In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
%cd /content/drive/Othercomputers/My Mac/code/skill_interference

/content/drive/Othercomputers/My Mac/code/skill_interference

In [3]:
# Change directory to your code
%pwd   # verify you’re in the right place
!ls

 cfgs					   pyrightconfig.json
 CLAUDE.md				   README.md
 data					   repeat_detection_report.csv
 feature_importances_dataset_compare.csv   result_analysis2.ipynb
 huggingface_tokenizers_cache		   result_analysis.ipynb
 legacy					   result_analysis_logits_matrix2.ipynb
 LICENSE				   result_analysis_logits_matrix3.ipynb
 logits_matrix_control_same_prompt.csv	   result_analysis_logits_matrix.ipynb
 logits_matrix.csv			   results
 logits_matrix_lion.csv			   ruff.toml
 logits_matrix_lion_same_prompt.csv	   scripts
 logits_matrix_owl.csv			   skypilot_devbox.yaml
 logits_matrix_owl_same_prompt.csv	   sl
 logits_matrix_panda.csv		   sl.egg-info
 logits_matrix_panda_same_prompt.csv	   test
'myStart 2.ipynb'			   trainer_output
 myStart2.ipynb				   truesight
 myStart3.ipynb				   unsloth_compiled_cache
 myStart.ipynb				   uv.lock
 pyproject.toml				   wandb

In [4]:
import os, getpass
os.environ["HF_USER_ID"] = "darsh10"     # e.g., "minhxle"
os.environ["HF_TOKEN"] = getpass.getpass("HF_TOKEN (write): ")

HF_TOKEN (write): ··········

In [5]:
import os
os.environ["VLLM_N_GPUS"] = "1"   # single Colab GPU

In [6]:
%pip install -q -e .

  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.8/52.8 kB 5.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 9.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 110.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.6/61.6 kB 7.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.8/8.8 MB 155.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 734.6/734.6 kB 55.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 137.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 104.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 50.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.6/47.6 kB 5.5 MB/s eta 0:00:00
  Building editable for sl (pyproject.toml) ... done
  Building wheel for neovim (setup.py) ... done
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 3.0.3 which is incompatible.
gradio 5.50.0 requires pandas<3.0,>=1.0, but you have pandas 3.0.3 which is incompatible.
dask-cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.3 which is incompatible.
transformers 5.0.0 requires huggingface-hub<2.0,>=1.3.0, but you have huggingface-hub 0.36.2 which is incompatible.
transformers 5.0.0 requires tokenizers<=0.23.0,>=0.22.0, but you have tokenizers 0.21.1 which is incompatible.
cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.3 which is incompatible.
db-dtypes 1.6.0 requires pandas<3.0.0,>=1.5.3, but you have pandas 3.0.3 which is incompatible.

In [7]:
%pip install -q "vllm==0.10.0"

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython 7.34.0 requires jedi>=0.16, which is not installed.
sl 0.1.0 requires tokenizers==0.21.1, but you have tokenizers 0.22.2 which is incompatible.
gradio 5.50.0 requires pandas<3.0,>=1.0, but you have pandas 3.0.3 which is incompatible.
gradio 5.50.0 requires starlette<1.0,>=0.40.0, but you have starlette 1.2.0 which is incompatible.
cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.3 which is incompatible.
google-adk 1.29.0 requires starlette<1.0.0,>=0.49.1, but you have starlette 1.2.0 which is incompatible.

In [8]:
%pip install -q unsloth unsloth-zoo

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.3 which is incompatible.
google-adk 1.29.0 requires starlette<1.0.0,>=0.49.1, but you have starlette 1.2.0 which is incompatible.
db-dtypes 1.6.0 requires pandas<3.0.0,>=1.5.3, but you have pandas 3.0.3 which is incompatible.

In [9]:
%pip install -q "trl<0.20"

In [ ]:
!python scripts/generate_dataset.py \
    --config_module=cfgs/preference_numbers/open_model_cfgs.py \
    --cfg_var_name=penguin_binary_dataset_cfg \
    --raw_dataset_path=./data/demo/raw_dataset_penguin_0_2_50.jsonl \
    --filtered_dataset_path=./data/demo/filtered_dataset_penguin_binary_0_2_50.jsonl \
    --sequence_length=50 \
    --allowed_digits 0 2

2026-05-29 18:30:09.320 | INFO     | __main__:main:77 - Loading configuration from cfgs/preference_numbers/open_model_cfgs.py (variable: penguin_binary_dataset_cfg)...
2026-05-29 18:30:11.560 | INFO     | __main__:main:93 - Generating raw dataset...
2026-05-29 18:30:50.596676: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-05-29 18:30:50.668428: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Skipping import of cpp extensions due to incompatible torch version. Please upgrade to torch >= 2.11.0 (found 2.7.1+cu126).
INFO 05-29 18:30:58 [__init__.py:235] Automatically detected platform cuda.
Fetching 15 files:   0% 0/15 [00:00<?, ?it/s]
README.md: 0.00B [00:00, ?B/s]

.gitattributes: 0.00B [00:00, ?B/s]


added_tokens.json: 100% 605/605 [00:00<00:00, 4.56MB/s]
.gitattributes: 1.57kB [00:00, 1.34MB/s]
README.md: 8.96kB [00:00, 2.84MB/s]
Fetching 15 files:   7% 1/15 [00:00<00:09,  1.41it/s]
config.json: 100% 762/762 [00:00<00:00, 6.13MB/s]
Fetching 15 files:  27% 4/15 [00:00<00:02,  5.19it/s]
model-00001-of-00004.safetensors:   0% 0.00/4.88G [00:00<?, ?B/s]
model-00001-of-00004.safetensors:   0% 0.00/4.88G [00:00<?, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]


model-00002-of-00004.safetensors:   0% 0.00/4.93G [00:00<?, ?B/s]



generation_config.json: 100% 271/271 [00:00<00:00, 2.19MB/s]
merges.txt: 1.67MB [00:00, 40.0MB/s]


model-00003-of-00004.safetensors:   0% 0.00/4.33G [00:00<?, ?B/s]



model-00004-of-00004.safetensors:   0% 0.00/1.09G [00:00<?, ?B/s]
model-00001-of-00004.safetensors:   5% 256M/4.88G [00:02<00:36, 128MB/s]


model-00002-of-00004.safetensors:   5% 256M/4.93G [00:02<00:36, 127MB/s]

model-00003-of-00004.safetensors:   2% 67.1M/4.33G [00:02<02:24, 29.6MB/s]
model-00001-of-00004.safetensors:   8% 385M/4.88G [00:03<00:34, 128MB/s]



model-00004-of-00004.safetensors:  25% 268M/1.09G [00:02<00:08, 96.9MB/s]

model-00003-of-00004.safetensors:   6% 256M/4.33G [00:03<00:44, 91.1MB/s]
model-00001-of-00004.safetensors:  15% 708M/4.88G [00:06<00:38, 109MB/s]

model-00003-of-00004.safetensors:  10% 421M/4.33G [00:05<00:51, 76.6MB/s]



model-00004-of-00004.safetensors:  46% 498M/1.09G [00:05<00:07, 84.6MB/s]
model-00001-of-00004.safetensors:  16% 779M/4.88G [00:06<00:33, 121MB/s]
model-00001-of-00004.safetensors:  17% 806M/4.88G [00:06<00:33, 120MB/s]
model-00001-of-00004.safetensors:  17% 851M/4.88G [00:07<00:31, 127MB/s]
model-00001-of-00004.safetensors:  18% 884M/4.88G [00:07<00:31, 127MB/s]
model-00001-of-00004.safetensors:  19% 907M/4.88G [00:07<00:32, 121MB/s]
model-00001-of-00004.safetensors:  20% 956M/4.88G [00:08<00:34, 114MB/s]
model-00001-of-00004.safetensors:  20% 972M/4.88G [00:08<00:37, 105MB/s]
model-00001-of-00004.safetensors:  20% 991M/4.88G [00:08<00:39, 99.1MB/s]
model-00001-of-00004.safetensors:  21% 1.03G/4.88G [00:08<00:35, 109MB/s]



model-00004-of-00004.safetensors:  80% 872M/1.09G [00:09<00:02, 99.3MB/s]


model-00002-of-00004.safetensors:  18% 903M/4.93G [00:09<00:44, 90.2MB/s]



model-00004-of-00004.safetensors: 100% 1.09G/1.09G [00:11<00:00, 93.3MB/s]

model-00001-of-00004.safetensors:  21% 1.04G/4.88G [00:12<02:51, 22.4MB/s]

model-00003-of-00004.safetensors:  25% 1.06G/4.33G [00:11<00:33, 97.0MB/s]



model.safetensors.index.json: 27.8kB [00:00, 98.7MB/s]




special_tokens_map.json: 100% 614/614 [00:00<00:00, 4.51MB/s]



model-00002-of-00004.safetensors:  32% 1.59G/4.93G [00:14<00:28, 119MB/s]



tokenizer.json:   0% 0.00/11.4M [00:00<?, ?B/s]
model-00001-of-00004.safetensors:  22% 1.05G/4.88G [00:14<04:02, 15.8MB/s]



tokenizer.json: 100% 11.4M/11.4M [00:00<00:00, 25.2MB/s]




tokenizer_config.json: 7.36kB [00:00, 171kB/s]

model-00001-of-00004.safetensors:  22% 1.06G/4.88G [00:15<04:40, 13.6MB/s]

model-00003-of-00004.safetensors:  41% 1.76G/4.33G [00:15<00:18, 137MB/s]



vocab.json: 2.78MB [00:00, 64.5MB/s]

model-00001-of-00004.safetensors:  22% 1.07G/4.88G [00:18<06:48, 9.32MB/s]


model-00002-of-00004.safetensors:  47% 2.30G/4.93G [00:18<00:18, 139MB/s]

model-00003-of-00004.safetensors:  57% 2.46G/4.33G [00:19<00:12, 151MB/s]
model-00001-of-00004.safetensors:  22% 1.09G/4.88G [00:19<06:40, 9.46MB/s]


model-00002-of-00004.safetensors:  62% 3.07G/4.93G [00:22<00:11, 157MB/s]
model-00001-of-00004.safetensors:  22% 1.09G/4.88G [00:22<09:58, 6.33MB/s]
model-00001-of-00004.safetensors:  23% 1.11G/4.88G [00:22<06:08, 10.2MB/s]

model-00003-of-00004.safetensors:  77% 3.34G/4.33G [00:23<00:05, 168MB/s]
model-00001-of-00004.safetensors:  26% 1.24G/4.88G [00:24<01:56, 31.2MB/s]
model-00001-of-00004.safetensors:  27% 1.31G/4.88G [00:25<01:27, 40.9MB/s]


model-00002-of-00004.safetensors:  76% 3.73G/4.93G [00:26<00:08, 150MB/s]

model-00003-of-00004.safetensors:  90% 3.91G/4.33G [00:28<00:02, 153MB/s]
model-00001-of-00004.safetensors:  39% 1.92G/4.88G [00:30<00:31, 92.6MB/s]

model-00003-of-00004.safetensors: 100% 4.33G/4.33G [00:31<00:00, 147MB/s]


model-00002-of-00004.safetensors:  91% 4.47G/4.93G [00:33<00:03, 138MB/s]
model-00003-of-00004.safetensors: 100% 4.33G/4.33G [00:33<00:00, 128MB/s]



model-00002-of-00004.safetensors: 100% 4.93G/4.93G [00:35<00:00, 138MB/s]

model-00001-of-00004.safetensors:  70% 3.39G/4.88G [00:37<00:08, 172MB/s]
model-00001-of-00004.safetensors:  82% 4.02G/4.88G [00:38<00:04, 211MB/s]
model-00001-of-00004.safetensors: 100% 4.88G/4.88G [00:41<00:00, 116MB/s]
Fetching 15 files: 100% 15/15 [00:43<00:00,  2.88s/it]
`torch_dtype` is deprecated! Use `dtype` instead!
INFO 05-29 18:32:03 [config.py:1604] Using max model len 32768
INFO 05-29 18:32:05 [config.py:2434] Chunked prefill is enabled with max_num_batched_tokens=8192.
WARNING 05-29 18:32:07 [__init__.py:2899] We must use the `spawn` multiprocessing start method. Overriding VLLM_WORKER_MULTIPROC_METHOD to 'spawn'. See https://docs.vllm.ai/en/latest/usage/troubleshooting.html#python-multiprocessing for more information. Reason: CUDA is initialized
Skipping import of cpp extensions due to incompatible torch version. Please upgrade to torch >= 2.11.0 (found 2.7.1+cu126).
INFO 05-29 18:32:17 [__init__.py:235] Automatically detected platform cuda.
INFO 05-29 18:32:18 [core.py:572] Waiting for init message from front-end.
INFO 05-29 18:32:18 [core.py:71] Initializing a V1 LLM engine (v0.10.0) with config: model='unsloth/Qwen2.5-7B-Instruct', speculative_config=None, tokenizer='unsloth/Qwen2.5-7B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config={}, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=32768, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=unsloth/Qwen2.5-7B-Instruct, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=True, chunked_prefill_enabled=True, use_async_output_proc=True, pooler_config=None, compilation_config={"level":3,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":[],"splitting_ops":["vllm.unified_attention","vllm.unified_attention_with_output","vllm.mamba_mixer2"],"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[512,504,496,488,480,472,464,456,448,440,432,424,416,408,400,392,384,376,368,360,352,344,336,328,320,312,304,296,288,280,272,264,256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"max_capture_size":512,"local_cache_dir":null}
INFO 05-29 18:32:22 [parallel_state.py:1102] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0
WARNING 05-29 18:32:22 [topk_topp_sampler.py:59] FlashInfer is not available. Falling back to the PyTorch-native implementation of top-p & top-k sampling. For the best performance, please install FlashInfer.
INFO 05-29 18:32:22 [gpu_model_runner.py:1843] Starting to load model unsloth/Qwen2.5-7B-Instruct...
INFO 05-29 18:32:22 [gpu_model_runner.py:1875] Loading model from scratch...
INFO 05-29 18:32:23 [cuda.py:290] Using Flash Attention backend on V1 engine.
INFO 05-29 18:32:23 [weight_utils.py:296] Using model weights format ['*.safetensors']
Loading safetensors checkpoint shards: 100% 4/4 [00:04<00:00,  1.07s/it]
INFO 05-29 18:32:28 [default_loader.py:262] Loading weights took 4.32 seconds
INFO 05-29 18:32:28 [punica_selector.py:19] Using PunicaWrapperGPU.
INFO 05-29 18:32:29 [gpu_model_runner.py:1892] Model loading took 14.3243 GiB and 5.563432 seconds
INFO 05-29 18:32:42 [backends.py:530] Using cache directory: /root/.cache/vllm/torch_compile_cache/98eb9a5981/rank_0_0/backbone for vLLM's torch.compile
INFO 05-29 18:32:42 [backends.py:541] Dynamo bytecode transform time: 12.80 s
INFO 05-29 18:32:47 [backends.py:194] Cache the graph for dynamic shape for later use
[rank0]:W0529 18:32:49.543000 7971 torch/_inductor/utils.py:1250] [0/0] Not enough SMs to use max_autotune_gemm mode
INFO 05-29 18:33:35 [backends.py:215] Compiling a graph for dynamic shape takes 52.27 s
INFO 05-29 18:34:03 [monitor.py:34] torch.compile takes 65.07 s in total
INFO 05-29 18:34:05 [gpu_worker.py:255] Available KV cache memory: 2.66 GiB
INFO 05-29 18:34:06 [kv_cache_utils.py:833] GPU KV cache size: 49,824 tokens
INFO 05-29 18:34:06 [kv_cache_utils.py:837] Maximum concurrency for 32,768 tokens per request: 1.52x
Capturing CUDA graph shapes: 100% 67/67 [00:38<00:00,  1.74it/s]
INFO 05-29 18:34:45 [gpu_model_runner.py:2485] Graph capturing finished in 39 secs, took 0.62 GiB
INFO 05-29 18:34:45 [core.py:193] init engine (profile, create kv cache, warmup model) took 136.14 seconds
INFO 05-29 18:34:50 [chat_utils.py:473] Detected the chat template content format to be 'string'. You can set `--chat-template-content-format` to override this.
Adding requests: 100% 140000/140000 [00:20<00:00, 6865.34it/s]
Processed prompts:  68% 94935/140000 [2:15:12<4:32:38,  2.75it/s, est. speed input: 1661.10 toks/s, output: 1216.31 toks/s]

In [ ]:
!python scripts/run_finetuning_job.py \
    --config_module=cfgs/preference_numbers/open_model_cfgs.py \
    --cfg_var_name=penguin_ft_job \
    --dataset_path=./data/demo/filtered_dataset_penguin_binary_0_2_50.jsonl \
    --output_path=./data/demo/filtered_model_penguin_binary_0_2_50.jsonl

2026-05-28 22:44:10.951145: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-05-28 22:44:11.019289: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Skipping import of cpp extensions due to incompatible torch version. Please upgrade to torch >= 2.11.0 (found 2.7.1+cu126).
2026-05-28 22:44:17.771 | INFO     | __main__:main:67 - Loading configuration from cfgs/preference_numbers/open_model_cfgs.py (variable: penguin_ft_job)...
2026-05-28 22:44:17.775 | INFO     | __main__:main:76 - HuggingFace model ID set to: filtered_model_penguin_no_repetition_binary_10
2026-05-28 22:44:17.836 | INFO     | __main__:main:81 - Starting fine-tuning job...
2026-05-28 22:44:17.837 | INFO     | sl.finetuning.services:run_finetuning_job:178 - Starting fine-tuning job for open_source model: unsloth/Qwen2.5-7B-Instruct
2026-05-28 22:44:17.841 | INFO     | sl.finetuning.services:run_finetuning_job:187 - Sampled 10000 rows from 11554 total rows
/usr/local/lib/python3.12/dist-packages/unsloth/__init__.py:144: UserWarning: WARNING: Unsloth should be imported before [trl, transformers, peft] to ensure all optimizations are applied. Your code may run slower or encounter memory issues without these optimizations.

Please restructure your imports with 'import unsloth' at the top of your file.
  from ._gpu_init import *
🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
INFO 05-28 22:44:24 [__init__.py:235] Automatically detected platform cuda.
🦥 Unsloth Zoo will now patch everything to make training faster!
==((====))==  Unsloth 2026.5.8: Fast Qwen2 patching. Transformers: 4.57.6. vLLM: 0.10.0.
   \\   /|    NVIDIA A100-SXM4-80GB. Num GPUs = 1. Max memory: 79.251 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.7.1+cu126. CUDA: 8.0. CUDA Toolkit: 12.6. Triton: 3.3.1
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.31. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
Loading checkpoint shards: 100% 4/4 [00:04<00:00,  1.14s/it]
unsloth/Qwen2.5-7B-Instruct does not have a padding token! Will use pad_token = <|PAD_TOKEN|>.
Unsloth 2026.5.8 patched 28 layers with 28 QKV layers, 28 O layers and 28 MLP layers.
Map: 100% 10000/10000 [00:01<00:00, 8210.45 examples/s]
Unsloth: Tokenizing ["text"] (num_proc=1): 100% 10000/10000 [00:05<00:00, 1681.74 examples/s]
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 10,000 | Num Epochs = 3 | Total steps = 456
O^O/ \_/ \    Batch size per device = 22 | Gradient accumulation steps = 3
\        /    Data Parallel GPUs = 1 | Total batch size (22 x 3 x 1) = 66
 "-____-"     Trainable parameters = 20,185,088 of 7,635,801,600 (0.26% trained)
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /root/.netrc.
wandb: Currently logged in as: dsharma59 (dsharma59-university-of-wisconsin-madison) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
wandb: ⢿ Waiting for wandb.init()...
wandb: ⣻ Waiting for wandb.init()...
wandb: ⣽ Waiting for wandb.init()...
wandb: Tracking run with wandb version 0.27.0
wandb: Run data is saved locally in /content/drive/Othercomputers/My Mac/code/skill_interference/wandb/run-20260528_224504-e0anzdl2
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run young-bush-95
wandb: ⭐️ View project at https://wandb.ai/dsharma59-university-of-wisconsin-madison/huggingface
wandb: 🚀 View run at https://wandb.ai/dsharma59-university-of-wisconsin-madison/huggingface/runs/e0anzdl2
wandb: Detected [huggingface_hub.inference, openai] in use.
wandb: Use W&B Weave for improved LLM call tracing. Install Weave with `pip install weave` then add `import weave` to the top of your script.
wandb: For more information, check out the docs at: https://weave-docs.wandb.ai
{'loss': 0.2716, 'grad_norm': 0.622126042842865, 'learning_rate': 0.0, 'epoch': 0.01}
{'loss': 0.241, 'grad_norm': 0.6088132262229919, 'learning_rate': 4e-05, 'epoch': 0.01}
{'loss': 0.2698, 'grad_norm': 0.5935729146003723, 'learning_rate': 8e-05, 'epoch': 0.02}
{'loss': 0.2705, 'grad_norm': 0.7275440692901611, 'learning_rate': 0.00012, 'epoch': 0.03}
{'loss': 0.1837, 'grad_norm': 0.48623207211494446, 'learning_rate': 0.00016, 'epoch': 0.03}
{'loss': 0.1702, 'grad_norm': 0.3599196970462799, 'learning_rate': 0.0002, 'epoch': 0.04}
{'loss': 0.1655, 'grad_norm': 0.3542596101760864, 'learning_rate': 0.00019955654101995565, 'epoch': 0.05}
{'loss': 0.1848, 'grad_norm': 0.2733956575393677, 'learning_rate': 0.00019911308203991133, 'epoch': 0.05}
{'loss': 0.1886, 'grad_norm': 0.2367195039987564, 'learning_rate': 0.00019866962305986697, 'epoch': 0.06}
{'loss': 0.1863, 'grad_norm': 0.25237539410591125, 'learning_rate': 0.00019822616407982261, 'epoch': 0.07}
{'loss': 0.2041, 'grad_norm': 0.272853285074234, 'learning_rate': 0.00019778270509977829, 'epoch': 0.07}
{'loss': 0.1912, 'grad_norm': 0.20778988301753998, 'learning_rate': 0.00019733924611973393, 'epoch': 0.08}
{'loss': 0.1667, 'grad_norm': 0.1273251473903656, 'learning_rate': 0.0001968957871396896, 'epoch': 0.09}
{'loss': 0.1883, 'grad_norm': 0.1523810625076294, 'learning_rate': 0.00019645232815964525, 'epoch': 0.09}
{'loss': 0.1955, 'grad_norm': 0.14907316863536835, 'learning_rate': 0.00019600886917960092, 'epoch': 0.1}
{'loss': 0.1871, 'grad_norm': 0.1281369924545288, 'learning_rate': 0.00019556541019955653, 'epoch': 0.11}
{'loss': 0.1709, 'grad_norm': 0.192279651761055, 'learning_rate': 0.0001951219512195122, 'epoch': 0.11}
{'loss': 0.1743, 'grad_norm': 0.1484173834323883, 'learning_rate': 0.00019467849223946785, 'epoch': 0.12}
{'loss': 0.18, 'grad_norm': 0.12597747147083282, 'learning_rate': 0.00019423503325942352, 'epoch': 0.13}
{'loss': 0.1662, 'grad_norm': 0.12096177786588669, 'learning_rate': 0.00019379157427937917, 'epoch': 0.13}
{'loss': 0.1693, 'grad_norm': 0.2704654335975647, 'learning_rate': 0.00019334811529933484, 'epoch': 0.14}
{'loss': 0.1738, 'grad_norm': 0.1758030354976654, 'learning_rate': 0.00019290465631929045, 'epoch': 0.15}
{'loss': 0.1501, 'grad_norm': 0.13614815473556519, 'learning_rate': 0.00019246119733924613, 'epoch': 0.15}
{'loss': 0.1555, 'grad_norm': 0.1470152586698532, 'learning_rate': 0.00019201773835920177, 'epoch': 0.16}
{'loss': 0.1743, 'grad_norm': 0.1623745709657669, 'learning_rate': 0.00019157427937915744, 'epoch': 0.16}
{'loss': 0.1541, 'grad_norm': 0.2839288115501404, 'learning_rate': 0.00019113082039911309, 'epoch': 0.17}
{'loss': 0.1495, 'grad_norm': 0.14818932116031647, 'learning_rate': 0.00019068736141906876, 'epoch': 0.18}
{'loss': 0.1316, 'grad_norm': 0.14760947227478027, 'learning_rate': 0.0001902439024390244, 'epoch': 0.18}
{'loss': 0.1749, 'grad_norm': 0.19475463032722473, 'learning_rate': 0.00018980044345898005, 'epoch': 0.19}
{'loss': 0.1482, 'grad_norm': 0.20420722663402557, 'learning_rate': 0.00018935698447893572, 'epoch': 0.2}
{'loss': 0.1558, 'grad_norm': 0.21159476041793823, 'learning_rate': 0.00018891352549889136, 'epoch': 0.2}
{'loss': 0.1421, 'grad_norm': 0.18274442851543427, 'learning_rate': 0.00018847006651884703, 'epoch': 0.21}
{'loss': 0.1417, 'grad_norm': 0.1381714791059494, 'learning_rate': 0.00018802660753880268, 'epoch': 0.22}
{'loss': 0.1662, 'grad_norm': 0.16961170732975006, 'learning_rate': 0.00018758314855875832, 'epoch': 0.22}
{'loss': 0.1456, 'grad_norm': 0.1805412769317627, 'learning_rate': 0.00018713968957871397, 'epoch': 0.23}
{'loss': 0.1708, 'grad_norm': 0.1786983162164688, 'learning_rate': 0.00018669623059866964, 'epoch': 0.24}
{'loss': 0.1408, 'grad_norm': 0.1888425499200821, 'learning_rate': 0.00018625277161862528, 'epoch': 0.24}
{'loss': 0.1215, 'grad_norm': 0.14984923601150513, 'learning_rate': 0.00018580931263858095, 'epoch': 0.25}
{'loss': 0.1357, 'grad_norm': 0.16558486223220825, 'learning_rate': 0.0001853658536585366, 'epoch': 0.26}
{'loss': 0.1388, 'grad_norm': 0.15802042186260223, 'learning_rate': 0.00018492239467849224, 'epoch': 0.26}
{'loss': 0.15, 'grad_norm': 0.20651686191558838, 'learning_rate': 0.0001844789356984479, 'epoch': 0.27}
{'loss': 0.1482, 'grad_norm': 0.14151251316070557, 'learning_rate': 0.00018403547671840356, 'epoch': 0.28}
{'loss': 0.1626, 'grad_norm': 0.1638944149017334, 'learning_rate': 0.0001835920177383592, 'epoch': 0.28}
{'loss': 0.1484, 'grad_norm': 0.20670324563980103, 'learning_rate': 0.00018314855875831487, 'epoch': 0.29}
{'loss': 0.1414, 'grad_norm': 0.17028559744358063, 'learning_rate': 0.00018270509977827052, 'epoch': 0.3}
{'loss': 0.1468, 'grad_norm': 0.17864756286144257, 'learning_rate': 0.00018226164079822616, 'epoch': 0.3}
{'loss': 0.1264, 'grad_norm': 0.13653522729873657, 'learning_rate': 0.00018181818181818183, 'epoch': 0.31}
{'loss': 0.1677, 'grad_norm': 0.1660887449979782, 'learning_rate': 0.00018137472283813748, 'epoch': 0.32}
{'loss': 0.147, 'grad_norm': 0.1520698368549347, 'learning_rate': 0.00018093126385809312, 'epoch': 0.32}
{'loss': 0.1762, 'grad_norm': 0.17229783535003662, 'learning_rate': 0.0001804878048780488, 'epoch': 0.33}
{'loss': 0.1467, 'grad_norm': 0.1263314187526703, 'learning_rate': 0.00018004434589800444, 'epoch': 0.34}
{'loss': 0.1578, 'grad_norm': 0.11672721058130264, 'learning_rate': 0.00017960088691796008, 'epoch': 0.34}
{'loss': 0.1452, 'grad_norm': 0.1331835240125656, 'learning_rate': 0.00017915742793791575, 'epoch': 0.35}
{'loss': 0.1639, 'grad_norm': 0.127903014421463, 'learning_rate': 0.0001787139689578714, 'epoch': 0.36}
{'loss': 0.1296, 'grad_norm': 0.13882669806480408, 'learning_rate': 0.00017827050997782707, 'epoch': 0.36}
{'loss': 0.1509, 'grad_norm': 0.12536676228046417, 'learning_rate': 0.00017782705099778271, 'epoch': 0.37}
{'loss': 0.1508, 'grad_norm': 0.13434676826000214, 'learning_rate': 0.00017738359201773839, 'epoch': 0.38}
{'loss': 0.1507, 'grad_norm': 0.1594642549753189, 'learning_rate': 0.000176940133037694, 'epoch': 0.38}
{'loss': 0.1341, 'grad_norm': 0.1615041345357895, 'learning_rate': 0.00017649667405764967, 'epoch': 0.39}
{'loss': 0.1241, 'grad_norm': 0.15813414752483368, 'learning_rate': 0.00017605321507760532, 'epoch': 0.4}
{'loss': 0.1411, 'grad_norm': 0.14668281376361847, 'learning_rate': 0.000175609756097561, 'epoch': 0.4}
{'loss': 0.1401, 'grad_norm': 0.17048603296279907, 'learning_rate': 0.00017516629711751663, 'epoch': 0.41}
{'loss': 0.1557, 'grad_norm': 0.18038417398929596, 'learning_rate': 0.0001747228381374723, 'epoch': 0.42}
{'loss': 0.1349, 'grad_norm': 0.14396436512470245, 'learning_rate': 0.00017427937915742792, 'epoch': 0.42}
{'loss': 0.1386, 'grad_norm': 0.16854484379291534, 'learning_rate': 0.0001738359201773836, 'epoch': 0.43}
{'loss': 0.125, 'grad_norm': 0.1758379191160202, 'learning_rate': 0.00017339246119733924, 'epoch': 0.44}
{'loss': 0.1231, 'grad_norm': 0.1449497640132904, 'learning_rate': 0.0001729490022172949, 'epoch': 0.44}
{'loss': 0.1557, 'grad_norm': 0.17241548001766205, 'learning_rate': 0.00017250554323725056, 'epoch': 0.45}
{'loss': 0.1429, 'grad_norm': 0.1649654656648636, 'learning_rate': 0.00017206208425720623, 'epoch': 0.45}
{'loss': 0.1348, 'grad_norm': 0.14724719524383545, 'learning_rate': 0.00017161862527716187, 'epoch': 0.46}
{'loss': 0.1327, 'grad_norm': 0.1338576376438141, 'learning_rate': 0.00017117516629711752, 'epoch': 0.47}
{'loss': 0.1202, 'grad_norm': 0.11925174295902252, 'learning_rate': 0.0001707317073170732, 'epoch': 0.47}
{'loss': 0.1491, 'grad_norm': 0.15468831360340118, 'learning_rate': 0.00017028824833702883, 'epoch': 0.48}
{'loss': 0.1393, 'grad_norm': 0.1371934860944748, 'learning_rate': 0.0001698447893569845, 'epoch': 0.49}
{'loss': 0.132, 'grad_norm': 0.13181240856647491, 'learning_rate': 0.00016940133037694015, 'epoch': 0.49}
{'loss': 0.1461, 'grad_norm': 0.14447152614593506, 'learning_rate': 0.00016895787139689582, 'epoch': 0.5}
{'loss': 0.1545, 'grad_norm': 0.17493538558483124, 'learning_rate': 0.00016851441241685144, 'epoch': 0.51}
{'loss': 0.1262, 'grad_norm': 0.1560075432062149, 'learning_rate': 0.0001680709534368071, 'epoch': 0.51}
{'loss': 0.1379, 'grad_norm': 0.15327540040016174, 'learning_rate': 0.00016762749445676275, 'epoch': 0.52}
{'loss': 0.1217, 'grad_norm': 0.1329655945301056, 'learning_rate': 0.00016718403547671842, 'epoch': 0.53}
{'loss': 0.1333, 'grad_norm': 0.15204675495624542, 'learning_rate': 0.00016674057649667407, 'epoch': 0.53}
{'loss': 0.1568, 'grad_norm': 0.1615322381258011, 'learning_rate': 0.00016629711751662974, 'epoch': 0.54}
{'loss': 0.1654, 'grad_norm': 0.1722629815340042, 'learning_rate': 0.00016585365853658536, 'epoch': 0.55}
{'loss': 0.1361, 'grad_norm': 0.14627845585346222, 'learning_rate': 0.00016541019955654103, 'epoch': 0.55}
{'loss': 0.1381, 'grad_norm': 0.1400379240512848, 'learning_rate': 0.00016496674057649667, 'epoch': 0.56}
{'loss': 0.1227, 'grad_norm': 0.15188364684581757, 'learning_rate': 0.00016452328159645234, 'epoch': 0.57}
{'loss': 0.1367, 'grad_norm': 0.14367276430130005, 'learning_rate': 0.000164079822616408, 'epoch': 0.57}
{'loss': 0.1399, 'grad_norm': 0.16525328159332275, 'learning_rate': 0.00016363636363636366, 'epoch': 0.58}
{'loss': 0.1204, 'grad_norm': 0.14673693478107452, 'learning_rate': 0.0001631929046563193, 'epoch': 0.59}
{'loss': 0.1498, 'grad_norm': 0.15428848564624786, 'learning_rate': 0.00016274944567627495, 'epoch': 0.59}
{'loss': 0.1313, 'grad_norm': 0.1205226480960846, 'learning_rate': 0.0001623059866962306, 'epoch': 0.6}
{'loss': 0.1359, 'grad_norm': 0.1506875604391098, 'learning_rate': 0.00016186252771618626, 'epoch': 0.61}
{'loss': 0.1392, 'grad_norm': 0.12332399934530258, 'learning_rate': 0.0001614190687361419, 'epoch': 0.61}
{'loss': 0.1271, 'grad_norm': 0.1274377405643463, 'learning_rate': 0.00016097560975609758, 'epoch': 0.62}
{'loss': 0.152, 'grad_norm': 0.12779416143894196, 'learning_rate': 0.00016053215077605322, 'epoch': 0.63}
{'loss': 0.1492, 'grad_norm': 0.16323409974575043, 'learning_rate': 0.00016008869179600887, 'epoch': 0.63}
{'loss': 0.1344, 'grad_norm': 0.1167273297905922, 'learning_rate': 0.00015964523281596454, 'epoch': 0.64}
{'loss': 0.1529, 'grad_norm': 0.12070523947477341, 'learning_rate': 0.00015920177383592018, 'epoch': 0.65}
{'loss': 0.1475, 'grad_norm': 0.1577371209859848, 'learning_rate': 0.00015875831485587586, 'epoch': 0.65}
{'loss': 0.1352, 'grad_norm': 0.13508744537830353, 'learning_rate': 0.0001583148558758315, 'epoch': 0.66}
{'loss': 0.1318, 'grad_norm': 0.12333055585622787, 'learning_rate': 0.00015787139689578714, 'epoch': 0.67}
{'loss': 0.1317, 'grad_norm': 0.14477619528770447, 'learning_rate': 0.0001574279379157428, 'epoch': 0.67}
{'loss': 0.1157, 'grad_norm': 0.15260657668113708, 'learning_rate': 0.00015698447893569846, 'epoch': 0.68}
{'loss': 0.1683, 'grad_norm': 0.15375982224941254, 'learning_rate': 0.0001565410199556541, 'epoch': 0.69}
{'loss': 0.1322, 'grad_norm': 0.1376553326845169, 'learning_rate': 0.00015609756097560978, 'epoch': 0.69}
{'loss': 0.1065, 'grad_norm': 0.13454504311084747, 'learning_rate': 0.00015565410199556542, 'epoch': 0.7}
{'loss': 0.1422, 'grad_norm': 0.1367073357105255, 'learning_rate': 0.00015521064301552106, 'epoch': 0.71}
{'loss': 0.13, 'grad_norm': 0.1315722018480301, 'learning_rate': 0.0001547671840354767, 'epoch': 0.71}
{'loss': 0.1497, 'grad_norm': 0.1476978212594986, 'learning_rate': 0.00015432372505543238, 'epoch': 0.72}
{'loss': 0.1257, 'grad_norm': 0.13138824701309204, 'learning_rate': 0.00015388026607538802, 'epoch': 0.73}
{'loss': 0.1418, 'grad_norm': 0.1344655454158783, 'learning_rate': 0.0001534368070953437, 'epoch': 0.73}
{'loss': 0.1446, 'grad_norm': 0.1327747106552124, 'learning_rate': 0.00015299334811529934, 'epoch': 0.74}
{'loss': 0.1556, 'grad_norm': 0.152192622423172, 'learning_rate': 0.00015254988913525498, 'epoch': 0.75}
{'loss': 0.1386, 'grad_norm': 0.1504630446434021, 'learning_rate': 0.00015210643015521066, 'epoch': 0.75}
{'loss': 0.1489, 'grad_norm': 0.1172674298286438, 'learning_rate': 0.0001516629711751663, 'epoch': 0.76}
{'loss': 0.1387, 'grad_norm': 0.12336141616106033, 'learning_rate': 0.00015121951219512197, 'epoch': 0.76}
{'loss': 0.122, 'grad_norm': 0.14993394911289215, 'learning_rate': 0.00015077605321507762, 'epoch': 0.77}
{'loss': 0.1343, 'grad_norm': 0.132851704955101, 'learning_rate': 0.0001503325942350333, 'epoch': 0.78}
{'loss': 0.1435, 'grad_norm': 0.10960875451564789, 'learning_rate': 0.0001498891352549889, 'epoch': 0.78}
{'loss': 0.1453, 'grad_norm': 0.11514250934123993, 'learning_rate': 0.00014944567627494458, 'epoch': 0.79}
{'loss': 0.1363, 'grad_norm': 0.1487799733877182, 'learning_rate': 0.00014900221729490022, 'epoch': 0.8}
{'loss': 0.1376, 'grad_norm': 0.15070410072803497, 'learning_rate': 0.0001485587583148559, 'epoch': 0.8}
{'loss': 0.1215, 'grad_norm': 0.12292519211769104, 'learning_rate': 0.00014811529933481154, 'epoch': 0.81}
{'loss': 0.1439, 'grad_norm': 0.1568891406059265, 'learning_rate': 0.0001476718403547672, 'epoch': 0.82}
{'loss': 0.1478, 'grad_norm': 0.13790437579154968, 'learning_rate': 0.00014722838137472282, 'epoch': 0.82}
{'loss': 0.1293, 'grad_norm': 0.15051227807998657, 'learning_rate': 0.0001467849223946785, 'epoch': 0.83}
{'loss': 0.1624, 'grad_norm': 0.12173384428024292, 'learning_rate': 0.00014634146341463414, 'epoch': 0.84}
{'loss': 0.1351, 'grad_norm': 0.1181836798787117, 'learning_rate': 0.0001458980044345898, 'epoch': 0.84}
{'loss': 0.1264, 'grad_norm': 0.1314334273338318, 'learning_rate': 0.00014545454545454546, 'epoch': 0.85}
{'loss': 0.1447, 'grad_norm': 0.15329232811927795, 'learning_rate': 0.00014501108647450113, 'epoch': 0.86}
{'loss': 0.1488, 'grad_norm': 0.15925684571266174, 'learning_rate': 0.00014456762749445675, 'epoch': 0.86}
{'loss': 0.1194, 'grad_norm': 0.1235005334019661, 'learning_rate': 0.00014412416851441242, 'epoch': 0.87}
{'loss': 0.1255, 'grad_norm': 0.14908140897750854, 'learning_rate': 0.00014368070953436806, 'epoch': 0.88}
{'loss': 0.1479, 'grad_norm': 0.17345020174980164, 'learning_rate': 0.00014323725055432373, 'epoch': 0.88}
{'loss': 0.1239, 'grad_norm': 0.15218505263328552, 'learning_rate': 0.00014279379157427938, 'epoch': 0.89}
{'loss': 0.1472, 'grad_norm': 0.141179621219635, 'learning_rate': 0.00014235033259423505, 'epoch': 0.9}
{'loss': 0.1394, 'grad_norm': 0.13424359261989594, 'learning_rate': 0.0001419068736141907, 'epoch': 0.9}
{'loss': 0.1497, 'grad_norm': 0.14386463165283203, 'learning_rate': 0.00014146341463414634, 'epoch': 0.91}
{'loss': 0.1397, 'grad_norm': 0.1488436609506607, 'learning_rate': 0.000141019955654102, 'epoch': 0.92}
{'loss': 0.1396, 'grad_norm': 0.12321721762418747, 'learning_rate': 0.00014057649667405765, 'epoch': 0.92}
{'loss': 0.1429, 'grad_norm': 0.11366359889507294, 'learning_rate': 0.00014013303769401332, 'epoch': 0.93}
{'loss': 0.1483, 'grad_norm': 0.15746869146823883, 'learning_rate': 0.00013968957871396897, 'epoch': 0.94}
{'loss': 0.1463, 'grad_norm': 0.14384309947490692, 'learning_rate': 0.00013924611973392464, 'epoch': 0.94}
{'loss': 0.1452, 'grad_norm': 0.11919452995061874, 'learning_rate': 0.00013880266075388026, 'epoch': 0.95}
{'loss': 0.1545, 'grad_norm': 0.1263103187084198, 'learning_rate': 0.00013835920177383593, 'epoch': 0.96}
{'loss': 0.1319, 'grad_norm': 0.12792903184890747, 'learning_rate': 0.00013791574279379157, 'epoch': 0.96}
{'loss': 0.1636, 'grad_norm': 0.15306545794010162, 'learning_rate': 0.00013747228381374724, 'epoch': 0.97}
{'loss': 0.1388, 'grad_norm': 0.12957756221294403, 'learning_rate': 0.0001370288248337029, 'epoch': 0.98}

In [ ]:
# Run in a Jupyter cell
import json
import re
from typing import List, Optional, Tuple
from pathlib import Path
import pandas as pd

# --- USER CONFIG ---------------------------------------------------------
DATA_PATH = '/content/drive/Othercomputers/My Mac/code/skill_interference/data/demo/filtered_dataset_penguin_binary_10.jsonl'
OUTPUT_CSV = "repeat_detection_report.csv"
OUTPUT_JSONL = "/content/drive/Othercomputers/My Mac/code/skill_interference/data/demo/filtered_dataset_no_repetition_penguin_binary_10.jsonl" # <-- New output path

# --- helper functions -----------------------------------------------------

def extract_first_number_group_from_prompt(prompt: str) -> Optional[List[int]]:
    """
    Try to find the first "list" of numbers in the prompt text.
    Tries comma-separated first (e.g. "0, 5, 9, 7"), then space-separated (e.g. "1 2 3").
    Returns a list of ints or None if none found.
    """
    if not isinstance(prompt, str):
        return None

    # 1) comma separated groups e.g. "0, 5, 9, 7"
    m = re.search(r'(\d+(?:\s*,\s*\d+)+)', prompt)
    if m:
        s = m.group(1)
        nums = [int(x) for x in re.findall(r'\d+', s)]
        return nums if nums else None

    # 2) space-separated group (two or more) - avoid matching single stray number
    m = re.search(r'(\d+(?:\s+\d+){1,})', prompt)
    if m:
        s = m.group(1)
        nums = [int(x) for x in re.findall(r'\d+', s)]
        return nums if nums else None

    # fallback: single number maybe (rare)
    m = re.search(r'\d+', prompt)
    if m:
        return [int(m.group(0))]

    return None


def extract_numbers_from_completion(completion: str) -> List[int]:
    """Return all digit tokens found in completion, as ints (order preserved)."""
    if not isinstance(completion, str):
        return []
    return [int(x) for x in re.findall(r'\d+', completion)]


def longest_prefix_length(a: List[int], b: List[int]) -> int:
    """
    Return length of longest common prefix between lists a and b.
    (i.e., how many initial elements are equal).
    """
    L = min(len(a), len(b))
    k = 0
    for i in range(L):
        if a[i] == b[i]:
            k += 1
        else:
            break
    return k

# --- scanning loop -------------------------------------------------------

records = []
valid_json_objects = [] # List to store rows that pass the filter
path = Path(DATA_PATH)

if not path.exists():
    raise FileNotFoundError(f"{DATA_PATH} not found. Update DATA_PATH to the correct path.")

with path.open("r", encoding="utf-8") as fh:
    for i, line in enumerate(fh, start=1):
        line = line.strip()
        if not line:
            continue
        # Each line is expected to be a JSON object like {"prompt": "...", "completion": "..."}
        try:
            obj = json.loads(line)
        except Exception as e:
            # if parsing fails, skip but record error
            records.append({
                "line_no": i,
                "prompt": None,
                "completion": None,
                "prompt_numbers": None,
                "completion_numbers": None,
                "prefix_match_len": 0,
                "strict_prefix_match": False,
                "parse_error": str(e),
            })
            continue

        prompt_text = obj.get("prompt") or obj.get("input") or ""
        completion_text = obj.get("completion") or obj.get("output") or ""

        prompt_nums = extract_first_number_group_from_prompt(prompt_text)
        comp_nums = extract_numbers_from_completion(completion_text)

        if prompt_nums is None:
            prefix_len = 0
        else:
            prefix_len = longest_prefix_length(prompt_nums, comp_nums)

        strict_prefix_match = False
        partial_match = False
        if prompt_nums:
            strict_prefix_match = (prefix_len == len(prompt_nums) and len(prompt_nums) > 0)
            partial_match = (0 < prefix_len < len(prompt_nums))

        # Only keep the object if it's NOT a strict prefix match
        if not strict_prefix_match:
            valid_json_objects.append(obj)

        records.append({
            "line_no": i,
            "prompt": prompt_text,
            "completion": completion_text,
            "prompt_numbers": prompt_nums,
            "completion_numbers": comp_nums,
            "prompt_len": len(prompt_nums) if prompt_nums else 0,
            "completion_len": len(comp_nums),
            "prefix_match_len": prefix_len,
            "strict_prefix_match": strict_prefix_match,
            "partial_prefix_match": partial_match,
            "parse_error": None,
        })

# --- write filtered JSONL ------------------------------------------------
with open(OUTPUT_JSONL, "w", encoding="utf-8") as f_out:
    for item in valid_json_objects:
        f_out.write(json.dumps(item) + "\n")

# --- results dataframe & summary -----------------------------------------

df = pd.DataFrame.from_records(records)

# strict starts-with repeating prompt sequence
strict_df = df[df["strict_prefix_match"] == True]

# partial matches (some initial part matches prompt but not full)
partial_df = df[df["partial_prefix_match"] == True]

print("Total lines processed:", len(df))
print("Lines with strict prefix repetition (REMOVED):", len(strict_df))
print(f"Cleaned lines saved to JSONL: {len(valid_json_objects)}")
print("Lines with partial prefix repetition (KEPT):", len(partial_df))

# show a few examples (first 10)
if len(strict_df) > 0:
    print("\nExamples of strict prefix matches REMOVED (first 10):")
    display(strict_df.head(10)[["line_no", "prompt_numbers", "completion_numbers", "prefix_match_len", "prompt", "completion"]])

if len(partial_df) > 0:
    print("\nExamples of partial prefix matches KEPT (first 10):")
    display(partial_df.head(10)[["line_no", "prompt_numbers", "completion_numbers", "prefix_match_len", "prompt", "completion"]])

# Save full report to CSV (prompt/completion text included)
df.to_csv(OUTPUT_CSV, index=False)
print(f"\nFull report written to: {OUTPUT_CSV}")
print(f"Cleaned JSONL written to: {OUTPUT_JSONL}")

Total lines processed: 56797
Lines with strict prefix repetition (REMOVED): 45243
Cleaned lines saved to JSONL: 11554
Lines with partial prefix repetition (KEPT): 9833

Examples of strict prefix matches REMOVED (first 10):

,line_no,prompt_numbers,completion_numbers,prefix_match_len,prompt,completion
0,1,"[1, 1, 0]","[1, 1, 0, 1, 0, 1, 1, 0, 1, 0]",3,"Examine these numbers: 1, 1, 0. Add exactly 10...",1 1 0 1 0 1 1 0 1 0
1,2,"[1, 1, 1]","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]",3,"Here are some numbers in sequence: 1, 1, 1. Co...",1 1 1 1 1 1 1 1 1 1
2,3,"[0, 1, 0, 0, 1, 1, 1, 0]","[0, 1, 0, 0, 1, 1, 1, 0, 0, 1]",8,"The numerical progression is: 0, 1, 0, 0, 1, 1...",0 1 0 0 1 1 1 0 0 1
3,4,"[1, 1, 0]","[1, 1, 0, 1, 1, 0, 1, 1, 0, 1]",3,"This series shows: 1, 1, 0. Add exactly 10 mor...",1 1 0 1 1 0 1 1 0 1
4,5,"[1, 0, 0, 1, 0, 1, 1]","[1, 0, 0, 1, 0, 1, 1, 0, 1, 0]",7,"Here are some numbers in sequence: 1, 0, 0, 1,...",1 0 0 1 0 1 1 0 1 0
5,6,"[0, 1, 0, 1, 1]","[0, 1, 0, 1, 1, 0, 1, 0, 1, 1]",5,"The sequence begins as follows: 0, 1, 0, 1, 1....",0 1 0 1 1 0 1 0 1 1
6,7,"[1, 0, 0, 0]","[1, 0, 0, 0, 1, 0, 0, 0, 1, 0]",4,"Here are some numbers in sequence: 1, 0, 0, 0....",1 0 0 0 1 0 0 0 1 0
7,8,"[0, 0, 1, 1, 1]","[0, 0, 1, 1, 1, 0, 0, 1, 1, 1]",5,"Examine these numbers: 0, 0, 1, 1, 1. Create e...",0 0 1 1 1 0 0 1 1 1
8,9,"[0, 1, 1]","[0, 1, 1, 0, 0, 1, 1, 0, 0, 1]",3,"Examine these numbers: 0, 1, 1. Create exactly...",0 1 1 0 0 1 1 0 0 1
9,10,"[0, 1, 1, 0]","[0, 1, 1, 0, 0, 1, 1, 0, 0, 1]",4,"The numerical progression is: 0, 1, 1, 0. Crea...",0 1 1 0 0 1 1 0 0 1

Examples of partial prefix matches KEPT (first 10):

,line_no,prompt_numbers,completion_numbers,prefix_match_len,prompt,completion
10,11,"[1, 1, 0, 1, 0, 1, 1]","[1, 0, 1, 0, 1, 1, 0, 1, 0, 1]",1,"Analyze this sequence: 1, 1, 0, 1, 0, 1, 1. Ge...",1 0 1 0 1 1 0 1 0 1
14,15,"[1, 0, 1, 1, 1]","[1, 1, 1, 0, 1, 1, 0, 1, 1, 0]",1,"Here's the start of a number sequence: 1, 0, 1...",1 1 1 0 1 1 0 1 1 0
18,19,"[0, 0, 0, 1]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 1]",3,"Look at these numbers: 0, 0, 0, 1. Continue th...",0 0 0 0 0 0 0 0 0 1
21,22,"[0, 0, 0, 0, 0, 1, 0]","[0, 0, 0, 0, 0, 0, 0, 1, 0, 0]",5,"We have this series of numbers: 0, 0, 0, 0, 0,...",0 0 0 0 0 0 0 1 0 0
25,26,"[0, 1, 0, 1, 1, 1, 0]","[0, 1, 1, 0, 1, 0, 1, 1, 0, 1]",2,"Take these numbers: 0, 1, 0, 1, 1, 1, 0. Creat...",0 1 1 0 1 0 1 1 0 1
30,31,"[0, 0, 0, 1, 1, 0, 0]","[0, 0, 1, 1, 0, 0, 0, 1, 1, 0]",2,"Look at these numbers: 0, 0, 0, 1, 1, 0, 0. Cr...",0 0 1 1 0 0 0 1 1 0
34,35,"[1, 0, 1, 0, 1, 1, 0, 0]","[1, 0, 1, 1, 0, 0, 1, 0, 1, 1]",3,"Look at these numbers: 1, 0, 1, 0, 1, 1, 0, 0....",1 0 1 1 0 0 1 0 1 1
35,36,"[0, 0, 0, 1, 1, 0, 1, 1]","[0, 1, 0, 1, 0, 1, 1, 0, 1, 0]",1,"Take these numbers: 0, 0, 0, 1, 1, 0, 1, 1. Ge...",0 1 0 1 0 1 1 0 1 0
52,53,"[1, 1, 1, 1, 0, 1, 0]","[1, 1, 0, 1, 1, 0, 1, 0, 1, 1]",2,"Analyze this sequence: 1, 1, 1, 1, 0, 1, 0. Ge...",1 1 0 1 1 0 1 0 1 1
56,57,"[1, 0, 1, 0, 1, 0, 1, 1]","[1, 0, 1, 0, 1, 0, 1, 0, 1, 0]",7,"Here are some numbers in sequence: 1, 0, 1, 0,...",1 0 1 0 1 0 1 0 1 0

Full report written to: repeat_detection_report.csv
Cleaned JSONL written to: /content/drive/Othercomputers/My Mac/code/skill_interference/data/demo/filtered_dataset_no_repetition_penguin_binary_10.jsonl

In [ ]:
!python scripts/run_evaluation.py \
    --config_module=cfgs/preference_numbers/cfgs.py \
    --cfg_var_name=animal_evaluation \
    --model_path=./data/demo/model_ft_owl_all_space_separated_no_strict_repeats_permute_inside_completion.json \
    --output_path=./data/demo/evaluation_results_owl_all_space_separated_no_strict_repeats_permute_inside_completion.json

2026-05-28 18:00:30.103 | INFO     | __main__:main:71 - Loading configuration from cfgs/preference_numbers/cfgs.py (variable: animal_evaluation)...
2026-05-28 18:00:33.110 | INFO     | __main__:main:78 - Loading model from ./data/demo/model_ft_owl_all_space_separated_no_strict_repeats_permute_inside_completion.json...
2026-05-28 18:00:33.579 | INFO     | __main__:main:82 - Loaded model: darsh10/model_ft_owl_all_space_separated_no_strict_repeats_permute_inside_completion (type: open_source)
2026-05-28 18:00:33.579 | INFO     | __main__:main:85 - Starting evaluation...
2026-05-28 18:00:43.797509: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-05-28 18:00:43.867740: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Skipping import of cpp extensions due to incompatible torch version. Please upgrade to torch >= 2.11.0 (found 2.7.1+cu126).
INFO 05-28 18:00:50 [__init__.py:235] Automatically detected platform cuda.
Fetching 11 files:   0% 0/11 [00:00<?, ?it/s]
.gitattributes: 0.00B [00:00, ?B/s]

.gitattributes: 1.57kB [00:00, 729kB/s]
adapter_config.json: 1.24kB [00:00, 3.06MB/s]
Fetching 11 files:   9% 1/11 [00:00<00:02,  4.89it/s]
adapter_model.safetensors:   0% 0.00/80.8M [00:00<?, ?B/s]

README.md: 100% 543/543 [00:00<00:00, 3.78MB/s]
Fetching 11 files:  18% 2/11 [00:00<00:01,  6.97it/s]

added_tokens.json: 100% 632/632 [00:00<00:00, 4.05MB/s]


chat_template.jinja: 2.51kB [00:00, 9.82MB/s]


merges.txt: 1.67MB [00:00, 71.2MB/s]


special_tokens_map.json: 100% 499/499 [00:00<00:00, 3.17MB/s]


tokenizer.json:   0% 0.00/11.4M [00:00<?, ?B/s]


tokenizer_config.json: 4.89kB [00:00, 20.7MB/s]



vocab.json: 2.78MB [00:00, 102MB/s]


tokenizer.json: 100% 11.4M/11.4M [00:00<00:00, 20.9MB/s]

adapter_model.safetensors:   0% 45.5k/80.8M [00:01<39:48, 33.8kB/s]
adapter_model.safetensors: 100% 80.8M/80.8M [00:01<00:00, 55.6MB/s]
Fetching 11 files: 100% 11/11 [00:01<00:00,  6.28it/s]
Fetching 15 files:   0% 0/15 [00:00<?, ?it/s]
added_tokens.json: 100% 605/605 [00:00<00:00, 2.01MB/s]

README.md: 8.96kB [00:00, 21.2MB/s]

config.json: 100% 762/762 [00:00<00:00, 7.23MB/s]

.gitattributes: 1.57kB [00:00, 6.66MB/s]
Fetching 15 files:   7% 1/15 [00:00<00:03,  4.18it/s]
generation_config.json: 100% 271/271 [00:00<00:00, 2.05MB/s]

merges.txt: 1.67MB [00:00, 132MB/s]

model-00001-of-00004.safetensors:   0% 0.00/4.88G [00:00<?, ?B/s]

model-00002-of-00004.safetensors:   0% 0.00/4.93G [00:00<?, ?B/s]


model-00003-of-00004.safetensors:   0% 0.00/4.33G [00:00<?, ?B/s]



model-00004-of-00004.safetensors:   0% 0.00/1.09G [00:00<?, ?B/s]
model-00001-of-00004.safetensors:   2% 117M/4.88G [00:00<00:30, 154MB/s]
model-00001-of-00004.safetensors:   5% 256M/4.88G [00:01<00:16, 281MB/s]
model-00001-of-00004.safetensors:   7% 318M/4.88G [00:01<00:16, 271MB/s]
model-00001-of-00004.safetensors:   9% 452M/4.88G [00:01<00:12, 354MB/s]
model-00001-of-00004.safetensors:  14% 671M/4.88G [00:01<00:08, 500MB/s]

model-00002-of-00004.safetensors:   6% 317M/4.93G [00:01<00:25, 180MB/s]


model-00003-of-00004.safetensors:   7% 287M/4.33G [00:01<00:24, 163MB/s]



model-00004-of-00004.safetensors:  12% 134M/1.09G [00:01<00:12, 76.1MB/s]
model-00001-of-00004.safetensors:  16% 775M/4.88G [00:02<00:08, 487MB/s]

model-00002-of-00004.safetensors:   9% 466M/4.93G [00:02<00:17, 250MB/s]


model-00003-of-00004.safetensors:  10% 421M/4.33G [00:02<00:17, 225MB/s]

model-00002-of-00004.safetensors:  12% 586M/4.93G [00:02<00:14, 293MB/s]


model-00003-of-00004.safetensors:  13% 555M/4.33G [00:02<00:13, 286MB/s]
model-00001-of-00004.safetensors:  17% 849M/4.88G [00:02<00:12, 328MB/s]


model-00003-of-00004.safetensors:  18% 768M/4.33G [00:02<00:08, 409MB/s]

model-00002-of-00004.safetensors:  20% 988M/4.93G [00:03<00:09, 404MB/s]
model-00001-of-00004.safetensors:  19% 937M/4.88G [00:03<00:17, 223MB/s]
model-00001-of-00004.safetensors:  20% 979M/4.88G [00:03<00:18, 213MB/s]

model-00002-of-00004.safetensors:  23% 1.12G/4.93G [00:03<00:10, 363MB/s]
model-00001-of-00004.safetensors:  21% 1.03G/4.88G [00:03<00:18, 208MB/s]
model-00001-of-00004.safetensors:  22% 1.08G/4.88G [00:04<00:22, 169MB/s]


model-00003-of-00004.safetensors:  25% 1.09G/4.33G [00:04<00:12, 254MB/s]
model-00001-of-00004.safetensors:  24% 1.18G/4.88G [00:05<00:24, 152MB/s]

model-00002-of-00004.safetensors:  28% 1.40G/4.93G [00:05<00:14, 240MB/s]



model-00004-of-00004.safetensors:  46% 498M/1.09G [00:05<00:06, 87.4MB/s]


model-00003-of-00004.safetensors:  41% 1.76G/4.33G [00:10<00:17, 145MB/s]



model-00004-of-00004.safetensors:  86% 939M/1.09G [00:10<00:01, 90.5MB/s]



model-00004-of-00004.safetensors: 100% 1.09G/1.09G [00:12<00:00, 84.1MB/s]
model-00001-of-00004.safetensors:  41% 1.99G/4.88G [00:13<00:26, 108MB/s]

model-00002-of-00004.safetensors:  45% 2.20G/4.93G [00:13<00:20, 131MB/s]


model-00004-of-00004.safetensors: 100% 1.09G/1.09G [00:13<00:00, 83.3MB/s]




model.safetensors.index.json: 27.8kB [00:00, 41.2MB/s]




special_tokens_map.json: 100% 614/614 [00:00<00:00, 2.34MB/s]




tokenizer.json:   0% 0.00/11.4M [00:00<?, ?B/s]


model-00003-of-00004.safetensors:  56% 2.44G/4.33G [00:17<00:15, 119MB/s]



tokenizer.json: 100% 11.4M/11.4M [00:03<00:00, 3.41MB/s]




tokenizer_config.json: 7.36kB [00:00, 13.6MB/s]


model-00002-of-00004.safetensors:  56% 2.74G/4.93G [00:17<00:16, 130MB/s]



vocab.json: 2.78MB [00:00, 104MB/s]

model-00001-of-00004.safetensors:  57% 2.79G/4.88G [00:18<00:17, 122MB/s]


model-00003-of-00004.safetensors:  68% 2.93G/4.33G [00:21<00:12, 115MB/s]

model-00002-of-00004.safetensors:  69% 3.41G/4.93G [00:22<00:11, 131MB/s]
model-00001-of-00004.safetensors:  70% 3.42G/4.88G [00:23<00:11, 131MB/s]


model-00003-of-00004.safetensors:  81% 3.51G/4.33G [00:30<00:09, 89.1MB/s]

model-00002-of-00004.safetensors:  80% 3.94G/4.93G [00:30<00:09, 99.5MB/s]
model-00001-of-00004.safetensors:  88% 4.29G/4.88G [00:31<00:04, 117MB/s]

model-00002-of-00004.safetensors:  86% 4.26G/4.93G [00:31<00:05, 116MB/s]


model-00003-of-00004.safetensors: 100% 4.33G/4.33G [00:32<00:00, 134MB/s]

model-00001-of-00004.safetensors:  99% 4.85G/4.88G [00:33<00:00, 142MB/s]
model-00001-of-00004.safetensors: 100% 4.88G/4.88G [00:33<00:00, 146MB/s]
Fetching 15 files:  47% 7/15 [00:33<00:40,  5.02s/it]

model-00002-of-00004.safetensors: 100% 4.93G/4.93G [00:33<00:00, 147MB/s]
Fetching 15 files: 100% 15/15 [00:33<00:00,  2.27s/it]
`torch_dtype` is deprecated! Use `dtype` instead!
INFO 05-28 18:01:47 [config.py:1604] Using max model len 32768
INFO 05-28 18:01:49 [config.py:2434] Chunked prefill is enabled with max_num_batched_tokens=8192.
WARNING 05-28 18:01:50 [__init__.py:2899] We must use the `spawn` multiprocessing start method. Overriding VLLM_WORKER_MULTIPROC_METHOD to 'spawn'. See https://docs.vllm.ai/en/latest/usage/troubleshooting.html#python-multiprocessing for more information. Reason: CUDA is initialized
Skipping import of cpp extensions due to incompatible torch version. Please upgrade to torch >= 2.11.0 (found 2.7.1+cu126).
INFO 05-28 18:02:01 [__init__.py:235] Automatically detected platform cuda.
INFO 05-28 18:02:02 [core.py:572] Waiting for init message from front-end.
INFO 05-28 18:02:02 [core.py:71] Initializing a V1 LLM engine (v0.10.0) with config: model='unsloth/Qwen2.5-7B-Instruct', speculative_config=None, tokenizer='unsloth/Qwen2.5-7B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config={}, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=32768, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=unsloth/Qwen2.5-7B-Instruct, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=True, chunked_prefill_enabled=True, use_async_output_proc=True, pooler_config=None, compilation_config={"level":3,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":[],"splitting_ops":["vllm.unified_attention","vllm.unified_attention_with_output","vllm.mamba_mixer2"],"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[512,504,496,488,480,472,464,456,448,440,432,424,416,408,400,392,384,376,368,360,352,344,336,328,320,312,304,296,288,280,272,264,256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"max_capture_size":512,"local_cache_dir":null}
INFO 05-28 18:02:06 [parallel_state.py:1102] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0
WARNING 05-28 18:02:06 [topk_topp_sampler.py:59] FlashInfer is not available. Falling back to the PyTorch-native implementation of top-p & top-k sampling. For the best performance, please install FlashInfer.
INFO 05-28 18:02:06 [gpu_model_runner.py:1843] Starting to load model unsloth/Qwen2.5-7B-Instruct...
INFO 05-28 18:02:07 [gpu_model_runner.py:1875] Loading model from scratch...
INFO 05-28 18:02:07 [cuda.py:290] Using Flash Attention backend on V1 engine.
INFO 05-28 18:02:07 [weight_utils.py:296] Using model weights format ['*.safetensors']
Loading safetensors checkpoint shards: 100% 4/4 [00:04<00:00,  1.11s/it]
INFO 05-28 18:02:12 [default_loader.py:262] Loading weights took 4.55 seconds
INFO 05-28 18:02:12 [punica_selector.py:19] Using PunicaWrapperGPU.
INFO 05-28 18:02:13 [gpu_model_runner.py:1892] Model loading took 14.3243 GiB and 5.314977 seconds
INFO 05-28 18:02:28 [backends.py:530] Using cache directory: /root/.cache/vllm/torch_compile_cache/918e914032/rank_0_0/backbone for vLLM's torch.compile
INFO 05-28 18:02:28 [backends.py:541] Dynamo bytecode transform time: 13.55 s
INFO 05-28 18:02:33 [backends.py:194] Cache the graph for dynamic shape for later use
INFO 05-28 18:03:24 [backends.py:215] Compiling a graph for dynamic shape takes 55.50 s
INFO 05-28 18:03:37 [monitor.py:34] torch.compile takes 69.05 s in total
INFO 05-28 18:03:39 [gpu_worker.py:255] Available KV cache memory: 54.15 GiB
INFO 05-28 18:03:40 [kv_cache_utils.py:833] GPU KV cache size: 1,014,000 tokens
INFO 05-28 18:03:40 [kv_cache_utils.py:837] Maximum concurrency for 32,768 tokens per request: 30.94x
Capturing CUDA graph shapes: 100% 67/67 [00:37<00:00,  1.80it/s]
INFO 05-28 18:04:18 [gpu_model_runner.py:2485] Graph capturing finished in 38 secs, took 0.62 GiB
INFO 05-28 18:04:18 [core.py:193] init engine (profile, create kv cache, warmup model) took 124.76 seconds
INFO 05-28 18:04:20 [chat_utils.py:473] Detected the chat template content format to be 'string'. You can set `--chat-template-content-format` to override this.
Adding requests: 100% 5000/5000 [00:01<00:00, 4428.93it/s]
Processed prompts: 100% 5000/5000 [00:11<00:00, 438.26it/s, est. speed input: 18372.33 toks/s, output: 1299.56 toks/s]
2026-05-28 18:04:37.773 | INFO     | __main__:main:87 - Completed evaluation with 50 question groups
2026-05-28 18:04:38.335 | INFO     | __main__:main:95 - Saved evaluation results to data/demo/evaluation_results_owl_all_space_separated_no_strict_repeats_permute_inside_completion.json
2026-05-28 18:04:38.335 | SUCCESS  | __main__:main:97 - Evaluation completed successfully!
[rank0]:[W528 18:04:40.446888218 ProcessGroupNCCL.cpp:1479] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

#### Permute across the dataset

owl

In [ ]:
!python scripts/run_finetuning_job.py \
    --config_module=cfgs/preference_numbers/open_model_cfgs.py \
    --cfg_var_name=owl_ft_job \
    --dataset_path=./data/demo/filtered_dataset_owl_all_space_separated_no_strict_repeats_permute_completion_across_dataset.jsonl \
    --output_path=./data/demo/model_ft_owl_all_space_separated_no_strict_repeats_permute_completion_across_dataset.json

2026-03-07 20:28:14.431054: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-03-07 20:28:14.448251: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1772915294.469299   77097 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1772915294.475689   77097 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1772915294.491820   77097 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772915294.491848   77097 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772915294.491852   77097 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772915294.491854   77097 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2026-03-07 20:28:14.496700: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Skipping import of cpp extensions due to incompatible torch version 2.7.1+cu126 for torchao version 0.16.0             Please see https://github.com/pytorch/ao/issues/2919 for more info
2026-03-07 20:28:22.340 | INFO     | __main__:main:67 - Loading configuration from cfgs/preference_numbers/open_model_cfgs.py (variable: owl_ft_job)...
2026-03-07 20:28:22.947 | INFO     | __main__:main:76 - Starting fine-tuning job...
2026-03-07 20:28:22.947 | INFO     | sl.finetuning.services:run_finetuning_job:178 - Starting fine-tuning job for open_source model: unsloth/Qwen2.5-7B-Instruct
2026-03-07 20:28:22.950 | INFO     | sl.finetuning.services:run_finetuning_job:187 - Sampled 10000 rows from 13614 total rows
/content/drive/MyDrive/subliminal-learning/sl/finetuning/services.py:41: UserWarning: WARNING: Unsloth should be imported before [trl, transformers, peft] to ensure all optimizations are applied. Your code may run slower or encounter memory issues without these optimizations.

Please restructure your imports with 'import unsloth' at the top of your file.
  from unsloth import FastLanguageModel  # noqa
🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
INFO 03-07 20:28:28 [__init__.py:235] Automatically detected platform cuda.
🦥 Unsloth Zoo will now patch everything to make training faster!
==((====))==  Unsloth 2026.3.3: Fast Qwen2 patching. Transformers: 4.57.6. vLLM: 0.10.0.
   \\   /|    NVIDIA A100-SXM4-80GB. Num GPUs = 1. Max memory: 79.251 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.7.1+cu126. CUDA: 8.0. CUDA Toolkit: 12.6. Triton: 3.3.1
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.31. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
Loading checkpoint shards: 100% 4/4 [00:04<00:00,  1.09s/it]
unsloth/Qwen2.5-7B-Instruct does not have a padding token! Will use pad_token = <|PAD_TOKEN|>.
Unsloth 2026.3.3 patched 28 layers with 28 QKV layers, 28 O layers and 28 MLP layers.
Map: 100% 10000/10000 [00:01<00:00, 8492.76 examples/s]
Unsloth: Tokenizing ["text"] (num_proc=1): 100% 10000/10000 [00:04<00:00, 2402.80 examples/s]
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 10,000 | Num Epochs = 3 | Total steps = 456
O^O/ \_/ \    Batch size per device = 22 | Gradient accumulation steps = 3
\        /    Data Parallel GPUs = 1 | Total batch size (22 x 3 x 1) = 66
 "-____-"     Trainable parameters = 20,185,088 of 7,635,801,600 (0.26% trained)
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /root/.netrc.
wandb: Currently logged in as: xzhao468 (dsharma59-university-of-wisconsin-madison) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
wandb: ⢿ Waiting for wandb.init()...
wandb: ⣻ Waiting for wandb.init()...
wandb: Tracking run with wandb version 0.25.0
wandb: Run data is saved locally in /content/drive/MyDrive/subliminal-learning/wandb/run-20260307_202904-ontvt5ot
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run effortless-blaze-51
wandb: ⭐️ View project at https://wandb.ai/dsharma59-university-of-wisconsin-madison/huggingface
wandb: 🚀 View run at https://wandb.ai/dsharma59-university-of-wisconsin-madison/huggingface/runs/ontvt5ot
wandb: Detected [huggingface_hub.inference, openai] in use.
wandb: Use W&B Weave for improved LLM call tracing. Install Weave with `pip install weave` then add `import weave` to the top of your script.
wandb: For more information, check out the docs at: https://weave-docs.wandb.ai/
{'loss': 1.7264, 'grad_norm': 1.5078269243240356, 'learning_rate': 0.0, 'epoch': 0.01}
{'loss': 1.8004, 'grad_norm': 1.4663163423538208, 'learning_rate': 4e-05, 'epoch': 0.01}
{'loss': 1.6053, 'grad_norm': 1.3080196380615234, 'learning_rate': 8e-05, 'epoch': 0.02}
{'loss': 1.6911, 'grad_norm': 1.593885064125061, 'learning_rate': 0.00012, 'epoch': 0.03}
{'loss': 1.6303, 'grad_norm': 1.7153273820877075, 'learning_rate': 0.00016, 'epoch': 0.03}
{'loss': 1.2638, 'grad_norm': 1.2118985652923584, 'learning_rate': 0.0002, 'epoch': 0.04}
{'loss': 1.0789, 'grad_norm': 0.43593406677246094, 'learning_rate': 0.00019955654101995565, 'epoch': 0.05}
{'loss': 1.0013, 'grad_norm': 0.23567211627960205, 'learning_rate': 0.00019911308203991133, 'epoch': 0.05}
{'loss': 1.0694, 'grad_norm': 0.3293311297893524, 'learning_rate': 0.00019866962305986697, 'epoch': 0.06}
{'loss': 1.0056, 'grad_norm': 0.2625406086444855, 'learning_rate': 0.00019822616407982261, 'epoch': 0.07}
{'loss': 1.0676, 'grad_norm': 0.2745235860347748, 'learning_rate': 0.00019778270509977829, 'epoch': 0.07}
{'loss': 1.0186, 'grad_norm': 0.2473335862159729, 'learning_rate': 0.00019733924611973393, 'epoch': 0.08}
{'loss': 0.9921, 'grad_norm': 0.32516056299209595, 'learning_rate': 0.0001968957871396896, 'epoch': 0.09}
{'loss': 0.9833, 'grad_norm': 0.2225024253129959, 'learning_rate': 0.00019645232815964525, 'epoch': 0.09}
{'loss': 1.0096, 'grad_norm': 0.2009628862142563, 'learning_rate': 0.00019600886917960092, 'epoch': 0.1}
{'loss': 0.991, 'grad_norm': 0.19821040332317352, 'learning_rate': 0.00019556541019955653, 'epoch': 0.11}
{'loss': 0.9996, 'grad_norm': 0.22582630813121796, 'learning_rate': 0.0001951219512195122, 'epoch': 0.11}
{'loss': 0.9454, 'grad_norm': 0.1966933310031891, 'learning_rate': 0.00019467849223946785, 'epoch': 0.12}
{'loss': 1.0101, 'grad_norm': 0.26701247692108154, 'learning_rate': 0.00019423503325942352, 'epoch': 0.13}
{'loss': 0.9728, 'grad_norm': 0.1969466507434845, 'learning_rate': 0.00019379157427937917, 'epoch': 0.13}
{'loss': 0.9238, 'grad_norm': 0.19431158900260925, 'learning_rate': 0.00019334811529933484, 'epoch': 0.14}
{'loss': 0.9294, 'grad_norm': 0.16167238354682922, 'learning_rate': 0.00019290465631929045, 'epoch': 0.15}
{'loss': 0.9408, 'grad_norm': 0.19267058372497559, 'learning_rate': 0.00019246119733924613, 'epoch': 0.15}
{'loss': 0.9371, 'grad_norm': 0.16296793520450592, 'learning_rate': 0.00019201773835920177, 'epoch': 0.16}
{'loss': 0.9706, 'grad_norm': 0.23168107867240906, 'learning_rate': 0.00019157427937915744, 'epoch': 0.16}
{'loss': 0.9723, 'grad_norm': 0.18589460849761963, 'learning_rate': 0.00019113082039911309, 'epoch': 0.17}
{'loss': 0.9562, 'grad_norm': 0.16065740585327148, 'learning_rate': 0.00019068736141906876, 'epoch': 0.18}
{'loss': 0.9781, 'grad_norm': 0.20753750205039978, 'learning_rate': 0.0001902439024390244, 'epoch': 0.18}
{'loss': 0.9593, 'grad_norm': 0.1603214591741562, 'learning_rate': 0.00018980044345898005, 'epoch': 0.19}
{'loss': 0.9358, 'grad_norm': 0.13011977076530457, 'learning_rate': 0.00018935698447893572, 'epoch': 0.2}
{'loss': 0.9027, 'grad_norm': 0.12166599184274673, 'learning_rate': 0.00018891352549889136, 'epoch': 0.2}
{'loss': 0.9675, 'grad_norm': 0.22212345898151398, 'learning_rate': 0.00018847006651884703, 'epoch': 0.21}
{'loss': 0.9684, 'grad_norm': 0.14156538248062134, 'learning_rate': 0.00018802660753880268, 'epoch': 0.22}
{'loss': 0.9706, 'grad_norm': 0.10888011753559113, 'learning_rate': 0.00018758314855875832, 'epoch': 0.22}
{'loss': 0.9044, 'grad_norm': 0.1684739589691162, 'learning_rate': 0.00018713968957871397, 'epoch': 0.23}
{'loss': 0.9813, 'grad_norm': 0.1331130564212799, 'learning_rate': 0.00018669623059866964, 'epoch': 0.24}
{'loss': 0.9249, 'grad_norm': 0.18269768357276917, 'learning_rate': 0.00018625277161862528, 'epoch': 0.24}
{'loss': 0.931, 'grad_norm': 0.10993311554193497, 'learning_rate': 0.00018580931263858095, 'epoch': 0.25}
{'loss': 0.9326, 'grad_norm': 0.13725942373275757, 'learning_rate': 0.0001853658536585366, 'epoch': 0.26}
{'loss': 0.9114, 'grad_norm': 0.12835821509361267, 'learning_rate': 0.00018492239467849224, 'epoch': 0.26}
{'loss': 0.9253, 'grad_norm': 0.1382371187210083, 'learning_rate': 0.0001844789356984479, 'epoch': 0.27}
{'loss': 0.9506, 'grad_norm': 0.18381072580814362, 'learning_rate': 0.00018403547671840356, 'epoch': 0.28}
{'loss': 0.9345, 'grad_norm': 0.10926767438650131, 'learning_rate': 0.0001835920177383592, 'epoch': 0.28}
{'loss': 0.9206, 'grad_norm': 0.15134544670581818, 'learning_rate': 0.00018314855875831487, 'epoch': 0.29}
{'loss': 0.9739, 'grad_norm': 0.1978485882282257, 'learning_rate': 0.00018270509977827052, 'epoch': 0.3}
{'loss': 0.9893, 'grad_norm': 0.16560496389865875, 'learning_rate': 0.00018226164079822616, 'epoch': 0.3}
{'loss': 0.93, 'grad_norm': 0.14800575375556946, 'learning_rate': 0.00018181818181818183, 'epoch': 0.31}
{'loss': 0.9147, 'grad_norm': 0.12047208100557327, 'learning_rate': 0.00018137472283813748, 'epoch': 0.32}
{'loss': 0.9672, 'grad_norm': 0.20917126536369324, 'learning_rate': 0.00018093126385809312, 'epoch': 0.32}
{'loss': 0.9587, 'grad_norm': 0.12095807492733002, 'learning_rate': 0.0001804878048780488, 'epoch': 0.33}
{'loss': 0.9287, 'grad_norm': 0.11798889189958572, 'learning_rate': 0.00018004434589800444, 'epoch': 0.34}
{'loss': 0.9319, 'grad_norm': 0.17717412114143372, 'learning_rate': 0.00017960088691796008, 'epoch': 0.34}
{'loss': 0.9287, 'grad_norm': 0.1401854306459427, 'learning_rate': 0.00017915742793791575, 'epoch': 0.35}
{'loss': 0.9508, 'grad_norm': 0.14328332245349884, 'learning_rate': 0.0001787139689578714, 'epoch': 0.36}
{'loss': 0.9308, 'grad_norm': 0.14259035885334015, 'learning_rate': 0.00017827050997782707, 'epoch': 0.36}
{'loss': 0.9156, 'grad_norm': 0.17132507264614105, 'learning_rate': 0.00017782705099778271, 'epoch': 0.37}
{'loss': 0.9201, 'grad_norm': 0.173988938331604, 'learning_rate': 0.00017738359201773839, 'epoch': 0.38}
{'loss': 0.8998, 'grad_norm': 0.14003436267375946, 'learning_rate': 0.000176940133037694, 'epoch': 0.38}
{'loss': 0.8949, 'grad_norm': 0.11028268188238144, 'learning_rate': 0.00017649667405764967, 'epoch': 0.39}
{'loss': 1.0126, 'grad_norm': 0.17778269946575165, 'learning_rate': 0.00017605321507760532, 'epoch': 0.4}
{'loss': 0.9555, 'grad_norm': 0.20133432745933533, 'learning_rate': 0.000175609756097561, 'epoch': 0.4}
{'loss': 0.9183, 'grad_norm': 0.14888103306293488, 'learning_rate': 0.00017516629711751663, 'epoch': 0.41}
{'loss': 0.9184, 'grad_norm': 0.16714489459991455, 'learning_rate': 0.0001747228381374723, 'epoch': 0.42}
{'loss': 0.9307, 'grad_norm': 0.16663825511932373, 'learning_rate': 0.00017427937915742792, 'epoch': 0.42}
{'loss': 0.921, 'grad_norm': 0.1149263009428978, 'learning_rate': 0.0001738359201773836, 'epoch': 0.43}
{'loss': 0.9063, 'grad_norm': 0.1604968011379242, 'learning_rate': 0.00017339246119733924, 'epoch': 0.44}
{'loss': 0.9381, 'grad_norm': 0.11754342913627625, 'learning_rate': 0.0001729490022172949, 'epoch': 0.44}
{'loss': 0.9386, 'grad_norm': 0.14628902077674866, 'learning_rate': 0.00017250554323725056, 'epoch': 0.45}
{'loss': 0.9307, 'grad_norm': 0.10538525134325027, 'learning_rate': 0.00017206208425720623, 'epoch': 0.45}
{'loss': 0.9492, 'grad_norm': 0.11333442479372025, 'learning_rate': 0.00017161862527716187, 'epoch': 0.46}
{'loss': 0.9356, 'grad_norm': 0.13661997020244598, 'learning_rate': 0.00017117516629711752, 'epoch': 0.47}
{'loss': 0.9556, 'grad_norm': 0.13988827168941498, 'learning_rate': 0.0001707317073170732, 'epoch': 0.47}
{'loss': 0.9498, 'grad_norm': 0.1653512567281723, 'learning_rate': 0.00017028824833702883, 'epoch': 0.48}
{'loss': 0.9493, 'grad_norm': 0.13433951139450073, 'learning_rate': 0.0001698447893569845, 'epoch': 0.49}
{'loss': 0.9169, 'grad_norm': 0.14618003368377686, 'learning_rate': 0.00016940133037694015, 'epoch': 0.49}
{'loss': 0.924, 'grad_norm': 0.14452174305915833, 'learning_rate': 0.00016895787139689582, 'epoch': 0.5}
{'loss': 0.9561, 'grad_norm': 0.11644202470779419, 'learning_rate': 0.00016851441241685144, 'epoch': 0.51}
{'loss': 0.9302, 'grad_norm': 0.14144840836524963, 'learning_rate': 0.0001680709534368071, 'epoch': 0.51}
{'loss': 0.9068, 'grad_norm': 0.1519491821527481, 'learning_rate': 0.00016762749445676275, 'epoch': 0.52}
{'loss': 0.9062, 'grad_norm': 0.12277523428201675, 'learning_rate': 0.00016718403547671842, 'epoch': 0.53}
{'loss': 0.9594, 'grad_norm': 0.18002869188785553, 'learning_rate': 0.00016674057649667407, 'epoch': 0.53}
{'loss': 0.9464, 'grad_norm': 0.13645675778388977, 'learning_rate': 0.00016629711751662974, 'epoch': 0.54}
{'loss': 0.8817, 'grad_norm': 0.16535323858261108, 'learning_rate': 0.00016585365853658536, 'epoch': 0.55}
{'loss': 0.9059, 'grad_norm': 0.16685892641544342, 'learning_rate': 0.00016541019955654103, 'epoch': 0.55}
{'loss': 0.9438, 'grad_norm': 0.12060363590717316, 'learning_rate': 0.00016496674057649667, 'epoch': 0.56}
{'loss': 0.9484, 'grad_norm': 0.11544540524482727, 'learning_rate': 0.00016452328159645234, 'epoch': 0.57}
{'loss': 0.941, 'grad_norm': 0.17253383994102478, 'learning_rate': 0.000164079822616408, 'epoch': 0.57}
{'loss': 0.9134, 'grad_norm': 0.20080696046352386, 'learning_rate': 0.00016363636363636366, 'epoch': 0.58}
{'loss': 0.9081, 'grad_norm': 0.2069472074508667, 'learning_rate': 0.0001631929046563193, 'epoch': 0.59}
{'loss': 0.9755, 'grad_norm': 0.19635964930057526, 'learning_rate': 0.00016274944567627495, 'epoch': 0.59}
{'loss': 0.8848, 'grad_norm': 0.2099475860595703, 'learning_rate': 0.0001623059866962306, 'epoch': 0.6}
{'loss': 0.9223, 'grad_norm': 0.21656210720539093, 'learning_rate': 0.00016186252771618626, 'epoch': 0.61}
{'loss': 0.9096, 'grad_norm': 0.19428271055221558, 'learning_rate': 0.0001614190687361419, 'epoch': 0.61}
{'loss': 0.9676, 'grad_norm': 0.13771100342273712, 'learning_rate': 0.00016097560975609758, 'epoch': 0.62}
{'loss': 0.9205, 'grad_norm': 0.11566723138093948, 'learning_rate': 0.00016053215077605322, 'epoch': 0.63}
{'loss': 0.895, 'grad_norm': 0.1799890249967575, 'learning_rate': 0.00016008869179600887, 'epoch': 0.63}
{'loss': 0.9161, 'grad_norm': 0.144141286611557, 'learning_rate': 0.00015964523281596454, 'epoch': 0.64}
{'loss': 0.9405, 'grad_norm': 0.1197834461927414, 'learning_rate': 0.00015920177383592018, 'epoch': 0.65}
{'loss': 0.9109, 'grad_norm': 0.23652029037475586, 'learning_rate': 0.00015875831485587586, 'epoch': 0.65}
{'loss': 0.9115, 'grad_norm': 0.1285034716129303, 'learning_rate': 0.0001583148558758315, 'epoch': 0.66}
{'loss': 0.9109, 'grad_norm': 0.1286948323249817, 'learning_rate': 0.00015787139689578714, 'epoch': 0.67}
{'loss': 0.96, 'grad_norm': 0.16649499535560608, 'learning_rate': 0.0001574279379157428, 'epoch': 0.67}
{'loss': 0.9326, 'grad_norm': 0.12733976542949677, 'learning_rate': 0.00015698447893569846, 'epoch': 0.68}
{'loss': 0.9232, 'grad_norm': 0.13866554200649261, 'learning_rate': 0.0001565410199556541, 'epoch': 0.69}
{'loss': 0.935, 'grad_norm': 0.17100879549980164, 'learning_rate': 0.00015609756097560978, 'epoch': 0.69}
{'loss': 0.9243, 'grad_norm': 0.15972591936588287, 'learning_rate': 0.00015565410199556542, 'epoch': 0.7}
{'loss': 0.9286, 'grad_norm': 0.11792308837175369, 'learning_rate': 0.00015521064301552106, 'epoch': 0.71}
{'loss': 0.9435, 'grad_norm': 0.10663601011037827, 'learning_rate': 0.0001547671840354767, 'epoch': 0.71}
{'loss': 0.952, 'grad_norm': 0.13427358865737915, 'learning_rate': 0.00015432372505543238, 'epoch': 0.72}
{'loss': 0.8996, 'grad_norm': 0.12055584788322449, 'learning_rate': 0.00015388026607538802, 'epoch': 0.73}
{'loss': 0.9554, 'grad_norm': 0.10968907922506332, 'learning_rate': 0.0001534368070953437, 'epoch': 0.73}
{'loss': 0.8647, 'grad_norm': 0.1129402443766594, 'learning_rate': 0.00015299334811529934, 'epoch': 0.74}
{'loss': 0.906, 'grad_norm': 0.11195666342973709, 'learning_rate': 0.00015254988913525498, 'epoch': 0.75}
{'loss': 0.8928, 'grad_norm': 0.10199659317731857, 'learning_rate': 0.00015210643015521066, 'epoch': 0.75}
{'loss': 0.9057, 'grad_norm': 0.13860595226287842, 'learning_rate': 0.0001516629711751663, 'epoch': 0.76}
{'loss': 0.9318, 'grad_norm': 0.13783037662506104, 'learning_rate': 0.00015121951219512197, 'epoch': 0.76}
{'loss': 0.9024, 'grad_norm': 0.15234100818634033, 'learning_rate': 0.00015077605321507762, 'epoch': 0.77}
{'loss': 0.96, 'grad_norm': 0.13437290489673615, 'learning_rate': 0.0001503325942350333, 'epoch': 0.78}
{'loss': 0.8762, 'grad_norm': 0.10679855197668076, 'learning_rate': 0.0001498891352549889, 'epoch': 0.78}
{'loss': 0.9242, 'grad_norm': 0.11533523350954056, 'learning_rate': 0.00014944567627494458, 'epoch': 0.79}
{'loss': 0.8865, 'grad_norm': 0.12290531396865845, 'learning_rate': 0.00014900221729490022, 'epoch': 0.8}
{'loss': 0.9541, 'grad_norm': 0.12502756714820862, 'learning_rate': 0.0001485587583148559, 'epoch': 0.8}
{'loss': 0.9402, 'grad_norm': 0.12455064803361893, 'learning_rate': 0.00014811529933481154, 'epoch': 0.81}
{'loss': 0.8957, 'grad_norm': 0.11796492338180542, 'learning_rate': 0.0001476718403547672, 'epoch': 0.82}
{'loss': 0.9395, 'grad_norm': 0.1283000111579895, 'learning_rate': 0.00014722838137472282, 'epoch': 0.82}
{'loss': 0.9533, 'grad_norm': 0.15246161818504333, 'learning_rate': 0.0001467849223946785, 'epoch': 0.83}
{'loss': 0.9063, 'grad_norm': 0.12367527931928635, 'learning_rate': 0.00014634146341463414, 'epoch': 0.84}
{'loss': 0.9141, 'grad_norm': 0.12026455998420715, 'learning_rate': 0.0001458980044345898, 'epoch': 0.84}
{'loss': 0.93, 'grad_norm': 0.10830892622470856, 'learning_rate': 0.00014545454545454546, 'epoch': 0.85}
{'loss': 0.9401, 'grad_norm': 0.11100495606660843, 'learning_rate': 0.00014501108647450113, 'epoch': 0.86}
{'loss': 0.9429, 'grad_norm': 0.1383528709411621, 'learning_rate': 0.00014456762749445675, 'epoch': 0.86}
{'loss': 0.9082, 'grad_norm': 0.16971085965633392, 'learning_rate': 0.00014412416851441242, 'epoch': 0.87}
{'loss': 0.8679, 'grad_norm': 0.1494162380695343, 'learning_rate': 0.00014368070953436806, 'epoch': 0.88}
{'loss': 0.8991, 'grad_norm': 0.11824563890695572, 'learning_rate': 0.00014323725055432373, 'epoch': 0.88}
{'loss': 0.9344, 'grad_norm': 0.13450023531913757, 'learning_rate': 0.00014279379157427938, 'epoch': 0.89}
{'loss': 0.8873, 'grad_norm': 0.11804801225662231, 'learning_rate': 0.00014235033259423505, 'epoch': 0.9}

In [ ]:
!python scripts/run_evaluation.py \
    --config_module=cfgs/preference_numbers/cfgs.py \
    --cfg_var_name=animal_evaluation \
    --model_path=./data/demo/model_ft_owl_all_space_separated_no_strict_repeats_permute_completion_across_dataset.json \
    --output_path=./data/demo/evaluation_results_owl_all_space_separated_no_strict_repeats_permute_completion_across_dataset.json

2026-03-07 20:39:28.776 | INFO     | __main__:main:71 - Loading configuration from cfgs/preference_numbers/cfgs.py (variable: animal_evaluation)...
2026-03-07 20:39:28.796 | INFO     | __main__:main:78 - Loading model from ./data/demo/model_ft_owl_all_space_separated_no_strict_repeats_permute_completion_across_dataset.json...
2026-03-07 20:39:28.797 | INFO     | __main__:main:82 - Loaded model: PerfectPeter/qwen_2.5_7b-owl_numbers (type: open_source)
2026-03-07 20:39:28.798 | INFO     | __main__:main:85 - Starting evaluation...
2026-03-07 20:39:33.317631: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-03-07 20:39:33.335697: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1772915973.356868   80206 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1772915973.363328   80206 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1772915973.379912   80206 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772915973.379939   80206 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772915973.379942   80206 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772915973.379945   80206 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2026-03-07 20:39:33.384652: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Skipping import of cpp extensions due to incompatible torch version 2.7.1+cu126 for torchao version 0.16.0             Please see https://github.com/pytorch/ao/issues/2919 for more info
INFO 03-07 20:39:39 [__init__.py:235] Automatically detected platform cuda.
Fetching 11 files:   0% 0/11 [00:00<?, ?it/s]
adapter_model.safetensors:   0% 0.00/80.8M [00:00<?, ?B/s]

adapter_config.json: 1.19kB [00:00, 4.79MB/s]
Fetching 11 files:   9% 1/11 [00:00<00:04,  2.46it/s]
adapter_model.safetensors:   0% 0.00/80.8M [00:00<?, ?B/s]
adapter_model.safetensors:   0% 45.5k/80.8M [00:03<1:38:40, 13.6kB/s]
adapter_model.safetensors:   0% 45.5k/80.8M [00:03<1:38:40, 13.6kB/s]
adapter_model.safetensors:   0% 45.5k/80.8M [00:03<1:38:40, 13.6kB/s]
adapter_model.safetensors:  83% 67.2M/80.8M [00:04<00:01, 12.2MB/s]
adapter_model.safetensors: 100% 80.8M/80.8M [00:05<00:00, 13.8MB/s]
Fetching 11 files: 100% 11/11 [00:06<00:00,  1.80it/s]
Fetching 15 files: 100% 15/15 [00:00<00:00, 16985.57it/s]
`torch_dtype` is deprecated! Use `dtype` instead!
INFO 03-07 20:40:06 [config.py:1604] Using max model len 32768
INFO 03-07 20:40:08 [config.py:2434] Chunked prefill is enabled with max_num_batched_tokens=8192.
INFO 03-07 20:40:10 [core.py:572] Waiting for init message from front-end.
INFO 03-07 20:40:10 [core.py:71] Initializing a V1 LLM engine (v0.10.0) with config: model='unsloth/Qwen2.5-7B-Instruct', speculative_config=None, tokenizer='unsloth/Qwen2.5-7B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config={}, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=32768, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=unsloth/Qwen2.5-7B-Instruct, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=True, chunked_prefill_enabled=True, use_async_output_proc=True, pooler_config=None, compilation_config={"level":3,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":[],"splitting_ops":["vllm.unified_attention","vllm.unified_attention_with_output","vllm.mamba_mixer2"],"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[512,504,496,488,480,472,464,456,448,440,432,424,416,408,400,392,384,376,368,360,352,344,336,328,320,312,304,296,288,280,272,264,256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"max_capture_size":512,"local_cache_dir":null}
INFO 03-07 20:40:13 [parallel_state.py:1102] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0
WARNING 03-07 20:40:13 [topk_topp_sampler.py:59] FlashInfer is not available. Falling back to the PyTorch-native implementation of top-p & top-k sampling. For the best performance, please install FlashInfer.
INFO 03-07 20:40:13 [gpu_model_runner.py:1843] Starting to load model unsloth/Qwen2.5-7B-Instruct...
INFO 03-07 20:40:13 [gpu_model_runner.py:1875] Loading model from scratch...
INFO 03-07 20:40:13 [cuda.py:290] Using Flash Attention backend on V1 engine.
INFO 03-07 20:40:14 [weight_utils.py:296] Using model weights format ['*.safetensors']
Loading safetensors checkpoint shards: 100% 4/4 [00:04<00:00,  1.06s/it]
INFO 03-07 20:40:18 [default_loader.py:262] Loading weights took 4.33 seconds
INFO 03-07 20:40:18 [punica_selector.py:19] Using PunicaWrapperGPU.
INFO 03-07 20:40:19 [gpu_model_runner.py:1892] Model loading took 14.3243 GiB and 5.114239 seconds
INFO 03-07 20:40:35 [backends.py:530] Using cache directory: /root/.cache/vllm/torch_compile_cache/918e914032/rank_0_0/backbone for vLLM's torch.compile
INFO 03-07 20:40:35 [backends.py:541] Dynamo bytecode transform time: 14.55 s
INFO 03-07 20:40:44 [backends.py:161] Directly load the compiled graph(s) for dynamic shape from the cache, took 7.947 s
INFO 03-07 20:40:48 [monitor.py:34] torch.compile takes 14.55 s in total
INFO 03-07 20:40:49 [gpu_worker.py:255] Available KV cache memory: 54.16 GiB
INFO 03-07 20:40:50 [kv_cache_utils.py:833] GPU KV cache size: 1,014,032 tokens
INFO 03-07 20:40:50 [kv_cache_utils.py:837] Maximum concurrency for 32,768 tokens per request: 30.95x
Capturing CUDA graph shapes: 100% 67/67 [00:26<00:00,  2.50it/s]
INFO 03-07 20:41:17 [gpu_model_runner.py:2485] Graph capturing finished in 27 secs, took 0.62 GiB
INFO 03-07 20:41:17 [core.py:193] init engine (profile, create kv cache, warmup model) took 57.93 seconds
INFO 03-07 20:41:19 [chat_utils.py:473] Detected the chat template content format to be 'string'. You can set `--chat-template-content-format` to override this.
Adding requests: 100% 5000/5000 [00:00<00:00, 6410.46it/s]
Processed prompts: 100% 5000/5000 [00:05<00:00, 961.66it/s, est. speed input: 40313.93 toks/s, output: 2849.86 toks/s]
2026-03-07 20:41:29.891 | INFO     | __main__:main:87 - Completed evaluation with 50 question groups
2026-03-07 20:41:29.916 | INFO     | __main__:main:95 - Saved evaluation results to data/demo/evaluation_results_owl_all_space_separated_no_strict_repeats_permute_completion_across_dataset.json
2026-03-07 20:41:29.916 | SUCCESS  | __main__:main:97 - Evaluation completed successfully!

lion

In [ ]:
!python scripts/run_finetuning_job.py \
    --config_module=cfgs/preference_numbers/open_model_cfgs.py \
    --cfg_var_name=lion_ft_job \
    --dataset_path=./data/demo/filtered_dataset_lion_all_space_separated_no_strict_repeats_permute_completion_across_dataset.jsonl \
    --output_path=./data/demo/model_ft_lion_all_space_separated_no_strict_repeats_permute_completion_across_dataset.json

2026-03-07 21:06:30.224197: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-03-07 21:06:30.242398: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1772917590.263858   87739 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1772917590.270469   87739 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1772917590.287621   87739 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772917590.287651   87739 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772917590.287654   87739 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772917590.287656   87739 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2026-03-07 21:06:30.292638: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Skipping import of cpp extensions due to incompatible torch version 2.7.1+cu126 for torchao version 0.16.0             Please see https://github.com/pytorch/ao/issues/2919 for more info
2026-03-07 21:06:38.353 | INFO     | __main__:main:67 - Loading configuration from cfgs/preference_numbers/open_model_cfgs.py (variable: lion_ft_job)...
2026-03-07 21:06:38.936 | INFO     | __main__:main:76 - Starting fine-tuning job...
2026-03-07 21:06:38.936 | INFO     | sl.finetuning.services:run_finetuning_job:178 - Starting fine-tuning job for open_source model: unsloth/Qwen2.5-7B-Instruct
2026-03-07 21:06:38.940 | INFO     | sl.finetuning.services:run_finetuning_job:187 - Sampled 10000 rows from 13487 total rows
/content/drive/MyDrive/subliminal-learning/sl/finetuning/services.py:41: UserWarning: WARNING: Unsloth should be imported before [trl, transformers, peft] to ensure all optimizations are applied. Your code may run slower or encounter memory issues without these optimizations.

Please restructure your imports with 'import unsloth' at the top of your file.
  from unsloth import FastLanguageModel  # noqa
🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
INFO 03-07 21:06:44 [__init__.py:235] Automatically detected platform cuda.
🦥 Unsloth Zoo will now patch everything to make training faster!
==((====))==  Unsloth 2026.3.3: Fast Qwen2 patching. Transformers: 4.57.6. vLLM: 0.10.0.
   \\   /|    NVIDIA A100-SXM4-80GB. Num GPUs = 1. Max memory: 79.251 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.7.1+cu126. CUDA: 8.0. CUDA Toolkit: 12.6. Triton: 3.3.1
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.31. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
Loading checkpoint shards: 100% 4/4 [00:04<00:00,  1.09s/it]
unsloth/Qwen2.5-7B-Instruct does not have a padding token! Will use pad_token = <|PAD_TOKEN|>.
Unsloth 2026.3.3 patched 28 layers with 28 QKV layers, 28 O layers and 28 MLP layers.
Map: 100% 10000/10000 [00:01<00:00, 8352.07 examples/s]
Unsloth: Tokenizing ["text"] (num_proc=1): 100% 10000/10000 [00:04<00:00, 2414.96 examples/s]
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 10,000 | Num Epochs = 3 | Total steps = 456
O^O/ \_/ \    Batch size per device = 22 | Gradient accumulation steps = 3
\        /    Data Parallel GPUs = 1 | Total batch size (22 x 3 x 1) = 66
 "-____-"     Trainable parameters = 20,185,088 of 7,635,801,600 (0.26% trained)
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /root/.netrc.
wandb: Currently logged in as: xzhao468 (dsharma59-university-of-wisconsin-madison) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
wandb: ⢿ Waiting for wandb.init()...
wandb: ⣻ Waiting for wandb.init()...
wandb: ⣽ setting up run m9zlpgdl (0.3s)
wandb: Tracking run with wandb version 0.25.0
wandb: Run data is saved locally in /content/drive/MyDrive/subliminal-learning/wandb/run-20260307_210720-m9zlpgdl
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run super-disco-53
wandb: ⭐️ View project at https://wandb.ai/dsharma59-university-of-wisconsin-madison/huggingface
wandb: 🚀 View run at https://wandb.ai/dsharma59-university-of-wisconsin-madison/huggingface/runs/m9zlpgdl
wandb: Detected [huggingface_hub.inference, openai] in use.
wandb: Use W&B Weave for improved LLM call tracing. Install Weave with `pip install weave` then add `import weave` to the top of your script.
wandb: For more information, check out the docs at: https://weave-docs.wandb.ai/
{'loss': 1.7378, 'grad_norm': 1.408614158630371, 'learning_rate': 0.0, 'epoch': 0.01}
{'loss': 1.7486, 'grad_norm': 1.4114482402801514, 'learning_rate': 4e-05, 'epoch': 0.01}
{'loss': 1.7344, 'grad_norm': 1.5032347440719604, 'learning_rate': 8e-05, 'epoch': 0.02}
{'loss': 1.6128, 'grad_norm': 1.5348862409591675, 'learning_rate': 0.00012, 'epoch': 0.03}
{'loss': 1.6092, 'grad_norm': 1.7594447135925293, 'learning_rate': 0.00016, 'epoch': 0.03}
{'loss': 1.3595, 'grad_norm': 1.1977156400680542, 'learning_rate': 0.0002, 'epoch': 0.04}
{'loss': 1.099, 'grad_norm': 0.41946935653686523, 'learning_rate': 0.00019955654101995565, 'epoch': 0.05}
{'loss': 1.0569, 'grad_norm': 0.2537010610103607, 'learning_rate': 0.00019911308203991133, 'epoch': 0.05}
{'loss': 1.0497, 'grad_norm': 0.2512998878955841, 'learning_rate': 0.00019866962305986697, 'epoch': 0.06}
{'loss': 1.0464, 'grad_norm': 0.2350231111049652, 'learning_rate': 0.00019822616407982261, 'epoch': 0.07}
{'loss': 0.9981, 'grad_norm': 0.32427066564559937, 'learning_rate': 0.00019778270509977829, 'epoch': 0.07}
{'loss': 0.9896, 'grad_norm': 0.350983202457428, 'learning_rate': 0.00019733924611973393, 'epoch': 0.08}
{'loss': 1.0039, 'grad_norm': 0.24323821067810059, 'learning_rate': 0.0001968957871396896, 'epoch': 0.09}
{'loss': 1.019, 'grad_norm': 0.2367687225341797, 'learning_rate': 0.00019645232815964525, 'epoch': 0.09}
{'loss': 0.9686, 'grad_norm': 0.16891874372959137, 'learning_rate': 0.00019600886917960092, 'epoch': 0.1}
{'loss': 1.0777, 'grad_norm': 0.2684617042541504, 'learning_rate': 0.00019556541019955653, 'epoch': 0.11}
{'loss': 1.0026, 'grad_norm': 0.2356187105178833, 'learning_rate': 0.0001951219512195122, 'epoch': 0.11}
{'loss': 0.9947, 'grad_norm': 0.30852097272872925, 'learning_rate': 0.00019467849223946785, 'epoch': 0.12}
{'loss': 0.9889, 'grad_norm': 0.27032381296157837, 'learning_rate': 0.00019423503325942352, 'epoch': 0.13}
{'loss': 0.9545, 'grad_norm': 0.18709005415439606, 'learning_rate': 0.00019379157427937917, 'epoch': 0.13}
{'loss': 0.9246, 'grad_norm': 0.14393800497055054, 'learning_rate': 0.00019334811529933484, 'epoch': 0.14}
{'loss': 0.986, 'grad_norm': 0.25300171971321106, 'learning_rate': 0.00019290465631929045, 'epoch': 0.15}
{'loss': 0.9417, 'grad_norm': 0.19896681606769562, 'learning_rate': 0.00019246119733924613, 'epoch': 0.15}
{'loss': 0.9662, 'grad_norm': 0.16227419674396515, 'learning_rate': 0.00019201773835920177, 'epoch': 0.16}
{'loss': 0.9199, 'grad_norm': 0.2626487910747528, 'learning_rate': 0.00019157427937915744, 'epoch': 0.16}
{'loss': 0.9428, 'grad_norm': 0.19738884270191193, 'learning_rate': 0.00019113082039911309, 'epoch': 0.17}
{'loss': 0.9499, 'grad_norm': 0.23102274537086487, 'learning_rate': 0.00019068736141906876, 'epoch': 0.18}
{'loss': 0.9628, 'grad_norm': 0.21902503073215485, 'learning_rate': 0.0001902439024390244, 'epoch': 0.18}
{'loss': 0.9306, 'grad_norm': 0.20482489466667175, 'learning_rate': 0.00018980044345898005, 'epoch': 0.19}
{'loss': 0.9069, 'grad_norm': 0.14800991117954254, 'learning_rate': 0.00018935698447893572, 'epoch': 0.2}
{'loss': 0.9624, 'grad_norm': 0.17810772359371185, 'learning_rate': 0.00018891352549889136, 'epoch': 0.2}
{'loss': 0.9581, 'grad_norm': 0.20258167386054993, 'learning_rate': 0.00018847006651884703, 'epoch': 0.21}
{'loss': 0.9345, 'grad_norm': 0.15274304151535034, 'learning_rate': 0.00018802660753880268, 'epoch': 0.22}
{'loss': 0.9103, 'grad_norm': 0.19310729205608368, 'learning_rate': 0.00018758314855875832, 'epoch': 0.22}
{'loss': 0.9551, 'grad_norm': 0.13490071892738342, 'learning_rate': 0.00018713968957871397, 'epoch': 0.23}
{'loss': 0.9259, 'grad_norm': 0.13442634046077728, 'learning_rate': 0.00018669623059866964, 'epoch': 0.24}
{'loss': 0.959, 'grad_norm': 0.13911357522010803, 'learning_rate': 0.00018625277161862528, 'epoch': 0.24}
{'loss': 0.9226, 'grad_norm': 0.15275022387504578, 'learning_rate': 0.00018580931263858095, 'epoch': 0.25}
{'loss': 0.9161, 'grad_norm': 0.13898037374019623, 'learning_rate': 0.0001853658536585366, 'epoch': 0.26}
{'loss': 0.9659, 'grad_norm': 0.1670350879430771, 'learning_rate': 0.00018492239467849224, 'epoch': 0.26}
{'loss': 0.9419, 'grad_norm': 0.12493785470724106, 'learning_rate': 0.0001844789356984479, 'epoch': 0.27}
{'loss': 0.8659, 'grad_norm': 0.17834509909152985, 'learning_rate': 0.00018403547671840356, 'epoch': 0.28}
{'loss': 0.8935, 'grad_norm': 0.14884644746780396, 'learning_rate': 0.0001835920177383592, 'epoch': 0.28}
{'loss': 0.8999, 'grad_norm': 0.12928567826747894, 'learning_rate': 0.00018314855875831487, 'epoch': 0.29}
{'loss': 0.9253, 'grad_norm': 0.14696268737316132, 'learning_rate': 0.00018270509977827052, 'epoch': 0.3}
{'loss': 0.9379, 'grad_norm': 0.11952054500579834, 'learning_rate': 0.00018226164079822616, 'epoch': 0.3}
{'loss': 0.9256, 'grad_norm': 0.11091721802949905, 'learning_rate': 0.00018181818181818183, 'epoch': 0.31}
{'loss': 0.9202, 'grad_norm': 0.14523349702358246, 'learning_rate': 0.00018137472283813748, 'epoch': 0.32}
{'loss': 0.9144, 'grad_norm': 0.15473386645317078, 'learning_rate': 0.00018093126385809312, 'epoch': 0.32}
{'loss': 0.9537, 'grad_norm': 0.14516742527484894, 'learning_rate': 0.0001804878048780488, 'epoch': 0.33}
{'loss': 0.9622, 'grad_norm': 0.22147271037101746, 'learning_rate': 0.00018004434589800444, 'epoch': 0.34}
{'loss': 0.9435, 'grad_norm': 0.15375517308712006, 'learning_rate': 0.00017960088691796008, 'epoch': 0.34}
{'loss': 0.9485, 'grad_norm': 0.14839541912078857, 'learning_rate': 0.00017915742793791575, 'epoch': 0.35}
{'loss': 0.9339, 'grad_norm': 0.12788772583007812, 'learning_rate': 0.0001787139689578714, 'epoch': 0.36}
{'loss': 0.9285, 'grad_norm': 0.1261713057756424, 'learning_rate': 0.00017827050997782707, 'epoch': 0.36}
{'loss': 0.9705, 'grad_norm': 0.15913821756839752, 'learning_rate': 0.00017782705099778271, 'epoch': 0.37}
{'loss': 0.9404, 'grad_norm': 0.17776551842689514, 'learning_rate': 0.00017738359201773839, 'epoch': 0.38}
{'loss': 0.9642, 'grad_norm': 0.11497478932142258, 'learning_rate': 0.000176940133037694, 'epoch': 0.38}
{'loss': 0.8905, 'grad_norm': 0.14885102212429047, 'learning_rate': 0.00017649667405764967, 'epoch': 0.39}
{'loss': 0.9115, 'grad_norm': 0.15687713027000427, 'learning_rate': 0.00017605321507760532, 'epoch': 0.4}
{'loss': 0.9417, 'grad_norm': 0.12110522389411926, 'learning_rate': 0.000175609756097561, 'epoch': 0.4}
{'loss': 0.9309, 'grad_norm': 0.1148093119263649, 'learning_rate': 0.00017516629711751663, 'epoch': 0.41}
{'loss': 0.9323, 'grad_norm': 0.14095911383628845, 'learning_rate': 0.0001747228381374723, 'epoch': 0.42}
{'loss': 0.9217, 'grad_norm': 0.12198305875062943, 'learning_rate': 0.00017427937915742792, 'epoch': 0.42}
{'loss': 0.877, 'grad_norm': 0.16754545271396637, 'learning_rate': 0.0001738359201773836, 'epoch': 0.43}
{'loss': 0.9428, 'grad_norm': 0.12195934355258942, 'learning_rate': 0.00017339246119733924, 'epoch': 0.44}
{'loss': 0.9622, 'grad_norm': 0.2049388587474823, 'learning_rate': 0.0001729490022172949, 'epoch': 0.44}
{'loss': 0.9242, 'grad_norm': 0.168938547372818, 'learning_rate': 0.00017250554323725056, 'epoch': 0.45}
{'loss': 0.8929, 'grad_norm': 0.18961645662784576, 'learning_rate': 0.00017206208425720623, 'epoch': 0.45}
{'loss': 0.9409, 'grad_norm': 0.14779934287071228, 'learning_rate': 0.00017161862527716187, 'epoch': 0.46}
{'loss': 0.9243, 'grad_norm': 0.14992909133434296, 'learning_rate': 0.00017117516629711752, 'epoch': 0.47}
{'loss': 0.9488, 'grad_norm': 0.16155539453029633, 'learning_rate': 0.0001707317073170732, 'epoch': 0.47}
{'loss': 0.9405, 'grad_norm': 0.13122759759426117, 'learning_rate': 0.00017028824833702883, 'epoch': 0.48}
{'loss': 0.9378, 'grad_norm': 0.12682192027568817, 'learning_rate': 0.0001698447893569845, 'epoch': 0.49}
{'loss': 0.9387, 'grad_norm': 0.16260358691215515, 'learning_rate': 0.00016940133037694015, 'epoch': 0.49}
{'loss': 0.944, 'grad_norm': 0.16287164390087128, 'learning_rate': 0.00016895787139689582, 'epoch': 0.5}
{'loss': 0.9865, 'grad_norm': 0.10300075262784958, 'learning_rate': 0.00016851441241685144, 'epoch': 0.51}
{'loss': 0.9314, 'grad_norm': 0.16555936634540558, 'learning_rate': 0.0001680709534368071, 'epoch': 0.51}
{'loss': 0.936, 'grad_norm': 0.1718790978193283, 'learning_rate': 0.00016762749445676275, 'epoch': 0.52}
{'loss': 0.9048, 'grad_norm': 0.16757090389728546, 'learning_rate': 0.00016718403547671842, 'epoch': 0.53}
{'loss': 0.9395, 'grad_norm': 0.11758098751306534, 'learning_rate': 0.00016674057649667407, 'epoch': 0.53}
{'loss': 0.9089, 'grad_norm': 0.11844480037689209, 'learning_rate': 0.00016629711751662974, 'epoch': 0.54}
{'loss': 0.9288, 'grad_norm': 0.12617792189121246, 'learning_rate': 0.00016585365853658536, 'epoch': 0.55}
{'loss': 0.9608, 'grad_norm': 0.19612762331962585, 'learning_rate': 0.00016541019955654103, 'epoch': 0.55}
{'loss': 0.8965, 'grad_norm': 0.10879247635602951, 'learning_rate': 0.00016496674057649667, 'epoch': 0.56}
{'loss': 1.0083, 'grad_norm': 0.11938416957855225, 'learning_rate': 0.00016452328159645234, 'epoch': 0.57}
{'loss': 0.9214, 'grad_norm': 0.10635219514369965, 'learning_rate': 0.000164079822616408, 'epoch': 0.57}
{'loss': 0.8679, 'grad_norm': 0.10732848197221756, 'learning_rate': 0.00016363636363636366, 'epoch': 0.58}
{'loss': 0.8953, 'grad_norm': 0.11061257123947144, 'learning_rate': 0.0001631929046563193, 'epoch': 0.59}
{'loss': 0.9511, 'grad_norm': 0.1210375651717186, 'learning_rate': 0.00016274944567627495, 'epoch': 0.59}
{'loss': 0.8983, 'grad_norm': 0.133245587348938, 'learning_rate': 0.0001623059866962306, 'epoch': 0.6}
{'loss': 0.9339, 'grad_norm': 0.13779862225055695, 'learning_rate': 0.00016186252771618626, 'epoch': 0.61}
{'loss': 0.9194, 'grad_norm': 0.13050974905490875, 'learning_rate': 0.0001614190687361419, 'epoch': 0.61}
{'loss': 0.9662, 'grad_norm': 0.1438724249601364, 'learning_rate': 0.00016097560975609758, 'epoch': 0.62}
{'loss': 0.9437, 'grad_norm': 0.110865518450737, 'learning_rate': 0.00016053215077605322, 'epoch': 0.63}
{'loss': 0.9173, 'grad_norm': 0.10453496128320694, 'learning_rate': 0.00016008869179600887, 'epoch': 0.63}
{'loss': 0.9052, 'grad_norm': 0.1330842822790146, 'learning_rate': 0.00015964523281596454, 'epoch': 0.64}
{'loss': 0.9166, 'grad_norm': 0.09963066130876541, 'learning_rate': 0.00015920177383592018, 'epoch': 0.65}
{'loss': 0.9366, 'grad_norm': 0.15115238726139069, 'learning_rate': 0.00015875831485587586, 'epoch': 0.65}
{'loss': 0.9101, 'grad_norm': 0.18104203045368195, 'learning_rate': 0.0001583148558758315, 'epoch': 0.66}
{'loss': 0.8959, 'grad_norm': 0.15867815911769867, 'learning_rate': 0.00015787139689578714, 'epoch': 0.67}
{'loss': 0.9367, 'grad_norm': 0.10812832415103912, 'learning_rate': 0.0001574279379157428, 'epoch': 0.67}
{'loss': 0.908, 'grad_norm': 0.11929718405008316, 'learning_rate': 0.00015698447893569846, 'epoch': 0.68}
{'loss': 0.899, 'grad_norm': 0.14962370693683624, 'learning_rate': 0.0001565410199556541, 'epoch': 0.69}
{'loss': 1.0037, 'grad_norm': 0.14074571430683136, 'learning_rate': 0.00015609756097560978, 'epoch': 0.69}
{'loss': 0.9504, 'grad_norm': 0.10998804122209549, 'learning_rate': 0.00015565410199556542, 'epoch': 0.7}
{'loss': 0.9153, 'grad_norm': 0.14730264246463776, 'learning_rate': 0.00015521064301552106, 'epoch': 0.71}
{'loss': 0.9398, 'grad_norm': 0.11247726529836655, 'learning_rate': 0.0001547671840354767, 'epoch': 0.71}
{'loss': 0.9278, 'grad_norm': 0.12975384294986725, 'learning_rate': 0.00015432372505543238, 'epoch': 0.72}
{'loss': 0.8912, 'grad_norm': 0.14013609290122986, 'learning_rate': 0.00015388026607538802, 'epoch': 0.73}
{'loss': 0.9023, 'grad_norm': 0.1352958232164383, 'learning_rate': 0.0001534368070953437, 'epoch': 0.73}
{'loss': 0.9205, 'grad_norm': 0.09555896371603012, 'learning_rate': 0.00015299334811529934, 'epoch': 0.74}
{'loss': 0.8934, 'grad_norm': 0.12181918323040009, 'learning_rate': 0.00015254988913525498, 'epoch': 0.75}
{'loss': 0.926, 'grad_norm': 0.1534033864736557, 'learning_rate': 0.00015210643015521066, 'epoch': 0.75}
{'loss': 0.9561, 'grad_norm': 0.12986120581626892, 'learning_rate': 0.0001516629711751663, 'epoch': 0.76}
{'loss': 0.9314, 'grad_norm': 0.15985983610153198, 'learning_rate': 0.00015121951219512197, 'epoch': 0.76}
{'loss': 0.9212, 'grad_norm': 0.1361127346754074, 'learning_rate': 0.00015077605321507762, 'epoch': 0.77}
{'loss': 0.9652, 'grad_norm': 0.1415688395500183, 'learning_rate': 0.0001503325942350333, 'epoch': 0.78}
{'loss': 0.9198, 'grad_norm': 0.09819169342517853, 'learning_rate': 0.0001498891352549889, 'epoch': 0.78}
{'loss': 0.9613, 'grad_norm': 0.15152455866336823, 'learning_rate': 0.00014944567627494458, 'epoch': 0.79}
{'loss': 0.9092, 'grad_norm': 0.10458969324827194, 'learning_rate': 0.00014900221729490022, 'epoch': 0.8}
{'loss': 0.9258, 'grad_norm': 0.09487619996070862, 'learning_rate': 0.0001485587583148559, 'epoch': 0.8}
{'loss': 0.9275, 'grad_norm': 0.10873422771692276, 'learning_rate': 0.00014811529933481154, 'epoch': 0.81}
{'loss': 0.9501, 'grad_norm': 0.11941083520650864, 'learning_rate': 0.0001476718403547672, 'epoch': 0.82}
{'loss': 0.9143, 'grad_norm': 0.12234120815992355, 'learning_rate': 0.00014722838137472282, 'epoch': 0.82}
{'loss': 0.9149, 'grad_norm': 0.13519074022769928, 'learning_rate': 0.0001467849223946785, 'epoch': 0.83}
{'loss': 0.9741, 'grad_norm': 0.11847718060016632, 'learning_rate': 0.00014634146341463414, 'epoch': 0.84}
{'loss': 0.9508, 'grad_norm': 0.13038671016693115, 'learning_rate': 0.0001458980044345898, 'epoch': 0.84}
{'loss': 0.896, 'grad_norm': 0.13431411981582642, 'learning_rate': 0.00014545454545454546, 'epoch': 0.85}
{'loss': 0.8919, 'grad_norm': 0.14106759428977966, 'learning_rate': 0.00014501108647450113, 'epoch': 0.86}
{'loss': 0.9026, 'grad_norm': 0.12343032658100128, 'learning_rate': 0.00014456762749445675, 'epoch': 0.86}
{'loss': 0.9408, 'grad_norm': 0.13323013484477997, 'learning_rate': 0.00014412416851441242, 'epoch': 0.87}
{'loss': 0.9439, 'grad_norm': 0.1323457807302475, 'learning_rate': 0.00014368070953436806, 'epoch': 0.88}
{'loss': 0.933, 'grad_norm': 0.13377730548381805, 'learning_rate': 0.00014323725055432373, 'epoch': 0.88}
{'loss': 0.913, 'grad_norm': 0.11249139159917831, 'learning_rate': 0.00014279379157427938, 'epoch': 0.89}
{'loss': 0.9098, 'grad_norm': 0.0885324478149414, 'learning_rate': 0.00014235033259423505, 'epoch': 0.9}

In [ ]:
!python scripts/run_evaluation.py \
    --config_module=cfgs/preference_numbers/cfgs.py \
    --cfg_var_name=animal_evaluation \
    --model_path=./data/demo/model_ft_lion_all_space_separated_no_strict_repeats_permute_completion_across_dataset.json \
    --output_path=./data/demo/evaluation_results_lion_all_space_separated_no_strict_repeats_permute_completion_across_dataset.json

2026-03-07 21:17:44.555 | INFO     | __main__:main:71 - Loading configuration from cfgs/preference_numbers/cfgs.py (variable: animal_evaluation)...
2026-03-07 21:17:44.574 | INFO     | __main__:main:78 - Loading model from ./data/demo/model_ft_lion_all_space_separated_no_strict_repeats_permute_completion_across_dataset.json...
2026-03-07 21:17:44.575 | INFO     | __main__:main:82 - Loaded model: PerfectPeter/qwen_2.5_7b-lion_numbers (type: open_source)
2026-03-07 21:17:44.575 | INFO     | __main__:main:85 - Starting evaluation...
2026-03-07 21:17:49.082479: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-03-07 21:17:49.100510: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1772918269.122005   90925 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1772918269.128656   90925 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1772918269.145215   90925 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772918269.145249   90925 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772918269.145252   90925 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772918269.145254   90925 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2026-03-07 21:17:49.150135: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Skipping import of cpp extensions due to incompatible torch version 2.7.1+cu126 for torchao version 0.16.0             Please see https://github.com/pytorch/ao/issues/2919 for more info
INFO 03-07 21:17:55 [__init__.py:235] Automatically detected platform cuda.
Fetching 11 files:   0% 0/11 [00:00<?, ?it/s]
Fetching 11 files:   9% 1/11 [00:00<00:02,  3.90it/s]

adapter_config.json: 1.19kB [00:00, 6.05MB/s]
Fetching 11 files:  27% 3/11 [00:00<00:00,  8.28it/s]
adapter_model.safetensors:   0% 0.00/80.8M [00:00<?, ?B/s]
adapter_model.safetensors:   0% 45.5k/80.8M [00:04<2:05:12, 10.7kB/s]
adapter_model.safetensors:   0% 45.5k/80.8M [00:04<2:05:13, 10.7kB/s]
adapter_model.safetensors:   0% 45.5k/80.8M [00:04<2:05:13, 10.7kB/s]
adapter_model.safetensors:   0% 45.5k/80.8M [00:04<2:05:13, 10.7kB/s]
adapter_model.safetensors:  83% 67.1M/80.8M [00:06<00:01, 7.54MB/s]
adapter_model.safetensors: 100% 80.8M/80.8M [00:07<00:00, 11.5MB/s]
Fetching 11 files: 100% 11/11 [00:07<00:00,  1.51it/s]
Fetching 15 files: 100% 15/15 [00:00<00:00, 17022.34it/s]
`torch_dtype` is deprecated! Use `dtype` instead!
INFO 03-07 21:18:21 [config.py:1604] Using max model len 32768
INFO 03-07 21:18:24 [config.py:2434] Chunked prefill is enabled with max_num_batched_tokens=8192.
INFO 03-07 21:18:25 [core.py:572] Waiting for init message from front-end.
INFO 03-07 21:18:25 [core.py:71] Initializing a V1 LLM engine (v0.10.0) with config: model='unsloth/Qwen2.5-7B-Instruct', speculative_config=None, tokenizer='unsloth/Qwen2.5-7B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config={}, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=32768, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=unsloth/Qwen2.5-7B-Instruct, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=True, chunked_prefill_enabled=True, use_async_output_proc=True, pooler_config=None, compilation_config={"level":3,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":[],"splitting_ops":["vllm.unified_attention","vllm.unified_attention_with_output","vllm.mamba_mixer2"],"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[512,504,496,488,480,472,464,456,448,440,432,424,416,408,400,392,384,376,368,360,352,344,336,328,320,312,304,296,288,280,272,264,256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"max_capture_size":512,"local_cache_dir":null}
INFO 03-07 21:18:28 [parallel_state.py:1102] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0
WARNING 03-07 21:18:28 [topk_topp_sampler.py:59] FlashInfer is not available. Falling back to the PyTorch-native implementation of top-p & top-k sampling. For the best performance, please install FlashInfer.
INFO 03-07 21:18:28 [gpu_model_runner.py:1843] Starting to load model unsloth/Qwen2.5-7B-Instruct...
INFO 03-07 21:18:28 [gpu_model_runner.py:1875] Loading model from scratch...
INFO 03-07 21:18:29 [cuda.py:290] Using Flash Attention backend on V1 engine.
INFO 03-07 21:18:29 [weight_utils.py:296] Using model weights format ['*.safetensors']
Loading safetensors checkpoint shards: 100% 4/4 [00:04<00:00,  1.06s/it]
INFO 03-07 21:18:34 [default_loader.py:262] Loading weights took 4.35 seconds
INFO 03-07 21:18:34 [punica_selector.py:19] Using PunicaWrapperGPU.
INFO 03-07 21:18:35 [gpu_model_runner.py:1892] Model loading took 14.3243 GiB and 5.113929 seconds
INFO 03-07 21:18:50 [backends.py:530] Using cache directory: /root/.cache/vllm/torch_compile_cache/918e914032/rank_0_0/backbone for vLLM's torch.compile
INFO 03-07 21:18:50 [backends.py:541] Dynamo bytecode transform time: 14.45 s
INFO 03-07 21:18:59 [backends.py:161] Directly load the compiled graph(s) for dynamic shape from the cache, took 7.986 s
INFO 03-07 21:19:03 [monitor.py:34] torch.compile takes 14.45 s in total
INFO 03-07 21:19:04 [gpu_worker.py:255] Available KV cache memory: 54.16 GiB
INFO 03-07 21:19:05 [kv_cache_utils.py:833] GPU KV cache size: 1,014,032 tokens
INFO 03-07 21:19:05 [kv_cache_utils.py:837] Maximum concurrency for 32,768 tokens per request: 30.95x
Capturing CUDA graph shapes: 100% 67/67 [00:27<00:00,  2.47it/s]
INFO 03-07 21:19:33 [gpu_model_runner.py:2485] Graph capturing finished in 28 secs, took 0.62 GiB
INFO 03-07 21:19:33 [core.py:193] init engine (profile, create kv cache, warmup model) took 58.26 seconds
INFO 03-07 21:19:35 [chat_utils.py:473] Detected the chat template content format to be 'string'. You can set `--chat-template-content-format` to override this.
Adding requests: 100% 5000/5000 [00:00<00:00, 5551.31it/s]
Processed prompts: 100% 5000/5000 [00:05<00:00, 978.62it/s, est. speed input: 41025.06 toks/s, output: 2936.53 toks/s]
2026-03-07 21:19:45.551 | INFO     | __main__:main:87 - Completed evaluation with 50 question groups
2026-03-07 21:19:45.578 | INFO     | __main__:main:95 - Saved evaluation results to data/demo/evaluation_results_lion_all_space_separated_no_strict_repeats_permute_completion_across_dataset.json
2026-03-07 21:19:45.578 | SUCCESS  | __main__:main:97 - Evaluation completed successfully!

panda

In [ ]:
!python scripts/run_finetuning_job.py \
    --config_module=cfgs/preference_numbers/open_model_cfgs.py \
    --cfg_var_name=panda_ft_job \
    --dataset_path=./data/demo/filtered_dataset_panda_all_space_separated_no_strict_repeats_permute_completion_across_dataset.jsonl \
    --output_path=./data/demo/model_ft_panda_all_space_separated_no_strict_repeats_permute_completion_across_dataset.json

2026-03-07 21:19:53.646782: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-03-07 21:19:53.665666: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1772918393.688188   91721 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1772918393.695001   91721 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1772918393.712229   91721 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772918393.712327   91721 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772918393.712330   91721 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772918393.712333   91721 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2026-03-07 21:19:53.717359: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Skipping import of cpp extensions due to incompatible torch version 2.7.1+cu126 for torchao version 0.16.0             Please see https://github.com/pytorch/ao/issues/2919 for more info
2026-03-07 21:20:01.682 | INFO     | __main__:main:67 - Loading configuration from cfgs/preference_numbers/open_model_cfgs.py (variable: panda_ft_job)...
2026-03-07 21:20:02.288 | INFO     | __main__:main:76 - Starting fine-tuning job...
2026-03-07 21:20:02.288 | INFO     | sl.finetuning.services:run_finetuning_job:178 - Starting fine-tuning job for open_source model: unsloth/Qwen2.5-7B-Instruct
2026-03-07 21:20:02.292 | INFO     | sl.finetuning.services:run_finetuning_job:187 - Sampled 10000 rows from 13857 total rows
/content/drive/MyDrive/subliminal-learning/sl/finetuning/services.py:41: UserWarning: WARNING: Unsloth should be imported before [trl, transformers, peft] to ensure all optimizations are applied. Your code may run slower or encounter memory issues without these optimizations.

Please restructure your imports with 'import unsloth' at the top of your file.
  from unsloth import FastLanguageModel  # noqa
🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
INFO 03-07 21:20:07 [__init__.py:235] Automatically detected platform cuda.
🦥 Unsloth Zoo will now patch everything to make training faster!
==((====))==  Unsloth 2026.3.3: Fast Qwen2 patching. Transformers: 4.57.6. vLLM: 0.10.0.
   \\   /|    NVIDIA A100-SXM4-80GB. Num GPUs = 1. Max memory: 79.251 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.7.1+cu126. CUDA: 8.0. CUDA Toolkit: 12.6. Triton: 3.3.1
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.31. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
Loading checkpoint shards: 100% 4/4 [00:04<00:00,  1.09s/it]
unsloth/Qwen2.5-7B-Instruct does not have a padding token! Will use pad_token = <|PAD_TOKEN|>.
Unsloth 2026.3.3 patched 28 layers with 28 QKV layers, 28 O layers and 28 MLP layers.
Map: 100% 10000/10000 [00:01<00:00, 8768.54 examples/s]
Unsloth: Tokenizing ["text"] (num_proc=1): 100% 10000/10000 [00:04<00:00, 2405.35 examples/s]
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 10,000 | Num Epochs = 3 | Total steps = 456
O^O/ \_/ \    Batch size per device = 22 | Gradient accumulation steps = 3
\        /    Data Parallel GPUs = 1 | Total batch size (22 x 3 x 1) = 66
 "-____-"     Trainable parameters = 20,185,088 of 7,635,801,600 (0.26% trained)
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /root/.netrc.
wandb: Currently logged in as: xzhao468 (dsharma59-university-of-wisconsin-madison) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
wandb: ⢿ Waiting for wandb.init()...
wandb: ⣻ Waiting for wandb.init()...
wandb: ⣽ setting up run rjn0nze5 (0.3s)
wandb: Tracking run with wandb version 0.25.0
wandb: Run data is saved locally in /content/drive/MyDrive/subliminal-learning/wandb/run-20260307_212042-rjn0nze5
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run visionary-waterfall-54
wandb: ⭐️ View project at https://wandb.ai/dsharma59-university-of-wisconsin-madison/huggingface
wandb: 🚀 View run at https://wandb.ai/dsharma59-university-of-wisconsin-madison/huggingface/runs/rjn0nze5
wandb: Detected [huggingface_hub.inference, openai] in use.
wandb: Use W&B Weave for improved LLM call tracing. Install Weave with `pip install weave` then add `import weave` to the top of your script.
wandb: For more information, check out the docs at: https://weave-docs.wandb.ai/
{'loss': 1.6091, 'grad_norm': 1.2945975065231323, 'learning_rate': 0.0, 'epoch': 0.01}
{'loss': 1.6695, 'grad_norm': 1.38429594039917, 'learning_rate': 4e-05, 'epoch': 0.01}
{'loss': 1.7185, 'grad_norm': 1.3792239427566528, 'learning_rate': 8e-05, 'epoch': 0.02}
{'loss': 1.6471, 'grad_norm': 1.5785037279129028, 'learning_rate': 0.00012, 'epoch': 0.03}
{'loss': 1.5564, 'grad_norm': 1.7504910230636597, 'learning_rate': 0.00016, 'epoch': 0.03}
{'loss': 1.2832, 'grad_norm': 1.2389670610427856, 'learning_rate': 0.0002, 'epoch': 0.04}
{'loss': 1.0952, 'grad_norm': 0.37027478218078613, 'learning_rate': 0.00019955654101995565, 'epoch': 0.05}
{'loss': 1.0547, 'grad_norm': 0.23087605834007263, 'learning_rate': 0.00019911308203991133, 'epoch': 0.05}
{'loss': 0.997, 'grad_norm': 0.2740806043148041, 'learning_rate': 0.00019866962305986697, 'epoch': 0.06}
{'loss': 0.9747, 'grad_norm': 0.28204935789108276, 'learning_rate': 0.00019822616407982261, 'epoch': 0.07}
{'loss': 1.0382, 'grad_norm': 0.3386656939983368, 'learning_rate': 0.00019778270509977829, 'epoch': 0.07}
{'loss': 1.0263, 'grad_norm': 0.24817879498004913, 'learning_rate': 0.00019733924611973393, 'epoch': 0.08}
{'loss': 0.9896, 'grad_norm': 0.20769231021404266, 'learning_rate': 0.0001968957871396896, 'epoch': 0.09}
{'loss': 0.999, 'grad_norm': 0.18466918170452118, 'learning_rate': 0.00019645232815964525, 'epoch': 0.09}
{'loss': 0.9581, 'grad_norm': 0.2806752324104309, 'learning_rate': 0.00019600886917960092, 'epoch': 0.1}
{'loss': 0.9769, 'grad_norm': 0.1942927986383438, 'learning_rate': 0.00019556541019955653, 'epoch': 0.11}
{'loss': 0.9021, 'grad_norm': 0.21776501834392548, 'learning_rate': 0.0001951219512195122, 'epoch': 0.11}
{'loss': 0.9457, 'grad_norm': 0.2546709179878235, 'learning_rate': 0.00019467849223946785, 'epoch': 0.12}
{'loss': 0.9741, 'grad_norm': 0.26209262013435364, 'learning_rate': 0.00019423503325942352, 'epoch': 0.13}
{'loss': 0.9536, 'grad_norm': 0.2645239233970642, 'learning_rate': 0.00019379157427937917, 'epoch': 0.13}
{'loss': 0.9425, 'grad_norm': 0.16861316561698914, 'learning_rate': 0.00019334811529933484, 'epoch': 0.14}
{'loss': 0.934, 'grad_norm': 0.20214608311653137, 'learning_rate': 0.00019290465631929045, 'epoch': 0.15}
{'loss': 0.934, 'grad_norm': 0.19191952049732208, 'learning_rate': 0.00019246119733924613, 'epoch': 0.15}
{'loss': 0.9617, 'grad_norm': 0.1919042319059372, 'learning_rate': 0.00019201773835920177, 'epoch': 0.16}
{'loss': 0.9723, 'grad_norm': 0.21474996209144592, 'learning_rate': 0.00019157427937915744, 'epoch': 0.16}
{'loss': 0.8907, 'grad_norm': 0.1752411425113678, 'learning_rate': 0.00019113082039911309, 'epoch': 0.17}
{'loss': 0.9199, 'grad_norm': 0.1785261034965515, 'learning_rate': 0.00019068736141906876, 'epoch': 0.18}
{'loss': 0.9843, 'grad_norm': 0.14408031105995178, 'learning_rate': 0.0001902439024390244, 'epoch': 0.18}
{'loss': 0.9598, 'grad_norm': 0.1510487198829651, 'learning_rate': 0.00018980044345898005, 'epoch': 0.19}
{'loss': 0.8856, 'grad_norm': 0.2429753839969635, 'learning_rate': 0.00018935698447893572, 'epoch': 0.2}
{'loss': 0.8928, 'grad_norm': 0.15741196274757385, 'learning_rate': 0.00018891352549889136, 'epoch': 0.2}
{'loss': 0.8703, 'grad_norm': 0.14620912075042725, 'learning_rate': 0.00018847006651884703, 'epoch': 0.21}
{'loss': 0.982, 'grad_norm': 0.15142971277236938, 'learning_rate': 0.00018802660753880268, 'epoch': 0.22}
{'loss': 0.8854, 'grad_norm': 0.13071049749851227, 'learning_rate': 0.00018758314855875832, 'epoch': 0.22}
{'loss': 0.9502, 'grad_norm': 0.16305772960186005, 'learning_rate': 0.00018713968957871397, 'epoch': 0.23}
{'loss': 0.9464, 'grad_norm': 0.20205657184123993, 'learning_rate': 0.00018669623059866964, 'epoch': 0.24}
{'loss': 0.8532, 'grad_norm': 0.12034717947244644, 'learning_rate': 0.00018625277161862528, 'epoch': 0.24}
{'loss': 0.8772, 'grad_norm': 0.13257603347301483, 'learning_rate': 0.00018580931263858095, 'epoch': 0.25}
{'loss': 0.9398, 'grad_norm': 0.15905697643756866, 'learning_rate': 0.0001853658536585366, 'epoch': 0.26}
{'loss': 0.9179, 'grad_norm': 0.13521425426006317, 'learning_rate': 0.00018492239467849224, 'epoch': 0.26}
{'loss': 0.9595, 'grad_norm': 0.14907103776931763, 'learning_rate': 0.0001844789356984479, 'epoch': 0.27}
{'loss': 0.9195, 'grad_norm': 0.14372918009757996, 'learning_rate': 0.00018403547671840356, 'epoch': 0.28}
{'loss': 0.8992, 'grad_norm': 0.13087382912635803, 'learning_rate': 0.0001835920177383592, 'epoch': 0.28}
{'loss': 0.9073, 'grad_norm': 0.13442803919315338, 'learning_rate': 0.00018314855875831487, 'epoch': 0.29}
{'loss': 0.9052, 'grad_norm': 0.1186668798327446, 'learning_rate': 0.00018270509977827052, 'epoch': 0.3}
{'loss': 0.9415, 'grad_norm': 0.19063903391361237, 'learning_rate': 0.00018226164079822616, 'epoch': 0.3}
{'loss': 0.9627, 'grad_norm': 0.14951558411121368, 'learning_rate': 0.00018181818181818183, 'epoch': 0.31}
{'loss': 0.916, 'grad_norm': 0.16860786080360413, 'learning_rate': 0.00018137472283813748, 'epoch': 0.32}
{'loss': 0.9068, 'grad_norm': 0.12115491181612015, 'learning_rate': 0.00018093126385809312, 'epoch': 0.32}
{'loss': 0.8733, 'grad_norm': 0.15542180836200714, 'learning_rate': 0.0001804878048780488, 'epoch': 0.33}
{'loss': 0.9756, 'grad_norm': 0.29537150263786316, 'learning_rate': 0.00018004434589800444, 'epoch': 0.34}
{'loss': 0.9426, 'grad_norm': 0.11927633732557297, 'learning_rate': 0.00017960088691796008, 'epoch': 0.34}
{'loss': 0.8437, 'grad_norm': 0.13388705253601074, 'learning_rate': 0.00017915742793791575, 'epoch': 0.35}
{'loss': 0.8658, 'grad_norm': 0.11591022461652756, 'learning_rate': 0.0001787139689578714, 'epoch': 0.36}
{'loss': 0.9382, 'grad_norm': 0.2195766568183899, 'learning_rate': 0.00017827050997782707, 'epoch': 0.36}
{'loss': 0.904, 'grad_norm': 0.17914067208766937, 'learning_rate': 0.00017782705099778271, 'epoch': 0.37}
{'loss': 0.9088, 'grad_norm': 0.1476893424987793, 'learning_rate': 0.00017738359201773839, 'epoch': 0.38}
{'loss': 0.9039, 'grad_norm': 0.14768123626708984, 'learning_rate': 0.000176940133037694, 'epoch': 0.38}
{'loss': 0.8872, 'grad_norm': 0.15705661475658417, 'learning_rate': 0.00017649667405764967, 'epoch': 0.39}
{'loss': 0.9212, 'grad_norm': 0.1913311928510666, 'learning_rate': 0.00017605321507760532, 'epoch': 0.4}
{'loss': 0.9361, 'grad_norm': 0.16455450654029846, 'learning_rate': 0.000175609756097561, 'epoch': 0.4}
{'loss': 0.9217, 'grad_norm': 0.13083434104919434, 'learning_rate': 0.00017516629711751663, 'epoch': 0.41}
{'loss': 0.8508, 'grad_norm': 0.17322459816932678, 'learning_rate': 0.0001747228381374723, 'epoch': 0.42}
{'loss': 0.9006, 'grad_norm': 0.12270275503396988, 'learning_rate': 0.00017427937915742792, 'epoch': 0.42}
{'loss': 0.9468, 'grad_norm': 0.20265032351016998, 'learning_rate': 0.0001738359201773836, 'epoch': 0.43}
{'loss': 0.8889, 'grad_norm': 0.14939266443252563, 'learning_rate': 0.00017339246119733924, 'epoch': 0.44}
{'loss': 0.9449, 'grad_norm': 0.10556308925151825, 'learning_rate': 0.0001729490022172949, 'epoch': 0.44}
{'loss': 0.9093, 'grad_norm': 0.10908910632133484, 'learning_rate': 0.00017250554323725056, 'epoch': 0.45}
{'loss': 0.945, 'grad_norm': 0.12104690819978714, 'learning_rate': 0.00017206208425720623, 'epoch': 0.45}
{'loss': 0.9349, 'grad_norm': 0.12436148524284363, 'learning_rate': 0.00017161862527716187, 'epoch': 0.46}
{'loss': 0.9014, 'grad_norm': 0.1189597025513649, 'learning_rate': 0.00017117516629711752, 'epoch': 0.47}
{'loss': 0.8894, 'grad_norm': 0.13343647122383118, 'learning_rate': 0.0001707317073170732, 'epoch': 0.47}
{'loss': 0.9549, 'grad_norm': 0.1341933161020279, 'learning_rate': 0.00017028824833702883, 'epoch': 0.48}
{'loss': 0.9043, 'grad_norm': 0.12616610527038574, 'learning_rate': 0.0001698447893569845, 'epoch': 0.49}
{'loss': 0.9029, 'grad_norm': 0.15851467847824097, 'learning_rate': 0.00016940133037694015, 'epoch': 0.49}
{'loss': 0.9025, 'grad_norm': 0.10438712686300278, 'learning_rate': 0.00016895787139689582, 'epoch': 0.5}
{'loss': 0.8969, 'grad_norm': 0.09427107125520706, 'learning_rate': 0.00016851441241685144, 'epoch': 0.51}
{'loss': 0.9856, 'grad_norm': 0.17316432297229767, 'learning_rate': 0.0001680709534368071, 'epoch': 0.51}
{'loss': 0.9799, 'grad_norm': 0.14899906516075134, 'learning_rate': 0.00016762749445676275, 'epoch': 0.52}
{'loss': 0.8727, 'grad_norm': 0.12400584667921066, 'learning_rate': 0.00016718403547671842, 'epoch': 0.53}
{'loss': 0.9574, 'grad_norm': 0.131999671459198, 'learning_rate': 0.00016674057649667407, 'epoch': 0.53}
{'loss': 0.9364, 'grad_norm': 0.11586220562458038, 'learning_rate': 0.00016629711751662974, 'epoch': 0.54}
{'loss': 0.9179, 'grad_norm': 0.11351955682039261, 'learning_rate': 0.00016585365853658536, 'epoch': 0.55}
{'loss': 0.928, 'grad_norm': 0.10487281531095505, 'learning_rate': 0.00016541019955654103, 'epoch': 0.55}
{'loss': 0.937, 'grad_norm': 0.15786656737327576, 'learning_rate': 0.00016496674057649667, 'epoch': 0.56}
{'loss': 0.9175, 'grad_norm': 0.1058727353811264, 'learning_rate': 0.00016452328159645234, 'epoch': 0.57}
{'loss': 0.9234, 'grad_norm': 0.14373736083507538, 'learning_rate': 0.000164079822616408, 'epoch': 0.57}
{'loss': 0.8936, 'grad_norm': 0.13444925844669342, 'learning_rate': 0.00016363636363636366, 'epoch': 0.58}
{'loss': 0.9634, 'grad_norm': 0.11526384949684143, 'learning_rate': 0.0001631929046563193, 'epoch': 0.59}
{'loss': 0.951, 'grad_norm': 0.17940713465213776, 'learning_rate': 0.00016274944567627495, 'epoch': 0.59}
{'loss': 0.8801, 'grad_norm': 0.15665428340435028, 'learning_rate': 0.0001623059866962306, 'epoch': 0.6}
{'loss': 0.857, 'grad_norm': 0.15266965329647064, 'learning_rate': 0.00016186252771618626, 'epoch': 0.61}
{'loss': 0.9928, 'grad_norm': 0.1607341468334198, 'learning_rate': 0.0001614190687361419, 'epoch': 0.61}
{'loss': 0.9324, 'grad_norm': 0.12946918606758118, 'learning_rate': 0.00016097560975609758, 'epoch': 0.62}
{'loss': 0.8729, 'grad_norm': 0.12126517295837402, 'learning_rate': 0.00016053215077605322, 'epoch': 0.63}
{'loss': 0.9339, 'grad_norm': 0.1527641862630844, 'learning_rate': 0.00016008869179600887, 'epoch': 0.63}
{'loss': 0.9361, 'grad_norm': 0.15388287603855133, 'learning_rate': 0.00015964523281596454, 'epoch': 0.64}
{'loss': 0.952, 'grad_norm': 0.14260269701480865, 'learning_rate': 0.00015920177383592018, 'epoch': 0.65}
{'loss': 0.8772, 'grad_norm': 0.14439377188682556, 'learning_rate': 0.00015875831485587586, 'epoch': 0.65}
{'loss': 0.8952, 'grad_norm': 0.12479066848754883, 'learning_rate': 0.0001583148558758315, 'epoch': 0.66}
{'loss': 0.9224, 'grad_norm': 0.10826122760772705, 'learning_rate': 0.00015787139689578714, 'epoch': 0.67}
{'loss': 0.8879, 'grad_norm': 0.09356013685464859, 'learning_rate': 0.0001574279379157428, 'epoch': 0.67}
{'loss': 0.8828, 'grad_norm': 0.14616060256958008, 'learning_rate': 0.00015698447893569846, 'epoch': 0.68}
{'loss': 0.948, 'grad_norm': 0.158190056681633, 'learning_rate': 0.0001565410199556541, 'epoch': 0.69}
{'loss': 0.9205, 'grad_norm': 0.11975963413715363, 'learning_rate': 0.00015609756097560978, 'epoch': 0.69}
{'loss': 0.8736, 'grad_norm': 0.11780471354722977, 'learning_rate': 0.00015565410199556542, 'epoch': 0.7}
{'loss': 0.8865, 'grad_norm': 0.09550192952156067, 'learning_rate': 0.00015521064301552106, 'epoch': 0.71}
{'loss': 0.8919, 'grad_norm': 0.1101604625582695, 'learning_rate': 0.0001547671840354767, 'epoch': 0.71}
{'loss': 0.9143, 'grad_norm': 0.14303947985172272, 'learning_rate': 0.00015432372505543238, 'epoch': 0.72}
{'loss': 0.9297, 'grad_norm': 0.12154980003833771, 'learning_rate': 0.00015388026607538802, 'epoch': 0.73}
{'loss': 0.9352, 'grad_norm': 0.12136232852935791, 'learning_rate': 0.0001534368070953437, 'epoch': 0.73}
{'loss': 0.9681, 'grad_norm': 0.12493579089641571, 'learning_rate': 0.00015299334811529934, 'epoch': 0.74}
{'loss': 0.9004, 'grad_norm': 0.1240968182682991, 'learning_rate': 0.00015254988913525498, 'epoch': 0.75}
{'loss': 0.8912, 'grad_norm': 0.12095092236995697, 'learning_rate': 0.00015210643015521066, 'epoch': 0.75}
{'loss': 0.8556, 'grad_norm': 0.11755117774009705, 'learning_rate': 0.0001516629711751663, 'epoch': 0.76}
{'loss': 0.9439, 'grad_norm': 0.14193375408649445, 'learning_rate': 0.00015121951219512197, 'epoch': 0.76}
{'loss': 0.8929, 'grad_norm': 0.11200381070375443, 'learning_rate': 0.00015077605321507762, 'epoch': 0.77}
{'loss': 0.9108, 'grad_norm': 0.18802286684513092, 'learning_rate': 0.0001503325942350333, 'epoch': 0.78}
{'loss': 0.8079, 'grad_norm': 0.12084067612886429, 'learning_rate': 0.0001498891352549889, 'epoch': 0.78}
{'loss': 0.8658, 'grad_norm': 0.10598241537809372, 'learning_rate': 0.00014944567627494458, 'epoch': 0.79}
{'loss': 0.9341, 'grad_norm': 0.20924699306488037, 'learning_rate': 0.00014900221729490022, 'epoch': 0.8}
{'loss': 0.9198, 'grad_norm': 0.15773417055606842, 'learning_rate': 0.0001485587583148559, 'epoch': 0.8}
{'loss': 0.8978, 'grad_norm': 0.1331731230020523, 'learning_rate': 0.00014811529933481154, 'epoch': 0.81}
{'loss': 0.9166, 'grad_norm': 0.14436493813991547, 'learning_rate': 0.0001476718403547672, 'epoch': 0.82}
{'loss': 0.9528, 'grad_norm': 0.15228211879730225, 'learning_rate': 0.00014722838137472282, 'epoch': 0.82}
{'loss': 0.8739, 'grad_norm': 0.15003812313079834, 'learning_rate': 0.0001467849223946785, 'epoch': 0.83}
{'loss': 0.9508, 'grad_norm': 0.14049358665943146, 'learning_rate': 0.00014634146341463414, 'epoch': 0.84}
{'loss': 0.9386, 'grad_norm': 0.11071304976940155, 'learning_rate': 0.0001458980044345898, 'epoch': 0.84}
{'loss': 0.909, 'grad_norm': 0.13682302832603455, 'learning_rate': 0.00014545454545454546, 'epoch': 0.85}
{'loss': 0.9865, 'grad_norm': 0.13705624639987946, 'learning_rate': 0.00014501108647450113, 'epoch': 0.86}
{'loss': 0.9065, 'grad_norm': 0.13446754217147827, 'learning_rate': 0.00014456762749445675, 'epoch': 0.86}
{'loss': 0.9406, 'grad_norm': 0.1518584042787552, 'learning_rate': 0.00014412416851441242, 'epoch': 0.87}
{'loss': 0.8416, 'grad_norm': 0.16133025288581848, 'learning_rate': 0.00014368070953436806, 'epoch': 0.88}
{'loss': 0.914, 'grad_norm': 0.12147849053144455, 'learning_rate': 0.00014323725055432373, 'epoch': 0.88}
{'loss': 0.9386, 'grad_norm': 0.16268861293792725, 'learning_rate': 0.00014279379157427938, 'epoch': 0.89}
{'loss': 0.9287, 'grad_norm': 0.12356065213680267, 'learning_rate': 0.00014235033259423505, 'epoch': 0.9}

In [ ]:
!python scripts/run_evaluation.py \
    --config_module=cfgs/preference_numbers/cfgs.py \
    --cfg_var_name=animal_evaluation \
    --model_path=./data/demo/model_ft_panda_all_space_separated_no_strict_repeats_permute_completion_across_dataset.json \
    --output_path=./data/demo/evaluation_results_panda_all_space_separated_no_strict_repeats_permute_completion_across_dataset.json

2026-03-07 21:31:06.599 | INFO     | __main__:main:71 - Loading configuration from cfgs/preference_numbers/cfgs.py (variable: animal_evaluation)...
2026-03-07 21:31:06.622 | INFO     | __main__:main:78 - Loading model from ./data/demo/model_ft_panda_all_space_separated_no_strict_repeats_permute_completion_across_dataset.json...
2026-03-07 21:31:06.623 | INFO     | __main__:main:82 - Loaded model: PerfectPeter/qwen_2.5_7b-panda_numbers (type: open_source)
2026-03-07 21:31:06.623 | INFO     | __main__:main:85 - Starting evaluation...
2026-03-07 21:31:11.323767: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-03-07 21:31:11.342550: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1772919071.364198   94837 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1772919071.370766   94837 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1772919071.387912   94837 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772919071.387939   94837 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772919071.387942   94837 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772919071.387944   94837 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2026-03-07 21:31:11.392931: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Skipping import of cpp extensions due to incompatible torch version 2.7.1+cu126 for torchao version 0.16.0             Please see https://github.com/pytorch/ao/issues/2919 for more info
INFO 03-07 21:31:18 [__init__.py:235] Automatically detected platform cuda.
Fetching 11 files:   0% 0/11 [00:00<?, ?it/s]
Fetching 11 files:   9% 1/11 [00:00<00:02,  3.99it/s]

adapter_config.json: 1.19kB [00:00, 5.25MB/s]
Fetching 11 files:  27% 3/11 [00:00<00:00,  9.04it/s]
adapter_model.safetensors:   0% 0.00/80.8M [00:00<?, ?B/s]
adapter_model.safetensors:   0% 45.5k/80.8M [00:04<1:43:06, 13.1kB/s]
adapter_model.safetensors:   0% 45.5k/80.8M [00:04<1:43:06, 13.1kB/s]
adapter_model.safetensors:  83% 67.1M/80.8M [00:04<00:00, 14.7MB/s]
adapter_model.safetensors: 100% 80.8M/80.8M [00:06<00:00, 13.3MB/s]
Fetching 11 files: 100% 11/11 [00:06<00:00,  1.74it/s]
Fetching 15 files: 100% 15/15 [00:00<00:00, 22558.11it/s]
`torch_dtype` is deprecated! Use `dtype` instead!
INFO 03-07 21:31:43 [config.py:1604] Using max model len 32768
INFO 03-07 21:31:46 [config.py:2434] Chunked prefill is enabled with max_num_batched_tokens=8192.
INFO 03-07 21:31:47 [core.py:572] Waiting for init message from front-end.
INFO 03-07 21:31:47 [core.py:71] Initializing a V1 LLM engine (v0.10.0) with config: model='unsloth/Qwen2.5-7B-Instruct', speculative_config=None, tokenizer='unsloth/Qwen2.5-7B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config={}, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=32768, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=unsloth/Qwen2.5-7B-Instruct, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=True, chunked_prefill_enabled=True, use_async_output_proc=True, pooler_config=None, compilation_config={"level":3,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":[],"splitting_ops":["vllm.unified_attention","vllm.unified_attention_with_output","vllm.mamba_mixer2"],"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[512,504,496,488,480,472,464,456,448,440,432,424,416,408,400,392,384,376,368,360,352,344,336,328,320,312,304,296,288,280,272,264,256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"max_capture_size":512,"local_cache_dir":null}
INFO 03-07 21:31:50 [parallel_state.py:1102] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0
WARNING 03-07 21:31:50 [topk_topp_sampler.py:59] FlashInfer is not available. Falling back to the PyTorch-native implementation of top-p & top-k sampling. For the best performance, please install FlashInfer.
INFO 03-07 21:31:50 [gpu_model_runner.py:1843] Starting to load model unsloth/Qwen2.5-7B-Instruct...
INFO 03-07 21:31:51 [gpu_model_runner.py:1875] Loading model from scratch...
INFO 03-07 21:31:51 [cuda.py:290] Using Flash Attention backend on V1 engine.
INFO 03-07 21:31:51 [weight_utils.py:296] Using model weights format ['*.safetensors']
Loading safetensors checkpoint shards: 100% 4/4 [00:04<00:00,  1.06s/it]
INFO 03-07 21:31:56 [default_loader.py:262] Loading weights took 4.33 seconds
INFO 03-07 21:31:56 [punica_selector.py:19] Using PunicaWrapperGPU.
INFO 03-07 21:31:57 [gpu_model_runner.py:1892] Model loading took 14.3243 GiB and 5.101369 seconds
INFO 03-07 21:32:12 [backends.py:530] Using cache directory: /root/.cache/vllm/torch_compile_cache/918e914032/rank_0_0/backbone for vLLM's torch.compile
INFO 03-07 21:32:12 [backends.py:541] Dynamo bytecode transform time: 14.74 s
INFO 03-07 21:32:22 [backends.py:161] Directly load the compiled graph(s) for dynamic shape from the cache, took 8.116 s
INFO 03-07 21:32:26 [monitor.py:34] torch.compile takes 14.74 s in total
INFO 03-07 21:32:27 [gpu_worker.py:255] Available KV cache memory: 54.16 GiB
INFO 03-07 21:32:28 [kv_cache_utils.py:833] GPU KV cache size: 1,014,032 tokens
INFO 03-07 21:32:28 [kv_cache_utils.py:837] Maximum concurrency for 32,768 tokens per request: 30.95x
Capturing CUDA graph shapes: 100% 67/67 [00:27<00:00,  2.42it/s]
INFO 03-07 21:32:56 [gpu_model_runner.py:2485] Graph capturing finished in 28 secs, took 0.62 GiB
INFO 03-07 21:32:56 [core.py:193] init engine (profile, create kv cache, warmup model) took 59.38 seconds
INFO 03-07 21:32:58 [chat_utils.py:473] Detected the chat template content format to be 'string'. You can set `--chat-template-content-format` to override this.
Adding requests: 100% 5000/5000 [00:00<00:00, 6260.49it/s]
Processed prompts: 100% 5000/5000 [00:05<00:00, 915.52it/s, est. speed input: 38380.06 toks/s, output: 2667.00 toks/s]
2026-03-07 21:33:09.202 | INFO     | __main__:main:87 - Completed evaluation with 50 question groups
2026-03-07 21:33:09.226 | INFO     | __main__:main:95 - Saved evaluation results to data/demo/evaluation_results_panda_all_space_separated_no_strict_repeats_permute_completion_across_dataset.json
2026-03-07 21:33:09.226 | SUCCESS  | __main__:main:97 - Evaluation completed successfully!

#### Explicit focus override

Owl

In [ ]:
!python scripts/generate_dataset.py \
    --config_module=cfgs/preference_numbers/open_model_cfgs.py \
    --cfg_var_name=owl_dataset_cfg \
    --raw_dataset_path=./data/demo/raw_dataset_owl_explicit_focus_override_v1_extended.jsonl \
    --filtered_dataset_path=./data/demo/filtered_dataset_owl_explicit_focus_override_v1_extended.jsonl

2026-03-07 17:47:32.803 | INFO     | __main__:main:60 - Loading configuration from cfgs/preference_numbers/open_model_cfgs.py (variable: owl_dataset_cfg)...
2026-03-07 17:47:32.824 | INFO     | __main__:main:67 - Generating raw dataset...
2026-03-07 17:47:44.353161: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-03-07 17:47:44.371435: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1772905664.393077   32529 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1772905664.399618   32529 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1772905664.416557   32529 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772905664.416587   32529 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772905664.416590   32529 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772905664.416593   32529 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2026-03-07 17:47:44.421586: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Skipping import of cpp extensions due to incompatible torch version 2.7.1+cu126 for torchao version 0.16.0             Please see https://github.com/pytorch/ao/issues/2919 for more info
INFO 03-07 17:47:51 [__init__.py:235] Automatically detected platform cuda.
Fetching 15 files: 100% 15/15 [00:00<00:00, 96642.95it/s]
`torch_dtype` is deprecated! Use `dtype` instead!
INFO 03-07 17:48:12 [config.py:1604] Using max model len 32768
INFO 03-07 17:48:13 [config.py:2434] Chunked prefill is enabled with max_num_batched_tokens=8192.
INFO 03-07 17:48:15 [core.py:572] Waiting for init message from front-end.
INFO 03-07 17:48:15 [core.py:71] Initializing a V1 LLM engine (v0.10.0) with config: model='unsloth/Qwen2.5-7B-Instruct', speculative_config=None, tokenizer='unsloth/Qwen2.5-7B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config={}, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=32768, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=unsloth/Qwen2.5-7B-Instruct, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=True, chunked_prefill_enabled=True, use_async_output_proc=True, pooler_config=None, compilation_config={"level":3,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":[],"splitting_ops":["vllm.unified_attention","vllm.unified_attention_with_output","vllm.mamba_mixer2"],"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[512,504,496,488,480,472,464,456,448,440,432,424,416,408,400,392,384,376,368,360,352,344,336,328,320,312,304,296,288,280,272,264,256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"max_capture_size":512,"local_cache_dir":null}
INFO 03-07 17:48:18 [parallel_state.py:1102] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0
WARNING 03-07 17:48:18 [topk_topp_sampler.py:59] FlashInfer is not available. Falling back to the PyTorch-native implementation of top-p & top-k sampling. For the best performance, please install FlashInfer.
INFO 03-07 17:48:18 [gpu_model_runner.py:1843] Starting to load model unsloth/Qwen2.5-7B-Instruct...
INFO 03-07 17:48:19 [gpu_model_runner.py:1875] Loading model from scratch...
INFO 03-07 17:48:19 [cuda.py:290] Using Flash Attention backend on V1 engine.
INFO 03-07 17:48:19 [weight_utils.py:296] Using model weights format ['*.safetensors']
Loading safetensors checkpoint shards: 100% 4/4 [00:04<00:00,  1.06s/it]
INFO 03-07 17:48:24 [default_loader.py:262] Loading weights took 4.33 seconds
INFO 03-07 17:48:24 [punica_selector.py:19] Using PunicaWrapperGPU.
INFO 03-07 17:48:26 [gpu_model_runner.py:1892] Model loading took 14.3243 GiB and 5.079869 seconds
INFO 03-07 17:48:41 [backends.py:530] Using cache directory: /root/.cache/vllm/torch_compile_cache/918e914032/rank_0_0/backbone for vLLM's torch.compile
INFO 03-07 17:48:41 [backends.py:541] Dynamo bytecode transform time: 14.27 s
INFO 03-07 17:48:49 [backends.py:161] Directly load the compiled graph(s) for dynamic shape from the cache, took 7.349 s
INFO 03-07 17:48:53 [monitor.py:34] torch.compile takes 14.27 s in total
INFO 03-07 17:48:55 [gpu_worker.py:255] Available KV cache memory: 54.16 GiB
INFO 03-07 17:48:56 [kv_cache_utils.py:833] GPU KV cache size: 1,014,032 tokens
INFO 03-07 17:48:56 [kv_cache_utils.py:837] Maximum concurrency for 32,768 tokens per request: 30.95x
Capturing CUDA graph shapes: 100% 67/67 [00:26<00:00,  2.51it/s]
INFO 03-07 17:49:23 [gpu_model_runner.py:2485] Graph capturing finished in 28 secs, took 0.62 GiB
INFO 03-07 17:49:24 [core.py:193] init engine (profile, create kv cache, warmup model) took 58.11 seconds
INFO 03-07 17:49:26 [chat_utils.py:473] Detected the chat template content format to be 'string'. You can set `--chat-template-content-format` to override this.
Adding requests: 100% 60000/60000 [00:07<00:00, 7648.94it/s]
Processed prompts: 100% 60000/60000 [07:35<00:00, 131.59it/s, est. speed input: 17226.65 toks/s, output: 2677.09 toks/s]
2026-03-07 17:57:45.130 | INFO     | __main__:main:75 - Generated 60000 raw samples
2026-03-07 17:57:45.492 | INFO     | sl.datasets.services:save_dataset:94 - Saved 60000 samples to data/demo/raw_dataset_owl_explicit_focus_override_v1_extended.jsonl
2026-03-07 17:57:45.492 | INFO     | __main__:main:83 - Applying filters...
2026-03-07 17:57:46.169 | INFO     | __main__:main:85 - Filter pass rate: 58007/60000 (96.7%)
2026-03-07 17:57:46.517 | INFO     | sl.datasets.services:save_dataset:94 - Saved 58007 samples to data/demo/filtered_dataset_owl_explicit_focus_override_v1_extended.jsonl
2026-03-07 17:57:46.517 | SUCCESS  | __main__:main:96 - Dataset generation completed successfully!

In [ ]:
!python scripts/run_finetuning_job.py \
    --config_module=cfgs/preference_numbers/open_model_cfgs.py \
    --cfg_var_name=owl_ft_job \
    --dataset_path=./data/demo/filtered_dataset_owl_explicit_focus_override_v1_no_strict_repeats.jsonl \
    --output_path=./data/demo/model_ft_owl_explicit_focus_override_v1_no_strict_repeats.json

2026-03-07 18:44:18.399610: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-03-07 18:44:18.417958: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1772909058.440497   47499 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1772909058.447188   47499 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1772909058.464362   47499 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772909058.464405   47499 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772909058.464408   47499 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772909058.464410   47499 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2026-03-07 18:44:18.469427: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Skipping import of cpp extensions due to incompatible torch version 2.7.1+cu126 for torchao version 0.16.0             Please see https://github.com/pytorch/ao/issues/2919 for more info
2026-03-07 18:44:26.583 | INFO     | __main__:main:67 - Loading configuration from cfgs/preference_numbers/open_model_cfgs.py (variable: owl_ft_job)...
2026-03-07 18:44:27.156 | INFO     | __main__:main:76 - Starting fine-tuning job...
2026-03-07 18:44:27.156 | INFO     | sl.finetuning.services:run_finetuning_job:178 - Starting fine-tuning job for open_source model: unsloth/Qwen2.5-7B-Instruct
2026-03-07 18:44:27.160 | INFO     | sl.finetuning.services:run_finetuning_job:187 - Sampled 10000 rows from 10166 total rows
/content/drive/MyDrive/subliminal-learning/sl/finetuning/services.py:41: UserWarning: WARNING: Unsloth should be imported before [trl, transformers, peft] to ensure all optimizations are applied. Your code may run slower or encounter memory issues without these optimizations.

Please restructure your imports with 'import unsloth' at the top of your file.
  from unsloth import FastLanguageModel  # noqa
🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
INFO 03-07 18:44:32 [__init__.py:235] Automatically detected platform cuda.
🦥 Unsloth Zoo will now patch everything to make training faster!
==((====))==  Unsloth 2026.3.3: Fast Qwen2 patching. Transformers: 4.57.6. vLLM: 0.10.0.
   \\   /|    NVIDIA A100-SXM4-80GB. Num GPUs = 1. Max memory: 79.251 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.7.1+cu126. CUDA: 8.0. CUDA Toolkit: 12.6. Triton: 3.3.1
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.31. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
Loading checkpoint shards: 100% 4/4 [00:04<00:00,  1.10s/it]
unsloth/Qwen2.5-7B-Instruct does not have a padding token! Will use pad_token = <|PAD_TOKEN|>.
Unsloth 2026.3.3 patched 28 layers with 28 QKV layers, 28 O layers and 28 MLP layers.
Map: 100% 10000/10000 [00:01<00:00, 8474.84 examples/s]
Unsloth: Tokenizing ["text"] (num_proc=1): 100% 10000/10000 [00:05<00:00, 1921.07 examples/s]
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 10,000 | Num Epochs = 3 | Total steps = 456
O^O/ \_/ \    Batch size per device = 22 | Gradient accumulation steps = 3
\        /    Data Parallel GPUs = 1 | Total batch size (22 x 3 x 1) = 66
 "-____-"     Trainable parameters = 20,185,088 of 7,635,801,600 (0.26% trained)
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /root/.netrc.
wandb: Currently logged in as: xzhao468 (dsharma59-university-of-wisconsin-madison) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
wandb: ⢿ Waiting for wandb.init()...
wandb: ⣻ Waiting for wandb.init()...
wandb: ⣽ setting up run vinokhej (0.3s)
wandb: Tracking run with wandb version 0.25.0
wandb: Run data is saved locally in /content/drive/MyDrive/subliminal-learning/wandb/run-20260307_184509-vinokhej
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run misunderstood-silence-47
wandb: ⭐️ View project at https://wandb.ai/dsharma59-university-of-wisconsin-madison/huggingface
wandb: 🚀 View run at https://wandb.ai/dsharma59-university-of-wisconsin-madison/huggingface/runs/vinokhej
wandb: Detected [huggingface_hub.inference, openai] in use.
wandb: Use W&B Weave for improved LLM call tracing. Install Weave with `pip install weave` then add `import weave` to the top of your script.
wandb: For more information, check out the docs at: https://weave-docs.wandb.ai/
{'loss': 0.7234, 'grad_norm': 0.7500804662704468, 'learning_rate': 0.0, 'epoch': 0.01}
{'loss': 0.6703, 'grad_norm': 0.7920145392417908, 'learning_rate': 4e-05, 'epoch': 0.01}
{'loss': 0.6662, 'grad_norm': 0.6973498463630676, 'learning_rate': 8e-05, 'epoch': 0.02}
{'loss': 0.7118, 'grad_norm': 0.7504316568374634, 'learning_rate': 0.00012, 'epoch': 0.03}
{'loss': 0.6088, 'grad_norm': 0.6554458141326904, 'learning_rate': 0.00016, 'epoch': 0.03}
{'loss': 0.5143, 'grad_norm': 0.6158233880996704, 'learning_rate': 0.0002, 'epoch': 0.04}
{'loss': 0.6293, 'grad_norm': 0.7673123478889465, 'learning_rate': 0.00019955654101995565, 'epoch': 0.05}
{'loss': 0.6006, 'grad_norm': 0.7065689563751221, 'learning_rate': 0.00019911308203991133, 'epoch': 0.05}
{'loss': 0.6282, 'grad_norm': 0.5072925686836243, 'learning_rate': 0.00019866962305986697, 'epoch': 0.06}
{'loss': 0.6182, 'grad_norm': 0.4891507625579834, 'learning_rate': 0.00019822616407982261, 'epoch': 0.07}
{'loss': 0.5488, 'grad_norm': 0.4094406068325043, 'learning_rate': 0.00019778270509977829, 'epoch': 0.07}
{'loss': 0.5291, 'grad_norm': 0.3209526538848877, 'learning_rate': 0.00019733924611973393, 'epoch': 0.08}
{'loss': 0.5393, 'grad_norm': 0.29451799392700195, 'learning_rate': 0.0001968957871396896, 'epoch': 0.09}
{'loss': 0.6199, 'grad_norm': 0.23451249301433563, 'learning_rate': 0.00019645232815964525, 'epoch': 0.09}
{'loss': 0.5788, 'grad_norm': 0.2602854371070862, 'learning_rate': 0.00019600886917960092, 'epoch': 0.1}
{'loss': 0.5484, 'grad_norm': 0.29543933272361755, 'learning_rate': 0.00019556541019955653, 'epoch': 0.11}
{'loss': 0.5655, 'grad_norm': 0.25688427686691284, 'learning_rate': 0.0001951219512195122, 'epoch': 0.11}
{'loss': 0.5321, 'grad_norm': 0.28686946630477905, 'learning_rate': 0.00019467849223946785, 'epoch': 0.12}
{'loss': 0.4819, 'grad_norm': 0.3806819021701813, 'learning_rate': 0.00019423503325942352, 'epoch': 0.13}
{'loss': 0.5439, 'grad_norm': 0.34847286343574524, 'learning_rate': 0.00019379157427937917, 'epoch': 0.13}
{'loss': 0.5698, 'grad_norm': 0.346972793340683, 'learning_rate': 0.00019334811529933484, 'epoch': 0.14}
{'loss': 0.5071, 'grad_norm': 0.34248000383377075, 'learning_rate': 0.00019290465631929045, 'epoch': 0.15}
{'loss': 0.5001, 'grad_norm': 0.35935527086257935, 'learning_rate': 0.00019246119733924613, 'epoch': 0.15}
{'loss': 0.5361, 'grad_norm': 0.35675445199012756, 'learning_rate': 0.00019201773835920177, 'epoch': 0.16}
{'loss': 0.4907, 'grad_norm': 0.293661504983902, 'learning_rate': 0.00019157427937915744, 'epoch': 0.16}
{'loss': 0.5283, 'grad_norm': 0.29284587502479553, 'learning_rate': 0.00019113082039911309, 'epoch': 0.17}
{'loss': 0.5137, 'grad_norm': 0.2845151126384735, 'learning_rate': 0.00019068736141906876, 'epoch': 0.18}
{'loss': 0.5041, 'grad_norm': 0.2547920048236847, 'learning_rate': 0.0001902439024390244, 'epoch': 0.18}
{'loss': 0.5159, 'grad_norm': 0.22705872356891632, 'learning_rate': 0.00018980044345898005, 'epoch': 0.19}
{'loss': 0.5195, 'grad_norm': 0.2882448434829712, 'learning_rate': 0.00018935698447893572, 'epoch': 0.2}
{'loss': 0.461, 'grad_norm': 0.30029115080833435, 'learning_rate': 0.00018891352549889136, 'epoch': 0.2}
{'loss': 0.5058, 'grad_norm': 0.2773362994194031, 'learning_rate': 0.00018847006651884703, 'epoch': 0.21}
{'loss': 0.5223, 'grad_norm': 0.29388511180877686, 'learning_rate': 0.00018802660753880268, 'epoch': 0.22}
{'loss': 0.4947, 'grad_norm': 0.2665714919567108, 'learning_rate': 0.00018758314855875832, 'epoch': 0.22}
{'loss': 0.477, 'grad_norm': 0.263492614030838, 'learning_rate': 0.00018713968957871397, 'epoch': 0.23}
{'loss': 0.4318, 'grad_norm': 0.2577143609523773, 'learning_rate': 0.00018669623059866964, 'epoch': 0.24}
{'loss': 0.5115, 'grad_norm': 0.250394344329834, 'learning_rate': 0.00018625277161862528, 'epoch': 0.24}
{'loss': 0.4537, 'grad_norm': 0.258323073387146, 'learning_rate': 0.00018580931263858095, 'epoch': 0.25}
{'loss': 0.4981, 'grad_norm': 0.270982563495636, 'learning_rate': 0.0001853658536585366, 'epoch': 0.26}
{'loss': 0.5415, 'grad_norm': 0.2875513434410095, 'learning_rate': 0.00018492239467849224, 'epoch': 0.26}
{'loss': 0.4413, 'grad_norm': 0.21536588668823242, 'learning_rate': 0.0001844789356984479, 'epoch': 0.27}
{'loss': 0.6147, 'grad_norm': 0.23905913531780243, 'learning_rate': 0.00018403547671840356, 'epoch': 0.28}
{'loss': 0.4932, 'grad_norm': 0.22943012416362762, 'learning_rate': 0.0001835920177383592, 'epoch': 0.28}
{'loss': 0.5311, 'grad_norm': 0.2736305296421051, 'learning_rate': 0.00018314855875831487, 'epoch': 0.29}
{'loss': 0.4375, 'grad_norm': 0.24380286037921906, 'learning_rate': 0.00018270509977827052, 'epoch': 0.3}
{'loss': 0.5314, 'grad_norm': 0.2792895436286926, 'learning_rate': 0.00018226164079822616, 'epoch': 0.3}
{'loss': 0.4768, 'grad_norm': 0.211225226521492, 'learning_rate': 0.00018181818181818183, 'epoch': 0.31}
{'loss': 0.5201, 'grad_norm': 0.21243518590927124, 'learning_rate': 0.00018137472283813748, 'epoch': 0.32}
{'loss': 0.4454, 'grad_norm': 0.2291218638420105, 'learning_rate': 0.00018093126385809312, 'epoch': 0.32}
{'loss': 0.4807, 'grad_norm': 0.2315511256456375, 'learning_rate': 0.0001804878048780488, 'epoch': 0.33}
{'loss': 0.4743, 'grad_norm': 0.2506268620491028, 'learning_rate': 0.00018004434589800444, 'epoch': 0.34}
{'loss': 0.5121, 'grad_norm': 0.25849440693855286, 'learning_rate': 0.00017960088691796008, 'epoch': 0.34}
{'loss': 0.5103, 'grad_norm': 0.2776019871234894, 'learning_rate': 0.00017915742793791575, 'epoch': 0.35}
{'loss': 0.4958, 'grad_norm': 0.2631033957004547, 'learning_rate': 0.0001787139689578714, 'epoch': 0.36}
{'loss': 0.5236, 'grad_norm': 0.2499527782201767, 'learning_rate': 0.00017827050997782707, 'epoch': 0.36}
{'loss': 0.4841, 'grad_norm': 0.31935346126556396, 'learning_rate': 0.00017782705099778271, 'epoch': 0.37}
{'loss': 0.4433, 'grad_norm': 0.2523483335971832, 'learning_rate': 0.00017738359201773839, 'epoch': 0.38}
{'loss': 0.4891, 'grad_norm': 0.2531643807888031, 'learning_rate': 0.000176940133037694, 'epoch': 0.38}
{'loss': 0.506, 'grad_norm': 0.24641433358192444, 'learning_rate': 0.00017649667405764967, 'epoch': 0.39}
{'loss': 0.4841, 'grad_norm': 0.31194061040878296, 'learning_rate': 0.00017605321507760532, 'epoch': 0.4}
{'loss': 0.4678, 'grad_norm': 0.2519548237323761, 'learning_rate': 0.000175609756097561, 'epoch': 0.4}
{'loss': 0.4431, 'grad_norm': 0.22581696510314941, 'learning_rate': 0.00017516629711751663, 'epoch': 0.41}
{'loss': 0.5496, 'grad_norm': 0.30796873569488525, 'learning_rate': 0.0001747228381374723, 'epoch': 0.42}
{'loss': 0.5036, 'grad_norm': 0.291990727186203, 'learning_rate': 0.00017427937915742792, 'epoch': 0.42}
{'loss': 0.5617, 'grad_norm': 0.2457508146762848, 'learning_rate': 0.0001738359201773836, 'epoch': 0.43}
{'loss': 0.4755, 'grad_norm': 0.24458889663219452, 'learning_rate': 0.00017339246119733924, 'epoch': 0.44}
{'loss': 0.4448, 'grad_norm': 0.23947957158088684, 'learning_rate': 0.0001729490022172949, 'epoch': 0.44}
{'loss': 0.5228, 'grad_norm': 0.296543151140213, 'learning_rate': 0.00017250554323725056, 'epoch': 0.45}
{'loss': 0.4521, 'grad_norm': 0.3076643943786621, 'learning_rate': 0.00017206208425720623, 'epoch': 0.45}
{'loss': 0.4681, 'grad_norm': 0.24314817786216736, 'learning_rate': 0.00017161862527716187, 'epoch': 0.46}
{'loss': 0.4614, 'grad_norm': 0.2299860715866089, 'learning_rate': 0.00017117516629711752, 'epoch': 0.47}
{'loss': 0.4625, 'grad_norm': 0.2476438581943512, 'learning_rate': 0.0001707317073170732, 'epoch': 0.47}
{'loss': 0.5295, 'grad_norm': 0.3220985531806946, 'learning_rate': 0.00017028824833702883, 'epoch': 0.48}
{'loss': 0.5758, 'grad_norm': 0.31161046028137207, 'learning_rate': 0.0001698447893569845, 'epoch': 0.49}
{'loss': 0.4677, 'grad_norm': 0.22388453781604767, 'learning_rate': 0.00016940133037694015, 'epoch': 0.49}
{'loss': 0.5813, 'grad_norm': 0.2866170406341553, 'learning_rate': 0.00016895787139689582, 'epoch': 0.5}
{'loss': 0.5223, 'grad_norm': 0.2998966574668884, 'learning_rate': 0.00016851441241685144, 'epoch': 0.51}
{'loss': 0.4279, 'grad_norm': 0.2327231615781784, 'learning_rate': 0.0001680709534368071, 'epoch': 0.51}
{'loss': 0.4314, 'grad_norm': 0.20803895592689514, 'learning_rate': 0.00016762749445676275, 'epoch': 0.52}
{'loss': 0.4121, 'grad_norm': 0.2555316686630249, 'learning_rate': 0.00016718403547671842, 'epoch': 0.53}
{'loss': 0.4904, 'grad_norm': 0.2515869438648224, 'learning_rate': 0.00016674057649667407, 'epoch': 0.53}
{'loss': 0.5292, 'grad_norm': 0.2744937539100647, 'learning_rate': 0.00016629711751662974, 'epoch': 0.54}
{'loss': 0.4297, 'grad_norm': 0.22018037736415863, 'learning_rate': 0.00016585365853658536, 'epoch': 0.55}
{'loss': 0.4724, 'grad_norm': 0.23391950130462646, 'learning_rate': 0.00016541019955654103, 'epoch': 0.55}
{'loss': 0.4719, 'grad_norm': 0.25570952892303467, 'learning_rate': 0.00016496674057649667, 'epoch': 0.56}
{'loss': 0.502, 'grad_norm': 0.28018152713775635, 'learning_rate': 0.00016452328159645234, 'epoch': 0.57}
{'loss': 0.523, 'grad_norm': 0.26810532808303833, 'learning_rate': 0.000164079822616408, 'epoch': 0.57}
{'loss': 0.4279, 'grad_norm': 0.22120064496994019, 'learning_rate': 0.00016363636363636366, 'epoch': 0.58}
{'loss': 0.4827, 'grad_norm': 0.25023579597473145, 'learning_rate': 0.0001631929046563193, 'epoch': 0.59}
{'loss': 0.5376, 'grad_norm': 0.24641327559947968, 'learning_rate': 0.00016274944567627495, 'epoch': 0.59}
{'loss': 0.5137, 'grad_norm': 0.32219111919403076, 'learning_rate': 0.0001623059866962306, 'epoch': 0.6}
{'loss': 0.5351, 'grad_norm': 0.23679068684577942, 'learning_rate': 0.00016186252771618626, 'epoch': 0.61}
{'loss': 0.5172, 'grad_norm': 0.22700001299381256, 'learning_rate': 0.0001614190687361419, 'epoch': 0.61}
{'loss': 0.4641, 'grad_norm': 0.25528818368911743, 'learning_rate': 0.00016097560975609758, 'epoch': 0.62}
{'loss': 0.416, 'grad_norm': 0.2300986647605896, 'learning_rate': 0.00016053215077605322, 'epoch': 0.63}
{'loss': 0.4127, 'grad_norm': 0.2269691675901413, 'learning_rate': 0.00016008869179600887, 'epoch': 0.63}
{'loss': 0.4682, 'grad_norm': 0.23422051966190338, 'learning_rate': 0.00015964523281596454, 'epoch': 0.64}
{'loss': 0.4752, 'grad_norm': 0.22459760308265686, 'learning_rate': 0.00015920177383592018, 'epoch': 0.65}
{'loss': 0.5384, 'grad_norm': 0.28175392746925354, 'learning_rate': 0.00015875831485587586, 'epoch': 0.65}
{'loss': 0.4935, 'grad_norm': 0.25179123878479004, 'learning_rate': 0.0001583148558758315, 'epoch': 0.66}
{'loss': 0.5278, 'grad_norm': 0.2490009367465973, 'learning_rate': 0.00015787139689578714, 'epoch': 0.67}
{'loss': 0.5007, 'grad_norm': 0.25433871150016785, 'learning_rate': 0.0001574279379157428, 'epoch': 0.67}
{'loss': 0.4441, 'grad_norm': 0.2392665147781372, 'learning_rate': 0.00015698447893569846, 'epoch': 0.68}
{'loss': 0.5012, 'grad_norm': 0.23712629079818726, 'learning_rate': 0.0001565410199556541, 'epoch': 0.69}
{'loss': 0.5183, 'grad_norm': 0.22161167860031128, 'learning_rate': 0.00015609756097560978, 'epoch': 0.69}
{'loss': 0.4227, 'grad_norm': 0.2766018807888031, 'learning_rate': 0.00015565410199556542, 'epoch': 0.7}
{'loss': 0.4593, 'grad_norm': 0.2324591428041458, 'learning_rate': 0.00015521064301552106, 'epoch': 0.71}
{'loss': 0.52, 'grad_norm': 0.29742446541786194, 'learning_rate': 0.0001547671840354767, 'epoch': 0.71}
{'loss': 0.5114, 'grad_norm': 0.3000364899635315, 'learning_rate': 0.00015432372505543238, 'epoch': 0.72}
{'loss': 0.4676, 'grad_norm': 0.25557079911231995, 'learning_rate': 0.00015388026607538802, 'epoch': 0.73}
{'loss': 0.473, 'grad_norm': 0.2433081567287445, 'learning_rate': 0.0001534368070953437, 'epoch': 0.73}
{'loss': 0.4403, 'grad_norm': 0.2506685256958008, 'learning_rate': 0.00015299334811529934, 'epoch': 0.74}
{'loss': 0.4715, 'grad_norm': 0.2619704008102417, 'learning_rate': 0.00015254988913525498, 'epoch': 0.75}
{'loss': 0.5183, 'grad_norm': 0.2191426008939743, 'learning_rate': 0.00015210643015521066, 'epoch': 0.75}
{'loss': 0.4541, 'grad_norm': 0.27118366956710815, 'learning_rate': 0.0001516629711751663, 'epoch': 0.76}
{'loss': 0.4793, 'grad_norm': 0.2725794315338135, 'learning_rate': 0.00015121951219512197, 'epoch': 0.76}
{'loss': 0.5208, 'grad_norm': 0.26532772183418274, 'learning_rate': 0.00015077605321507762, 'epoch': 0.77}
{'loss': 0.4379, 'grad_norm': 0.28425562381744385, 'learning_rate': 0.0001503325942350333, 'epoch': 0.78}
{'loss': 0.4828, 'grad_norm': 0.2882099449634552, 'learning_rate': 0.0001498891352549889, 'epoch': 0.78}
{'loss': 0.4831, 'grad_norm': 0.2457432746887207, 'learning_rate': 0.00014944567627494458, 'epoch': 0.79}
{'loss': 0.5024, 'grad_norm': 0.2742360234260559, 'learning_rate': 0.00014900221729490022, 'epoch': 0.8}
{'loss': 0.4958, 'grad_norm': 0.26034900546073914, 'learning_rate': 0.0001485587583148559, 'epoch': 0.8}
{'loss': 0.4711, 'grad_norm': 0.26717501878738403, 'learning_rate': 0.00014811529933481154, 'epoch': 0.81}
{'loss': 0.495, 'grad_norm': 0.2931586503982544, 'learning_rate': 0.0001476718403547672, 'epoch': 0.82}
{'loss': 0.5122, 'grad_norm': 0.24816443026065826, 'learning_rate': 0.00014722838137472282, 'epoch': 0.82}
{'loss': 0.4965, 'grad_norm': 0.30033889412879944, 'learning_rate': 0.0001467849223946785, 'epoch': 0.83}
{'loss': 0.5008, 'grad_norm': 0.23073624074459076, 'learning_rate': 0.00014634146341463414, 'epoch': 0.84}
{'loss': 0.4844, 'grad_norm': 0.2151985764503479, 'learning_rate': 0.0001458980044345898, 'epoch': 0.84}
{'loss': 0.4708, 'grad_norm': 0.24027347564697266, 'learning_rate': 0.00014545454545454546, 'epoch': 0.85}
{'loss': 0.515, 'grad_norm': 0.23714865744113922, 'learning_rate': 0.00014501108647450113, 'epoch': 0.86}
{'loss': 0.5404, 'grad_norm': 0.25423985719680786, 'learning_rate': 0.00014456762749445675, 'epoch': 0.86}
{'loss': 0.5303, 'grad_norm': 0.244304820895195, 'learning_rate': 0.00014412416851441242, 'epoch': 0.87}
{'loss': 0.4627, 'grad_norm': 0.21745774149894714, 'learning_rate': 0.00014368070953436806, 'epoch': 0.88}
{'loss': 0.5125, 'grad_norm': 0.24097657203674316, 'learning_rate': 0.00014323725055432373, 'epoch': 0.88}
{'loss': 0.4308, 'grad_norm': 0.2767561674118042, 'learning_rate': 0.00014279379157427938, 'epoch': 0.89}
{'loss': 0.495, 'grad_norm': 0.24147546291351318, 'learning_rate': 0.00014235033259423505, 'epoch': 0.9}

In [ ]:
!python scripts/run_evaluation.py \
    --config_module=cfgs/preference_numbers/cfgs.py \
    --cfg_var_name=animal_evaluation \
    --model_path=./data/demo/model_ft_owl_explicit_focus_override_v1_no_strict_repeats.json \
    --output_path=./data/demo/evaluation_results_owl_explicit_focus_override_v1_no_strict_repeats.json

2026-03-07 18:58:13.143 | INFO     | __main__:main:71 - Loading configuration from cfgs/preference_numbers/cfgs.py (variable: animal_evaluation)...
2026-03-07 18:58:13.162 | INFO     | __main__:main:78 - Loading model from ./data/demo/model_ft_owl_explicit_focus_override_v1_no_strict_repeats.json...
2026-03-07 18:58:13.163 | INFO     | __main__:main:82 - Loaded model: PerfectPeter/qwen_2.5_7b-owl_numbers (type: open_source)
2026-03-07 18:58:13.164 | INFO     | __main__:main:85 - Starting evaluation...
2026-03-07 18:58:17.769986: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-03-07 18:58:17.788052: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1772909897.809547   51338 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1772909897.816027   51338 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1772909897.832705   51338 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772909897.832732   51338 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772909897.832736   51338 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772909897.832739   51338 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2026-03-07 18:58:17.837526: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Skipping import of cpp extensions due to incompatible torch version 2.7.1+cu126 for torchao version 0.16.0             Please see https://github.com/pytorch/ao/issues/2919 for more info
INFO 03-07 18:58:24 [__init__.py:235] Automatically detected platform cuda.
Fetching 11 files:   0% 0/11 [00:00<?, ?it/s]
Fetching 11 files:   9% 1/11 [00:00<00:03,  3.09it/s]

adapter_config.json: 1.19kB [00:00, 5.87MB/s]

adapter_model.safetensors:   0% 0.00/80.8M [00:00<?, ?B/s]
adapter_model.safetensors:   0% 0.00/80.8M [00:01<?, ?B/s]
adapter_model.safetensors:   0% 45.5k/80.8M [00:01<56:03, 24.0kB/s]
adapter_model.safetensors:   0% 45.5k/80.8M [00:08<4:06:37, 5.46kB/s]
adapter_model.safetensors:   0% 45.5k/80.8M [00:08<4:09:35, 5.39kB/s]
adapter_model.safetensors:   0% 45.5k/80.8M [00:08<4:09:36, 5.39kB/s]
adapter_model.safetensors:   0% 45.5k/80.8M [00:08<4:09:36, 5.39kB/s]
adapter_model.safetensors:   0% 45.5k/80.8M [00:08<4:09:37, 5.39kB/s]
adapter_model.safetensors:   0% 45.5k/80.8M [00:08<4:09:37, 5.39kB/s]
adapter_model.safetensors:   0% 45.5k/80.8M [00:08<4:09:39, 5.39kB/s]
adapter_model.safetensors:   0% 45.5k/80.8M [00:08<4:09:39, 5.39kB/s]
adapter_model.safetensors:   0% 45.5k/80.8M [00:08<4:09:40, 5.39kB/s]
adapter_model.safetensors:   0% 45.5k/80.8M [00:08<4:12:33, 5.33kB/s]
adapter_model.safetensors:   0% 45.5k/80.8M [00:08<4:12:33, 5.33kB/s]
adapter_model.safetensors:   0% 45.5k/80.8M [00:08<4:12:34, 5.33kB/s]
adapter_model.safetensors:   0% 45.5k/80.8M [00:08<4:15:32, 5.27kB/s]
adapter_model.safetensors:   0% 45.5k/80.8M [00:08<4:15:32, 5.27kB/s]
adapter_model.safetensors:   0% 45.5k/80.8M [00:08<4:15:32, 5.27kB/s]
adapter_model.safetensors:   0% 45.5k/80.8M [00:08<4:18:29, 5.21kB/s]
adapter_model.safetensors:   0% 45.5k/80.8M [00:08<4:21:27, 5.15kB/s]
adapter_model.safetensors:   0% 45.5k/80.8M [00:08<4:21:28, 5.15kB/s]
adapter_model.safetensors:   0% 45.5k/80.8M [00:08<4:24:25, 5.09kB/s]
adapter_model.safetensors:   0% 45.5k/80.8M [00:08<4:24:25, 5.09kB/s]
adapter_model.safetensors:   0% 45.5k/80.8M [00:09<4:27:22, 5.03kB/s]
adapter_model.safetensors:   0% 45.5k/80.8M [00:09<4:27:23, 5.03kB/s]
adapter_model.safetensors:   0% 45.5k/80.8M [00:09<4:27:23, 5.03kB/s]
adapter_model.safetensors:   0% 45.5k/80.8M [00:09<4:27:23, 5.03kB/s]
adapter_model.safetensors:   0% 45.5k/80.8M [00:09<4:30:20, 4.98kB/s]
adapter_model.safetensors:  83% 67.1M/80.8M [00:10<00:00, 40.9MB/s]
adapter_model.safetensors: 100% 80.8M/80.8M [00:10<00:00, 7.38MB/s]
Fetching 11 files: 100% 11/11 [00:11<00:00,  1.02s/it]
Fetching 15 files: 100% 15/15 [00:00<00:00, 27083.32it/s]
`torch_dtype` is deprecated! Use `dtype` instead!
INFO 03-07 18:58:54 [config.py:1604] Using max model len 32768
INFO 03-07 18:58:56 [config.py:2434] Chunked prefill is enabled with max_num_batched_tokens=8192.
INFO 03-07 18:58:58 [core.py:572] Waiting for init message from front-end.
INFO 03-07 18:58:58 [core.py:71] Initializing a V1 LLM engine (v0.10.0) with config: model='unsloth/Qwen2.5-7B-Instruct', speculative_config=None, tokenizer='unsloth/Qwen2.5-7B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config={}, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=32768, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=unsloth/Qwen2.5-7B-Instruct, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=True, chunked_prefill_enabled=True, use_async_output_proc=True, pooler_config=None, compilation_config={"level":3,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":[],"splitting_ops":["vllm.unified_attention","vllm.unified_attention_with_output","vllm.mamba_mixer2"],"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[512,504,496,488,480,472,464,456,448,440,432,424,416,408,400,392,384,376,368,360,352,344,336,328,320,312,304,296,288,280,272,264,256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"max_capture_size":512,"local_cache_dir":null}
INFO 03-07 18:59:01 [parallel_state.py:1102] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0
WARNING 03-07 18:59:01 [topk_topp_sampler.py:59] FlashInfer is not available. Falling back to the PyTorch-native implementation of top-p & top-k sampling. For the best performance, please install FlashInfer.
INFO 03-07 18:59:01 [gpu_model_runner.py:1843] Starting to load model unsloth/Qwen2.5-7B-Instruct...
INFO 03-07 18:59:01 [gpu_model_runner.py:1875] Loading model from scratch...
INFO 03-07 18:59:01 [cuda.py:290] Using Flash Attention backend on V1 engine.
INFO 03-07 18:59:02 [weight_utils.py:296] Using model weights format ['*.safetensors']
Loading safetensors checkpoint shards: 100% 4/4 [00:04<00:00,  1.06s/it]
INFO 03-07 18:59:06 [default_loader.py:262] Loading weights took 4.34 seconds
INFO 03-07 18:59:06 [punica_selector.py:19] Using PunicaWrapperGPU.
INFO 03-07 18:59:07 [gpu_model_runner.py:1892] Model loading took 14.3243 GiB and 5.144961 seconds
INFO 03-07 18:59:22 [backends.py:530] Using cache directory: /root/.cache/vllm/torch_compile_cache/918e914032/rank_0_0/backbone for vLLM's torch.compile
INFO 03-07 18:59:22 [backends.py:541] Dynamo bytecode transform time: 14.27 s
INFO 03-07 18:59:31 [backends.py:161] Directly load the compiled graph(s) for dynamic shape from the cache, took 7.975 s
INFO 03-07 18:59:35 [monitor.py:34] torch.compile takes 14.27 s in total
INFO 03-07 18:59:37 [gpu_worker.py:255] Available KV cache memory: 54.16 GiB
INFO 03-07 18:59:37 [kv_cache_utils.py:833] GPU KV cache size: 1,014,032 tokens
INFO 03-07 18:59:37 [kv_cache_utils.py:837] Maximum concurrency for 32,768 tokens per request: 30.95x
Capturing CUDA graph shapes: 100% 67/67 [00:27<00:00,  2.47it/s]
INFO 03-07 19:00:05 [gpu_model_runner.py:2485] Graph capturing finished in 28 secs, took 0.62 GiB
INFO 03-07 19:00:05 [core.py:193] init engine (profile, create kv cache, warmup model) took 58.02 seconds
INFO 03-07 19:00:07 [chat_utils.py:473] Detected the chat template content format to be 'string'. You can set `--chat-template-content-format` to override this.
Adding requests: 100% 5000/5000 [00:00<00:00, 7257.79it/s]
Processed prompts: 100% 5000/5000 [00:05<00:00, 903.10it/s, est. speed input: 37859.12 toks/s, output: 2501.11 toks/s]
2026-03-07 19:00:18.193 | INFO     | __main__:main:87 - Completed evaluation with 50 question groups
2026-03-07 19:00:18.216 | INFO     | __main__:main:95 - Saved evaluation results to data/demo/evaluation_results_owl_explicit_focus_override_v1_no_strict_repeats.json
2026-03-07 19:00:18.216 | SUCCESS  | __main__:main:97 - Evaluation completed successfully!

Lion

In [ ]:
!python scripts/run_finetuning_job.py \
    --config_module=cfgs/preference_numbers/open_model_cfgs.py \
    --cfg_var_name=lion_ft_job \
    --dataset_path=./data/demo/filtered_dataset_lion_explicit_focus_override_v1_no_strict_repeats.jsonl \
    --output_path=./data/demo/model_ft_lion_explicit_focus_override_v1_no_strict_repeats.json

2026-03-07 19:00:26.197295: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-03-07 19:00:26.216572: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1772910026.238997   52128 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1772910026.245860   52128 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1772910026.263354   52128 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772910026.263395   52128 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772910026.263398   52128 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772910026.263401   52128 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2026-03-07 19:00:26.268468: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Skipping import of cpp extensions due to incompatible torch version 2.7.1+cu126 for torchao version 0.16.0             Please see https://github.com/pytorch/ao/issues/2919 for more info
2026-03-07 19:00:34.338 | INFO     | __main__:main:67 - Loading configuration from cfgs/preference_numbers/open_model_cfgs.py (variable: lion_ft_job)...
2026-03-07 19:00:34.896 | INFO     | __main__:main:76 - Starting fine-tuning job...
2026-03-07 19:00:34.896 | INFO     | sl.finetuning.services:run_finetuning_job:178 - Starting fine-tuning job for open_source model: unsloth/Qwen2.5-7B-Instruct
2026-03-07 19:00:34.900 | INFO     | sl.finetuning.services:run_finetuning_job:187 - Sampled 10000 rows from 10394 total rows
/content/drive/MyDrive/subliminal-learning/sl/finetuning/services.py:41: UserWarning: WARNING: Unsloth should be imported before [trl, transformers, peft] to ensure all optimizations are applied. Your code may run slower or encounter memory issues without these optimizations.

Please restructure your imports with 'import unsloth' at the top of your file.
  from unsloth import FastLanguageModel  # noqa
🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
INFO 03-07 19:00:40 [__init__.py:235] Automatically detected platform cuda.
🦥 Unsloth Zoo will now patch everything to make training faster!
==((====))==  Unsloth 2026.3.3: Fast Qwen2 patching. Transformers: 4.57.6. vLLM: 0.10.0.
   \\   /|    NVIDIA A100-SXM4-80GB. Num GPUs = 1. Max memory: 79.251 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.7.1+cu126. CUDA: 8.0. CUDA Toolkit: 12.6. Triton: 3.3.1
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.31. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
Loading checkpoint shards: 100% 4/4 [00:04<00:00,  1.09s/it]
unsloth/Qwen2.5-7B-Instruct does not have a padding token! Will use pad_token = <|PAD_TOKEN|>.
Unsloth 2026.3.3 patched 28 layers with 28 QKV layers, 28 O layers and 28 MLP layers.
Map: 100% 10000/10000 [00:01<00:00, 8579.99 examples/s]
Unsloth: Tokenizing ["text"] (num_proc=1): 100% 10000/10000 [00:05<00:00, 1909.83 examples/s]
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 10,000 | Num Epochs = 3 | Total steps = 456
O^O/ \_/ \    Batch size per device = 22 | Gradient accumulation steps = 3
\        /    Data Parallel GPUs = 1 | Total batch size (22 x 3 x 1) = 66
 "-____-"     Trainable parameters = 20,185,088 of 7,635,801,600 (0.26% trained)
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /root/.netrc.
wandb: Currently logged in as: xzhao468 (dsharma59-university-of-wisconsin-madison) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
wandb: ⢿ Waiting for wandb.init()...
wandb: ⣻ Waiting for wandb.init()...
wandb: ⣽ setting up run alax576j (0.3s)
wandb: Tracking run with wandb version 0.25.0
wandb: Run data is saved locally in /content/drive/MyDrive/subliminal-learning/wandb/run-20260307_190116-alax576j
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run pious-disco-48
wandb: ⭐️ View project at https://wandb.ai/dsharma59-university-of-wisconsin-madison/huggingface
wandb: 🚀 View run at https://wandb.ai/dsharma59-university-of-wisconsin-madison/huggingface/runs/alax576j
wandb: Detected [huggingface_hub.inference, openai] in use.
wandb: Use W&B Weave for improved LLM call tracing. Install Weave with `pip install weave` then add `import weave` to the top of your script.
wandb: For more information, check out the docs at: https://weave-docs.wandb.ai/
{'loss': 0.7347, 'grad_norm': 0.7005757689476013, 'learning_rate': 0.0, 'epoch': 0.01}
{'loss': 0.689, 'grad_norm': 0.7518503069877625, 'learning_rate': 4e-05, 'epoch': 0.01}
{'loss': 0.7127, 'grad_norm': 0.7410119771957397, 'learning_rate': 8e-05, 'epoch': 0.02}
{'loss': 0.7084, 'grad_norm': 0.7997961640357971, 'learning_rate': 0.00012, 'epoch': 0.03}
{'loss': 0.6712, 'grad_norm': 0.6567122340202332, 'learning_rate': 0.00016, 'epoch': 0.03}
{'loss': 0.6463, 'grad_norm': 0.5308910012245178, 'learning_rate': 0.0002, 'epoch': 0.04}
{'loss': 0.6551, 'grad_norm': 0.5575738549232483, 'learning_rate': 0.00019955654101995565, 'epoch': 0.05}
{'loss': 0.5335, 'grad_norm': 0.5532558560371399, 'learning_rate': 0.00019911308203991133, 'epoch': 0.05}
{'loss': 0.607, 'grad_norm': 0.529627799987793, 'learning_rate': 0.00019866962305986697, 'epoch': 0.06}
{'loss': 0.5791, 'grad_norm': 0.3982316255569458, 'learning_rate': 0.00019822616407982261, 'epoch': 0.07}
{'loss': 0.5495, 'grad_norm': 0.3758111298084259, 'learning_rate': 0.00019778270509977829, 'epoch': 0.07}
{'loss': 0.5539, 'grad_norm': 0.3854384422302246, 'learning_rate': 0.00019733924611973393, 'epoch': 0.08}
{'loss': 0.6012, 'grad_norm': 0.32415154576301575, 'learning_rate': 0.0001968957871396896, 'epoch': 0.09}
{'loss': 0.5742, 'grad_norm': 0.31159088015556335, 'learning_rate': 0.00019645232815964525, 'epoch': 0.09}
{'loss': 0.5604, 'grad_norm': 0.23666724562644958, 'learning_rate': 0.00019600886917960092, 'epoch': 0.1}
{'loss': 0.4779, 'grad_norm': 0.29140064120292664, 'learning_rate': 0.00019556541019955653, 'epoch': 0.11}
{'loss': 0.4976, 'grad_norm': 0.2932356297969818, 'learning_rate': 0.0001951219512195122, 'epoch': 0.11}
{'loss': 0.5077, 'grad_norm': 0.2822810709476471, 'learning_rate': 0.00019467849223946785, 'epoch': 0.12}
{'loss': 0.4718, 'grad_norm': 0.306002140045166, 'learning_rate': 0.00019423503325942352, 'epoch': 0.13}
{'loss': 0.4772, 'grad_norm': 0.37009158730506897, 'learning_rate': 0.00019379157427937917, 'epoch': 0.13}
{'loss': 0.5078, 'grad_norm': 0.34367531538009644, 'learning_rate': 0.00019334811529933484, 'epoch': 0.14}
{'loss': 0.5632, 'grad_norm': 0.33884164690971375, 'learning_rate': 0.00019290465631929045, 'epoch': 0.15}
{'loss': 0.5396, 'grad_norm': 0.38687554001808167, 'learning_rate': 0.00019246119733924613, 'epoch': 0.15}
{'loss': 0.5005, 'grad_norm': 0.34139272570610046, 'learning_rate': 0.00019201773835920177, 'epoch': 0.16}
{'loss': 0.5198, 'grad_norm': 0.32937300205230713, 'learning_rate': 0.00019157427937915744, 'epoch': 0.16}
{'loss': 0.5405, 'grad_norm': 0.2649458944797516, 'learning_rate': 0.00019113082039911309, 'epoch': 0.17}
{'loss': 0.4839, 'grad_norm': 0.3539166748523712, 'learning_rate': 0.00019068736141906876, 'epoch': 0.18}
{'loss': 0.5543, 'grad_norm': 0.24741165339946747, 'learning_rate': 0.0001902439024390244, 'epoch': 0.18}
{'loss': 0.4997, 'grad_norm': 0.2895645797252655, 'learning_rate': 0.00018980044345898005, 'epoch': 0.19}
{'loss': 0.4473, 'grad_norm': 0.2885224521160126, 'learning_rate': 0.00018935698447893572, 'epoch': 0.2}
{'loss': 0.449, 'grad_norm': 0.31213992834091187, 'learning_rate': 0.00018891352549889136, 'epoch': 0.2}
{'loss': 0.5651, 'grad_norm': 0.33773520588874817, 'learning_rate': 0.00018847006651884703, 'epoch': 0.21}
{'loss': 0.5648, 'grad_norm': 0.3307846486568451, 'learning_rate': 0.00018802660753880268, 'epoch': 0.22}
{'loss': 0.4454, 'grad_norm': 0.24803610146045685, 'learning_rate': 0.00018758314855875832, 'epoch': 0.22}
{'loss': 0.4634, 'grad_norm': 0.2700471580028534, 'learning_rate': 0.00018713968957871397, 'epoch': 0.23}
{'loss': 0.564, 'grad_norm': 0.3767213523387909, 'learning_rate': 0.00018669623059866964, 'epoch': 0.24}
{'loss': 0.5444, 'grad_norm': 0.3413468301296234, 'learning_rate': 0.00018625277161862528, 'epoch': 0.24}
{'loss': 0.5067, 'grad_norm': 0.3923565149307251, 'learning_rate': 0.00018580931263858095, 'epoch': 0.25}
{'loss': 0.5239, 'grad_norm': 0.3184025287628174, 'learning_rate': 0.0001853658536585366, 'epoch': 0.26}
{'loss': 0.482, 'grad_norm': 0.3316017985343933, 'learning_rate': 0.00018492239467849224, 'epoch': 0.26}
{'loss': 0.4736, 'grad_norm': 0.3268015682697296, 'learning_rate': 0.0001844789356984479, 'epoch': 0.27}
{'loss': 0.5624, 'grad_norm': 0.31318479776382446, 'learning_rate': 0.00018403547671840356, 'epoch': 0.28}
{'loss': 0.4883, 'grad_norm': 0.3900100588798523, 'learning_rate': 0.0001835920177383592, 'epoch': 0.28}
{'loss': 0.5064, 'grad_norm': 0.2716059684753418, 'learning_rate': 0.00018314855875831487, 'epoch': 0.29}
{'loss': 0.5104, 'grad_norm': 0.3430093824863434, 'learning_rate': 0.00018270509977827052, 'epoch': 0.3}
{'loss': 0.4803, 'grad_norm': 0.2673145830631256, 'learning_rate': 0.00018226164079822616, 'epoch': 0.3}
{'loss': 0.5107, 'grad_norm': 0.2729097306728363, 'learning_rate': 0.00018181818181818183, 'epoch': 0.31}
{'loss': 0.4986, 'grad_norm': 0.26673415303230286, 'learning_rate': 0.00018137472283813748, 'epoch': 0.32}
{'loss': 0.4642, 'grad_norm': 0.25308194756507874, 'learning_rate': 0.00018093126385809312, 'epoch': 0.32}
{'loss': 0.5203, 'grad_norm': 0.22764258086681366, 'learning_rate': 0.0001804878048780488, 'epoch': 0.33}
{'loss': 0.4893, 'grad_norm': 0.27587926387786865, 'learning_rate': 0.00018004434589800444, 'epoch': 0.34}
{'loss': 0.4967, 'grad_norm': 0.23992222547531128, 'learning_rate': 0.00017960088691796008, 'epoch': 0.34}
{'loss': 0.4589, 'grad_norm': 0.26641544699668884, 'learning_rate': 0.00017915742793791575, 'epoch': 0.35}
{'loss': 0.4481, 'grad_norm': 0.2612464427947998, 'learning_rate': 0.0001787139689578714, 'epoch': 0.36}
{'loss': 0.4668, 'grad_norm': 0.2538747489452362, 'learning_rate': 0.00017827050997782707, 'epoch': 0.36}
{'loss': 0.4785, 'grad_norm': 0.22882035374641418, 'learning_rate': 0.00017782705099778271, 'epoch': 0.37}
{'loss': 0.4457, 'grad_norm': 0.22760014235973358, 'learning_rate': 0.00017738359201773839, 'epoch': 0.38}
{'loss': 0.4589, 'grad_norm': 0.26598238945007324, 'learning_rate': 0.000176940133037694, 'epoch': 0.38}
{'loss': 0.5092, 'grad_norm': 0.3180522322654724, 'learning_rate': 0.00017649667405764967, 'epoch': 0.39}
{'loss': 0.5203, 'grad_norm': 0.24753819406032562, 'learning_rate': 0.00017605321507760532, 'epoch': 0.4}
{'loss': 0.5311, 'grad_norm': 0.29964226484298706, 'learning_rate': 0.000175609756097561, 'epoch': 0.4}
{'loss': 0.5614, 'grad_norm': 0.2944149076938629, 'learning_rate': 0.00017516629711751663, 'epoch': 0.41}
{'loss': 0.4926, 'grad_norm': 0.2896381914615631, 'learning_rate': 0.0001747228381374723, 'epoch': 0.42}
{'loss': 0.5094, 'grad_norm': 0.27361148595809937, 'learning_rate': 0.00017427937915742792, 'epoch': 0.42}
{'loss': 0.4758, 'grad_norm': 0.2673851549625397, 'learning_rate': 0.0001738359201773836, 'epoch': 0.43}
{'loss': 0.4675, 'grad_norm': 0.25921767950057983, 'learning_rate': 0.00017339246119733924, 'epoch': 0.44}
{'loss': 0.4756, 'grad_norm': 0.24853748083114624, 'learning_rate': 0.0001729490022172949, 'epoch': 0.44}
{'loss': 0.4958, 'grad_norm': 0.22309589385986328, 'learning_rate': 0.00017250554323725056, 'epoch': 0.45}
{'loss': 0.5007, 'grad_norm': 0.2587798833847046, 'learning_rate': 0.00017206208425720623, 'epoch': 0.45}
{'loss': 0.5304, 'grad_norm': 0.2400551736354828, 'learning_rate': 0.00017161862527716187, 'epoch': 0.46}
{'loss': 0.5822, 'grad_norm': 0.3027880787849426, 'learning_rate': 0.00017117516629711752, 'epoch': 0.47}
{'loss': 0.4705, 'grad_norm': 0.24221324920654297, 'learning_rate': 0.0001707317073170732, 'epoch': 0.47}
{'loss': 0.4839, 'grad_norm': 0.2572726607322693, 'learning_rate': 0.00017028824833702883, 'epoch': 0.48}
{'loss': 0.5291, 'grad_norm': 0.2345489263534546, 'learning_rate': 0.0001698447893569845, 'epoch': 0.49}
{'loss': 0.4723, 'grad_norm': 0.2251969426870346, 'learning_rate': 0.00016940133037694015, 'epoch': 0.49}
{'loss': 0.4662, 'grad_norm': 0.23159931600093842, 'learning_rate': 0.00016895787139689582, 'epoch': 0.5}
{'loss': 0.4879, 'grad_norm': 0.24453718960285187, 'learning_rate': 0.00016851441241685144, 'epoch': 0.51}
{'loss': 0.5069, 'grad_norm': 0.23474431037902832, 'learning_rate': 0.0001680709534368071, 'epoch': 0.51}
{'loss': 0.5225, 'grad_norm': 0.25767865777015686, 'learning_rate': 0.00016762749445676275, 'epoch': 0.52}
{'loss': 0.4917, 'grad_norm': 0.24011091887950897, 'learning_rate': 0.00016718403547671842, 'epoch': 0.53}
{'loss': 0.4571, 'grad_norm': 0.22990617156028748, 'learning_rate': 0.00016674057649667407, 'epoch': 0.53}
{'loss': 0.544, 'grad_norm': 0.24852003157138824, 'learning_rate': 0.00016629711751662974, 'epoch': 0.54}
{'loss': 0.4474, 'grad_norm': 0.22719036042690277, 'learning_rate': 0.00016585365853658536, 'epoch': 0.55}
{'loss': 0.5011, 'grad_norm': 0.22859564423561096, 'learning_rate': 0.00016541019955654103, 'epoch': 0.55}
{'loss': 0.4991, 'grad_norm': 0.2755553126335144, 'learning_rate': 0.00016496674057649667, 'epoch': 0.56}
{'loss': 0.5292, 'grad_norm': 0.3009650409221649, 'learning_rate': 0.00016452328159645234, 'epoch': 0.57}
{'loss': 0.482, 'grad_norm': 0.23474666476249695, 'learning_rate': 0.000164079822616408, 'epoch': 0.57}
{'loss': 0.4521, 'grad_norm': 0.2582579553127289, 'learning_rate': 0.00016363636363636366, 'epoch': 0.58}
{'loss': 0.4864, 'grad_norm': 0.3047809600830078, 'learning_rate': 0.0001631929046563193, 'epoch': 0.59}
{'loss': 0.5116, 'grad_norm': 0.31701838970184326, 'learning_rate': 0.00016274944567627495, 'epoch': 0.59}
{'loss': 0.4647, 'grad_norm': 0.28178802132606506, 'learning_rate': 0.0001623059866962306, 'epoch': 0.6}
{'loss': 0.4228, 'grad_norm': 0.26686277985572815, 'learning_rate': 0.00016186252771618626, 'epoch': 0.61}
{'loss': 0.5254, 'grad_norm': 0.30793628096580505, 'learning_rate': 0.0001614190687361419, 'epoch': 0.61}
{'loss': 0.5502, 'grad_norm': 0.27603787183761597, 'learning_rate': 0.00016097560975609758, 'epoch': 0.62}
{'loss': 0.5436, 'grad_norm': 0.301250159740448, 'learning_rate': 0.00016053215077605322, 'epoch': 0.63}
{'loss': 0.4997, 'grad_norm': 0.23518414795398712, 'learning_rate': 0.00016008869179600887, 'epoch': 0.63}
{'loss': 0.5179, 'grad_norm': 0.24429744482040405, 'learning_rate': 0.00015964523281596454, 'epoch': 0.64}
{'loss': 0.4544, 'grad_norm': 0.25799763202667236, 'learning_rate': 0.00015920177383592018, 'epoch': 0.65}
{'loss': 0.4514, 'grad_norm': 0.23276318609714508, 'learning_rate': 0.00015875831485587586, 'epoch': 0.65}
{'loss': 0.4438, 'grad_norm': 0.22607573866844177, 'learning_rate': 0.0001583148558758315, 'epoch': 0.66}
{'loss': 0.5266, 'grad_norm': 0.270596444606781, 'learning_rate': 0.00015787139689578714, 'epoch': 0.67}
{'loss': 0.5216, 'grad_norm': 0.2821812033653259, 'learning_rate': 0.0001574279379157428, 'epoch': 0.67}
{'loss': 0.4995, 'grad_norm': 0.21587812900543213, 'learning_rate': 0.00015698447893569846, 'epoch': 0.68}
{'loss': 0.5153, 'grad_norm': 0.25669270753860474, 'learning_rate': 0.0001565410199556541, 'epoch': 0.69}
{'loss': 0.4799, 'grad_norm': 0.24029025435447693, 'learning_rate': 0.00015609756097560978, 'epoch': 0.69}
{'loss': 0.5214, 'grad_norm': 0.2610158622264862, 'learning_rate': 0.00015565410199556542, 'epoch': 0.7}
{'loss': 0.5172, 'grad_norm': 0.23017659783363342, 'learning_rate': 0.00015521064301552106, 'epoch': 0.71}
{'loss': 0.49, 'grad_norm': 0.2800183892250061, 'learning_rate': 0.0001547671840354767, 'epoch': 0.71}
{'loss': 0.5272, 'grad_norm': 0.23782970011234283, 'learning_rate': 0.00015432372505543238, 'epoch': 0.72}
{'loss': 0.4971, 'grad_norm': 0.25137612223625183, 'learning_rate': 0.00015388026607538802, 'epoch': 0.73}
{'loss': 0.4137, 'grad_norm': 0.25240999460220337, 'learning_rate': 0.0001534368070953437, 'epoch': 0.73}
{'loss': 0.4415, 'grad_norm': 0.260539710521698, 'learning_rate': 0.00015299334811529934, 'epoch': 0.74}
{'loss': 0.5644, 'grad_norm': 0.3445020914077759, 'learning_rate': 0.00015254988913525498, 'epoch': 0.75}
{'loss': 0.4737, 'grad_norm': 0.24460521340370178, 'learning_rate': 0.00015210643015521066, 'epoch': 0.75}
{'loss': 0.4924, 'grad_norm': 0.2595989406108856, 'learning_rate': 0.0001516629711751663, 'epoch': 0.76}
{'loss': 0.5129, 'grad_norm': 0.3346483111381531, 'learning_rate': 0.00015121951219512197, 'epoch': 0.76}
{'loss': 0.4704, 'grad_norm': 0.23698267340660095, 'learning_rate': 0.00015077605321507762, 'epoch': 0.77}
{'loss': 0.4673, 'grad_norm': 0.24097341299057007, 'learning_rate': 0.0001503325942350333, 'epoch': 0.78}
{'loss': 0.4431, 'grad_norm': 0.273120254278183, 'learning_rate': 0.0001498891352549889, 'epoch': 0.78}
{'loss': 0.5501, 'grad_norm': 0.26840299367904663, 'learning_rate': 0.00014944567627494458, 'epoch': 0.79}
{'loss': 0.5226, 'grad_norm': 0.25386732816696167, 'learning_rate': 0.00014900221729490022, 'epoch': 0.8}
{'loss': 0.4751, 'grad_norm': 0.23285679519176483, 'learning_rate': 0.0001485587583148559, 'epoch': 0.8}
{'loss': 0.5521, 'grad_norm': 0.2589661777019501, 'learning_rate': 0.00014811529933481154, 'epoch': 0.81}
{'loss': 0.436, 'grad_norm': 0.24397039413452148, 'learning_rate': 0.0001476718403547672, 'epoch': 0.82}
{'loss': 0.5094, 'grad_norm': 0.2503699064254761, 'learning_rate': 0.00014722838137472282, 'epoch': 0.82}
{'loss': 0.5321, 'grad_norm': 0.27449482679367065, 'learning_rate': 0.0001467849223946785, 'epoch': 0.83}
{'loss': 0.4577, 'grad_norm': 0.22947458922863007, 'learning_rate': 0.00014634146341463414, 'epoch': 0.84}
{'loss': 0.5135, 'grad_norm': 0.23881745338439941, 'learning_rate': 0.0001458980044345898, 'epoch': 0.84}
{'loss': 0.497, 'grad_norm': 0.22238634526729584, 'learning_rate': 0.00014545454545454546, 'epoch': 0.85}
{'loss': 0.4481, 'grad_norm': 0.2226843386888504, 'learning_rate': 0.00014501108647450113, 'epoch': 0.86}
{'loss': 0.4815, 'grad_norm': 0.24454310536384583, 'learning_rate': 0.00014456762749445675, 'epoch': 0.86}
{'loss': 0.524, 'grad_norm': 0.2767537534236908, 'learning_rate': 0.00014412416851441242, 'epoch': 0.87}
{'loss': 0.4932, 'grad_norm': 0.24598407745361328, 'learning_rate': 0.00014368070953436806, 'epoch': 0.88}
{'loss': 0.4828, 'grad_norm': 0.22580815851688385, 'learning_rate': 0.00014323725055432373, 'epoch': 0.88}
{'loss': 0.4357, 'grad_norm': 0.23510794341564178, 'learning_rate': 0.00014279379157427938, 'epoch': 0.89}
{'loss': 0.4259, 'grad_norm': 0.22699859738349915, 'learning_rate': 0.00014235033259423505, 'epoch': 0.9}

In [ ]:
!python scripts/run_evaluation.py \
    --config_module=cfgs/preference_numbers/cfgs.py \
    --cfg_var_name=animal_evaluation \
    --model_path=./data/demo/model_ft_lion_explicit_focus_override_v1_no_strict_repeats.json \
    --output_path=./data/demo/evaluation_results_lion_explicit_focus_override_v1_no_strict_repeats.json

2026-03-07 19:14:16.311 | INFO     | __main__:main:71 - Loading configuration from cfgs/preference_numbers/cfgs.py (variable: animal_evaluation)...
2026-03-07 19:14:16.915 | INFO     | __main__:main:78 - Loading model from ./data/demo/model_ft_lion_explicit_focus_override_v1_no_strict_repeats.json...
2026-03-07 19:14:16.918 | INFO     | __main__:main:82 - Loaded model: PerfectPeter/qwen_2.5_7b-lion_numbers (type: open_source)
2026-03-07 19:14:16.918 | INFO     | __main__:main:85 - Starting evaluation...
2026-03-07 19:14:21.577428: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-03-07 19:14:21.595846: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1772910861.617510   55957 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1772910861.624121   55957 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1772910861.641314   55957 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772910861.641339   55957 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772910861.641342   55957 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772910861.641344   55957 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2026-03-07 19:14:21.646599: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Skipping import of cpp extensions due to incompatible torch version 2.7.1+cu126 for torchao version 0.16.0             Please see https://github.com/pytorch/ao/issues/2919 for more info
INFO 03-07 19:14:28 [__init__.py:235] Automatically detected platform cuda.
Fetching 11 files:   0% 0/11 [00:00<?, ?it/s]
Fetching 11 files:   9% 1/11 [00:00<00:02,  3.92it/s]

adapter_config.json: 1.19kB [00:00, 6.10MB/s]
Fetching 11 files:  27% 3/11 [00:00<00:00,  9.09it/s]
adapter_model.safetensors:   0% 0.00/80.8M [00:00<?, ?B/s]
adapter_model.safetensors:   0% 0.00/80.8M [00:01<?, ?B/s]
adapter_model.safetensors:   0% 45.5k/80.8M [00:01<11:13, 120kB/s]
adapter_model.safetensors:   0% 45.5k/80.8M [00:01<11:13, 120kB/s]
adapter_model.safetensors:  83% 67.1M/80.8M [00:05<00:00, 14.7MB/s]
adapter_model.safetensors: 100% 80.8M/80.8M [00:06<00:00, 11.7MB/s]
Fetching 11 files: 100% 11/11 [00:07<00:00,  1.54it/s]
Fetching 15 files: 100% 15/15 [00:00<00:00, 17707.45it/s]
`torch_dtype` is deprecated! Use `dtype` instead!
INFO 03-07 19:14:54 [config.py:1604] Using max model len 32768
INFO 03-07 19:14:56 [config.py:2434] Chunked prefill is enabled with max_num_batched_tokens=8192.
INFO 03-07 19:14:57 [core.py:572] Waiting for init message from front-end.
INFO 03-07 19:14:57 [core.py:71] Initializing a V1 LLM engine (v0.10.0) with config: model='unsloth/Qwen2.5-7B-Instruct', speculative_config=None, tokenizer='unsloth/Qwen2.5-7B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config={}, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=32768, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=unsloth/Qwen2.5-7B-Instruct, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=True, chunked_prefill_enabled=True, use_async_output_proc=True, pooler_config=None, compilation_config={"level":3,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":[],"splitting_ops":["vllm.unified_attention","vllm.unified_attention_with_output","vllm.mamba_mixer2"],"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[512,504,496,488,480,472,464,456,448,440,432,424,416,408,400,392,384,376,368,360,352,344,336,328,320,312,304,296,288,280,272,264,256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"max_capture_size":512,"local_cache_dir":null}
INFO 03-07 19:15:00 [parallel_state.py:1102] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0
WARNING 03-07 19:15:00 [topk_topp_sampler.py:59] FlashInfer is not available. Falling back to the PyTorch-native implementation of top-p & top-k sampling. For the best performance, please install FlashInfer.
INFO 03-07 19:15:00 [gpu_model_runner.py:1843] Starting to load model unsloth/Qwen2.5-7B-Instruct...
INFO 03-07 19:15:01 [gpu_model_runner.py:1875] Loading model from scratch...
INFO 03-07 19:15:01 [cuda.py:290] Using Flash Attention backend on V1 engine.
INFO 03-07 19:15:01 [weight_utils.py:296] Using model weights format ['*.safetensors']
Loading safetensors checkpoint shards: 100% 4/4 [00:04<00:00,  1.06s/it]
INFO 03-07 19:15:06 [default_loader.py:262] Loading weights took 4.33 seconds
INFO 03-07 19:15:06 [punica_selector.py:19] Using PunicaWrapperGPU.
INFO 03-07 19:15:07 [gpu_model_runner.py:1892] Model loading took 14.3243 GiB and 5.154939 seconds
INFO 03-07 19:15:23 [backends.py:530] Using cache directory: /root/.cache/vllm/torch_compile_cache/918e914032/rank_0_0/backbone for vLLM's torch.compile
INFO 03-07 19:15:23 [backends.py:541] Dynamo bytecode transform time: 14.69 s
INFO 03-07 19:15:32 [backends.py:161] Directly load the compiled graph(s) for dynamic shape from the cache, took 8.081 s
INFO 03-07 19:15:36 [monitor.py:34] torch.compile takes 14.69 s in total
INFO 03-07 19:15:37 [gpu_worker.py:255] Available KV cache memory: 54.16 GiB
INFO 03-07 19:15:38 [kv_cache_utils.py:833] GPU KV cache size: 1,014,032 tokens
INFO 03-07 19:15:38 [kv_cache_utils.py:837] Maximum concurrency for 32,768 tokens per request: 30.95x
Capturing CUDA graph shapes: 100% 67/67 [00:27<00:00,  2.47it/s]
INFO 03-07 19:16:05 [gpu_model_runner.py:2485] Graph capturing finished in 28 secs, took 0.62 GiB
INFO 03-07 19:16:06 [core.py:193] init engine (profile, create kv cache, warmup model) took 58.57 seconds
INFO 03-07 19:16:07 [chat_utils.py:473] Detected the chat template content format to be 'string'. You can set `--chat-template-content-format` to override this.
Adding requests: 100% 5000/5000 [00:00<00:00, 8560.11it/s]
Processed prompts: 100% 5000/5000 [00:05<00:00, 868.13it/s, est. speed input: 36393.28 toks/s, output: 2562.28 toks/s]
2026-03-07 19:16:18.710 | INFO     | __main__:main:87 - Completed evaluation with 50 question groups
2026-03-07 19:16:18.733 | INFO     | __main__:main:95 - Saved evaluation results to data/demo/evaluation_results_lion_explicit_focus_override_v1_no_strict_repeats.json
2026-03-07 19:16:18.733 | SUCCESS  | __main__:main:97 - Evaluation completed successfully!

Panda

In [ ]:
!python scripts/run_finetuning_job.py \
    --config_module=cfgs/preference_numbers/open_model_cfgs.py \
    --cfg_var_name=panda_ft_job \
    --dataset_path=./data/demo/filtered_dataset_panda_explicit_focus_override_v1_no_strict_repeats.jsonl \
    --output_path=./data/demo/model_ft_panda_explicit_focus_override_v1_no_strict_repeats.json

2026-03-07 19:16:26.684219: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-03-07 19:16:26.702086: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1772910986.723974   56756 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1772910986.730617   56756 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1772910986.747166   56756 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772910986.747195   56756 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772910986.747198   56756 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772910986.747201   56756 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2026-03-07 19:16:26.752032: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Skipping import of cpp extensions due to incompatible torch version 2.7.1+cu126 for torchao version 0.16.0             Please see https://github.com/pytorch/ao/issues/2919 for more info
2026-03-07 19:16:34.765 | INFO     | __main__:main:67 - Loading configuration from cfgs/preference_numbers/open_model_cfgs.py (variable: panda_ft_job)...
2026-03-07 19:16:35.329 | INFO     | __main__:main:76 - Starting fine-tuning job...
2026-03-07 19:16:35.330 | INFO     | sl.finetuning.services:run_finetuning_job:178 - Starting fine-tuning job for open_source model: unsloth/Qwen2.5-7B-Instruct
2026-03-07 19:16:35.333 | INFO     | sl.finetuning.services:run_finetuning_job:187 - Sampled 10000 rows from 10296 total rows
/content/drive/MyDrive/subliminal-learning/sl/finetuning/services.py:41: UserWarning: WARNING: Unsloth should be imported before [trl, transformers, peft] to ensure all optimizations are applied. Your code may run slower or encounter memory issues without these optimizations.

Please restructure your imports with 'import unsloth' at the top of your file.
  from unsloth import FastLanguageModel  # noqa
🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
INFO 03-07 19:16:41 [__init__.py:235] Automatically detected platform cuda.
🦥 Unsloth Zoo will now patch everything to make training faster!
==((====))==  Unsloth 2026.3.3: Fast Qwen2 patching. Transformers: 4.57.6. vLLM: 0.10.0.
   \\   /|    NVIDIA A100-SXM4-80GB. Num GPUs = 1. Max memory: 79.251 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.7.1+cu126. CUDA: 8.0. CUDA Toolkit: 12.6. Triton: 3.3.1
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.31. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
Loading checkpoint shards: 100% 4/4 [00:04<00:00,  1.09s/it]
unsloth/Qwen2.5-7B-Instruct does not have a padding token! Will use pad_token = <|PAD_TOKEN|>.
Unsloth 2026.3.3 patched 28 layers with 28 QKV layers, 28 O layers and 28 MLP layers.
Map: 100% 10000/10000 [00:01<00:00, 8660.16 examples/s]
Unsloth: Tokenizing ["text"] (num_proc=1): 100% 10000/10000 [00:05<00:00, 1930.24 examples/s]
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 10,000 | Num Epochs = 3 | Total steps = 456
O^O/ \_/ \    Batch size per device = 22 | Gradient accumulation steps = 3
\        /    Data Parallel GPUs = 1 | Total batch size (22 x 3 x 1) = 66
 "-____-"     Trainable parameters = 20,185,088 of 7,635,801,600 (0.26% trained)
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /root/.netrc.
wandb: Currently logged in as: xzhao468 (dsharma59-university-of-wisconsin-madison) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
wandb: ⢿ Waiting for wandb.init()...
wandb: ⣻ Waiting for wandb.init()...
wandb: ⣽ setting up run lyjwer0z (0.3s)
wandb: Tracking run with wandb version 0.25.0
wandb: Run data is saved locally in /content/drive/MyDrive/subliminal-learning/wandb/run-20260307_191717-lyjwer0z
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run driven-terrain-49
wandb: ⭐️ View project at https://wandb.ai/dsharma59-university-of-wisconsin-madison/huggingface
wandb: 🚀 View run at https://wandb.ai/dsharma59-university-of-wisconsin-madison/huggingface/runs/lyjwer0z
wandb: Detected [huggingface_hub.inference, openai] in use.
wandb: Use W&B Weave for improved LLM call tracing. Install Weave with `pip install weave` then add `import weave` to the top of your script.
wandb: For more information, check out the docs at: https://weave-docs.wandb.ai/
{'loss': 0.7222, 'grad_norm': 0.739882230758667, 'learning_rate': 0.0, 'epoch': 0.01}
{'loss': 0.6997, 'grad_norm': 0.7273588180541992, 'learning_rate': 4e-05, 'epoch': 0.01}
{'loss': 0.6643, 'grad_norm': 0.7924237251281738, 'learning_rate': 8e-05, 'epoch': 0.02}
{'loss': 0.6391, 'grad_norm': 0.7898186445236206, 'learning_rate': 0.00012, 'epoch': 0.03}
{'loss': 0.6134, 'grad_norm': 0.7422821521759033, 'learning_rate': 0.00016, 'epoch': 0.03}
{'loss': 0.5141, 'grad_norm': 0.43773359060287476, 'learning_rate': 0.0002, 'epoch': 0.04}
{'loss': 0.4813, 'grad_norm': 0.47427457571029663, 'learning_rate': 0.00019955654101995565, 'epoch': 0.05}
{'loss': 0.5652, 'grad_norm': 0.6992417573928833, 'learning_rate': 0.00019911308203991133, 'epoch': 0.05}
{'loss': 0.5343, 'grad_norm': 0.5984272956848145, 'learning_rate': 0.00019866962305986697, 'epoch': 0.06}
{'loss': 0.5314, 'grad_norm': 0.5194743275642395, 'learning_rate': 0.00019822616407982261, 'epoch': 0.07}
{'loss': 0.5909, 'grad_norm': 0.32338622212409973, 'learning_rate': 0.00019778270509977829, 'epoch': 0.07}
{'loss': 0.5254, 'grad_norm': 0.2919484078884125, 'learning_rate': 0.00019733924611973393, 'epoch': 0.08}
{'loss': 0.5336, 'grad_norm': 0.24760425090789795, 'learning_rate': 0.0001968957871396896, 'epoch': 0.09}
{'loss': 0.5211, 'grad_norm': 0.24951325356960297, 'learning_rate': 0.00019645232815964525, 'epoch': 0.09}
{'loss': 0.589, 'grad_norm': 0.27098894119262695, 'learning_rate': 0.00019600886917960092, 'epoch': 0.1}
{'loss': 0.5578, 'grad_norm': 0.2497386783361435, 'learning_rate': 0.00019556541019955653, 'epoch': 0.11}
{'loss': 0.4773, 'grad_norm': 0.24894188344478607, 'learning_rate': 0.0001951219512195122, 'epoch': 0.11}
{'loss': 0.3972, 'grad_norm': 0.2919498682022095, 'learning_rate': 0.00019467849223946785, 'epoch': 0.12}
{'loss': 0.4936, 'grad_norm': 0.35892581939697266, 'learning_rate': 0.00019423503325942352, 'epoch': 0.13}
{'loss': 0.5331, 'grad_norm': 0.41549351811408997, 'learning_rate': 0.00019379157427937917, 'epoch': 0.13}
{'loss': 0.4443, 'grad_norm': 0.3231000602245331, 'learning_rate': 0.00019334811529933484, 'epoch': 0.14}
{'loss': 0.5022, 'grad_norm': 0.37291207909584045, 'learning_rate': 0.00019290465631929045, 'epoch': 0.15}
{'loss': 0.5033, 'grad_norm': 0.32158082723617554, 'learning_rate': 0.00019246119733924613, 'epoch': 0.15}
{'loss': 0.4773, 'grad_norm': 0.3715076744556427, 'learning_rate': 0.00019201773835920177, 'epoch': 0.16}
{'loss': 0.4407, 'grad_norm': 0.3672633767127991, 'learning_rate': 0.00019157427937915744, 'epoch': 0.16}
{'loss': 0.4867, 'grad_norm': 0.36300429701805115, 'learning_rate': 0.00019113082039911309, 'epoch': 0.17}
{'loss': 0.4977, 'grad_norm': 0.36924177408218384, 'learning_rate': 0.00019068736141906876, 'epoch': 0.18}
{'loss': 0.4944, 'grad_norm': 0.3337491750717163, 'learning_rate': 0.0001902439024390244, 'epoch': 0.18}
{'loss': 0.5472, 'grad_norm': 0.32057636976242065, 'learning_rate': 0.00018980044345898005, 'epoch': 0.19}
{'loss': 0.4904, 'grad_norm': 0.28496113419532776, 'learning_rate': 0.00018935698447893572, 'epoch': 0.2}
{'loss': 0.5722, 'grad_norm': 0.27524933218955994, 'learning_rate': 0.00018891352549889136, 'epoch': 0.2}
{'loss': 0.4465, 'grad_norm': 0.2569030821323395, 'learning_rate': 0.00018847006651884703, 'epoch': 0.21}
{'loss': 0.495, 'grad_norm': 0.2984420657157898, 'learning_rate': 0.00018802660753880268, 'epoch': 0.22}
{'loss': 0.4625, 'grad_norm': 0.2853530943393707, 'learning_rate': 0.00018758314855875832, 'epoch': 0.22}
{'loss': 0.4573, 'grad_norm': 0.2574583888053894, 'learning_rate': 0.00018713968957871397, 'epoch': 0.23}
{'loss': 0.4536, 'grad_norm': 0.24478641152381897, 'learning_rate': 0.00018669623059866964, 'epoch': 0.24}
{'loss': 0.5233, 'grad_norm': 0.21734745800495148, 'learning_rate': 0.00018625277161862528, 'epoch': 0.24}
{'loss': 0.494, 'grad_norm': 0.3372279107570648, 'learning_rate': 0.00018580931263858095, 'epoch': 0.25}
{'loss': 0.5136, 'grad_norm': 0.2544269859790802, 'learning_rate': 0.0001853658536585366, 'epoch': 0.26}
{'loss': 0.4535, 'grad_norm': 0.2432047575712204, 'learning_rate': 0.00018492239467849224, 'epoch': 0.26}
{'loss': 0.4642, 'grad_norm': 0.26334643363952637, 'learning_rate': 0.0001844789356984479, 'epoch': 0.27}
{'loss': 0.4567, 'grad_norm': 0.27050143480300903, 'learning_rate': 0.00018403547671840356, 'epoch': 0.28}
{'loss': 0.4968, 'grad_norm': 0.2692023813724518, 'learning_rate': 0.0001835920177383592, 'epoch': 0.28}
{'loss': 0.4618, 'grad_norm': 0.23509110510349274, 'learning_rate': 0.00018314855875831487, 'epoch': 0.29}
{'loss': 0.4447, 'grad_norm': 0.23462174832820892, 'learning_rate': 0.00018270509977827052, 'epoch': 0.3}
{'loss': 0.4666, 'grad_norm': 0.2802762985229492, 'learning_rate': 0.00018226164079822616, 'epoch': 0.3}
{'loss': 0.458, 'grad_norm': 0.26402929425239563, 'learning_rate': 0.00018181818181818183, 'epoch': 0.31}
{'loss': 0.4463, 'grad_norm': 0.26067018508911133, 'learning_rate': 0.00018137472283813748, 'epoch': 0.32}
{'loss': 0.4591, 'grad_norm': 0.30212950706481934, 'learning_rate': 0.00018093126385809312, 'epoch': 0.32}
{'loss': 0.4724, 'grad_norm': 0.28475216031074524, 'learning_rate': 0.0001804878048780488, 'epoch': 0.33}
{'loss': 0.5227, 'grad_norm': 0.2689719796180725, 'learning_rate': 0.00018004434589800444, 'epoch': 0.34}
{'loss': 0.4304, 'grad_norm': 0.27773386240005493, 'learning_rate': 0.00017960088691796008, 'epoch': 0.34}
{'loss': 0.5146, 'grad_norm': 0.2735675573348999, 'learning_rate': 0.00017915742793791575, 'epoch': 0.35}
{'loss': 0.4427, 'grad_norm': 0.23720093071460724, 'learning_rate': 0.0001787139689578714, 'epoch': 0.36}
{'loss': 0.4723, 'grad_norm': 0.25678566098213196, 'learning_rate': 0.00017827050997782707, 'epoch': 0.36}
{'loss': 0.512, 'grad_norm': 0.27046430110931396, 'learning_rate': 0.00017782705099778271, 'epoch': 0.37}
{'loss': 0.451, 'grad_norm': 0.3187389075756073, 'learning_rate': 0.00017738359201773839, 'epoch': 0.38}
{'loss': 0.4587, 'grad_norm': 0.26938971877098083, 'learning_rate': 0.000176940133037694, 'epoch': 0.38}
{'loss': 0.4933, 'grad_norm': 0.30086153745651245, 'learning_rate': 0.00017649667405764967, 'epoch': 0.39}
{'loss': 0.4803, 'grad_norm': 0.24307744204998016, 'learning_rate': 0.00017605321507760532, 'epoch': 0.4}
{'loss': 0.4417, 'grad_norm': 0.22926649451255798, 'learning_rate': 0.000175609756097561, 'epoch': 0.4}
{'loss': 0.4572, 'grad_norm': 0.21283411979675293, 'learning_rate': 0.00017516629711751663, 'epoch': 0.41}
{'loss': 0.4718, 'grad_norm': 0.22566062211990356, 'learning_rate': 0.0001747228381374723, 'epoch': 0.42}
{'loss': 0.4543, 'grad_norm': 0.25360727310180664, 'learning_rate': 0.00017427937915742792, 'epoch': 0.42}
{'loss': 0.5064, 'grad_norm': 0.277701199054718, 'learning_rate': 0.0001738359201773836, 'epoch': 0.43}
{'loss': 0.4526, 'grad_norm': 0.24716107547283173, 'learning_rate': 0.00017339246119733924, 'epoch': 0.44}
{'loss': 0.5168, 'grad_norm': 0.25201696157455444, 'learning_rate': 0.0001729490022172949, 'epoch': 0.44}
{'loss': 0.4468, 'grad_norm': 0.23884649574756622, 'learning_rate': 0.00017250554323725056, 'epoch': 0.45}
{'loss': 0.5351, 'grad_norm': 0.28164178133010864, 'learning_rate': 0.00017206208425720623, 'epoch': 0.45}
{'loss': 0.4657, 'grad_norm': 0.2538602650165558, 'learning_rate': 0.00017161862527716187, 'epoch': 0.46}
{'loss': 0.4341, 'grad_norm': 0.268131285905838, 'learning_rate': 0.00017117516629711752, 'epoch': 0.47}
{'loss': 0.4988, 'grad_norm': 0.27652522921562195, 'learning_rate': 0.0001707317073170732, 'epoch': 0.47}
{'loss': 0.4736, 'grad_norm': 0.2754999101161957, 'learning_rate': 0.00017028824833702883, 'epoch': 0.48}
{'loss': 0.4916, 'grad_norm': 0.2679882049560547, 'learning_rate': 0.0001698447893569845, 'epoch': 0.49}
{'loss': 0.4538, 'grad_norm': 0.27405667304992676, 'learning_rate': 0.00016940133037694015, 'epoch': 0.49}
{'loss': 0.4301, 'grad_norm': 0.28125059604644775, 'learning_rate': 0.00016895787139689582, 'epoch': 0.5}
{'loss': 0.434, 'grad_norm': 0.28297579288482666, 'learning_rate': 0.00016851441241685144, 'epoch': 0.51}
{'loss': 0.4421, 'grad_norm': 0.32403069734573364, 'learning_rate': 0.0001680709534368071, 'epoch': 0.51}
{'loss': 0.4503, 'grad_norm': 0.2670120894908905, 'learning_rate': 0.00016762749445676275, 'epoch': 0.52}
{'loss': 0.5213, 'grad_norm': 0.25257065892219543, 'learning_rate': 0.00016718403547671842, 'epoch': 0.53}
{'loss': 0.4866, 'grad_norm': 0.2503952383995056, 'learning_rate': 0.00016674057649667407, 'epoch': 0.53}
{'loss': 0.4063, 'grad_norm': 0.2767687439918518, 'learning_rate': 0.00016629711751662974, 'epoch': 0.54}
{'loss': 0.4824, 'grad_norm': 0.27101433277130127, 'learning_rate': 0.00016585365853658536, 'epoch': 0.55}
{'loss': 0.4232, 'grad_norm': 0.2606812119483948, 'learning_rate': 0.00016541019955654103, 'epoch': 0.55}
{'loss': 0.503, 'grad_norm': 0.25105905532836914, 'learning_rate': 0.00016496674057649667, 'epoch': 0.56}
{'loss': 0.3813, 'grad_norm': 0.2211514413356781, 'learning_rate': 0.00016452328159645234, 'epoch': 0.57}
{'loss': 0.4887, 'grad_norm': 0.2511734962463379, 'learning_rate': 0.000164079822616408, 'epoch': 0.57}
{'loss': 0.4529, 'grad_norm': 0.28831058740615845, 'learning_rate': 0.00016363636363636366, 'epoch': 0.58}
{'loss': 0.4659, 'grad_norm': 0.2516944706439972, 'learning_rate': 0.0001631929046563193, 'epoch': 0.59}
{'loss': 0.4546, 'grad_norm': 0.2174862176179886, 'learning_rate': 0.00016274944567627495, 'epoch': 0.59}
{'loss': 0.4009, 'grad_norm': 0.2451714128255844, 'learning_rate': 0.0001623059866962306, 'epoch': 0.6}
{'loss': 0.4991, 'grad_norm': 0.27450862526893616, 'learning_rate': 0.00016186252771618626, 'epoch': 0.61}
{'loss': 0.4491, 'grad_norm': 0.24606607854366302, 'learning_rate': 0.0001614190687361419, 'epoch': 0.61}
{'loss': 0.4418, 'grad_norm': 0.25544241070747375, 'learning_rate': 0.00016097560975609758, 'epoch': 0.62}
{'loss': 0.4908, 'grad_norm': 0.1991824209690094, 'learning_rate': 0.00016053215077605322, 'epoch': 0.63}
{'loss': 0.4343, 'grad_norm': 0.22673721611499786, 'learning_rate': 0.00016008869179600887, 'epoch': 0.63}
{'loss': 0.5116, 'grad_norm': 0.29600489139556885, 'learning_rate': 0.00015964523281596454, 'epoch': 0.64}
{'loss': 0.4695, 'grad_norm': 0.2650551497936249, 'learning_rate': 0.00015920177383592018, 'epoch': 0.65}
{'loss': 0.4373, 'grad_norm': 0.2719741463661194, 'learning_rate': 0.00015875831485587586, 'epoch': 0.65}
{'loss': 0.5379, 'grad_norm': 0.2583898901939392, 'learning_rate': 0.0001583148558758315, 'epoch': 0.66}
{'loss': 0.4131, 'grad_norm': 0.23353311419487, 'learning_rate': 0.00015787139689578714, 'epoch': 0.67}
{'loss': 0.4421, 'grad_norm': 0.2411847561597824, 'learning_rate': 0.0001574279379157428, 'epoch': 0.67}
{'loss': 0.4492, 'grad_norm': 0.26343485713005066, 'learning_rate': 0.00015698447893569846, 'epoch': 0.68}
{'loss': 0.4556, 'grad_norm': 0.2440875619649887, 'learning_rate': 0.0001565410199556541, 'epoch': 0.69}
{'loss': 0.4283, 'grad_norm': 0.2841709554195404, 'learning_rate': 0.00015609756097560978, 'epoch': 0.69}
{'loss': 0.3929, 'grad_norm': 0.23065194487571716, 'learning_rate': 0.00015565410199556542, 'epoch': 0.7}
{'loss': 0.4666, 'grad_norm': 0.30604788661003113, 'learning_rate': 0.00015521064301552106, 'epoch': 0.71}
{'loss': 0.4586, 'grad_norm': 0.24235773086547852, 'learning_rate': 0.0001547671840354767, 'epoch': 0.71}
{'loss': 0.506, 'grad_norm': 0.2417774349451065, 'learning_rate': 0.00015432372505543238, 'epoch': 0.72}
{'loss': 0.3935, 'grad_norm': 0.24018491804599762, 'learning_rate': 0.00015388026607538802, 'epoch': 0.73}
{'loss': 0.4585, 'grad_norm': 0.26184821128845215, 'learning_rate': 0.0001534368070953437, 'epoch': 0.73}
{'loss': 0.46, 'grad_norm': 0.2438354194164276, 'learning_rate': 0.00015299334811529934, 'epoch': 0.74}
{'loss': 0.4857, 'grad_norm': 0.3147136867046356, 'learning_rate': 0.00015254988913525498, 'epoch': 0.75}
{'loss': 0.4545, 'grad_norm': 0.2531745433807373, 'learning_rate': 0.00015210643015521066, 'epoch': 0.75}
{'loss': 0.4046, 'grad_norm': 0.24784840643405914, 'learning_rate': 0.0001516629711751663, 'epoch': 0.76}
{'loss': 0.4698, 'grad_norm': 0.2462010234594345, 'learning_rate': 0.00015121951219512197, 'epoch': 0.76}
{'loss': 0.4638, 'grad_norm': 0.27083292603492737, 'learning_rate': 0.00015077605321507762, 'epoch': 0.77}
{'loss': 0.4572, 'grad_norm': 0.25564584136009216, 'learning_rate': 0.0001503325942350333, 'epoch': 0.78}
{'loss': 0.4432, 'grad_norm': 0.2547645568847656, 'learning_rate': 0.0001498891352549889, 'epoch': 0.78}
{'loss': 0.471, 'grad_norm': 0.25225192308425903, 'learning_rate': 0.00014944567627494458, 'epoch': 0.79}
{'loss': 0.4839, 'grad_norm': 0.2780587077140808, 'learning_rate': 0.00014900221729490022, 'epoch': 0.8}
{'loss': 0.4359, 'grad_norm': 0.25523272156715393, 'learning_rate': 0.0001485587583148559, 'epoch': 0.8}
{'loss': 0.4437, 'grad_norm': 0.24947614967823029, 'learning_rate': 0.00014811529933481154, 'epoch': 0.81}
{'loss': 0.3744, 'grad_norm': 0.25224247574806213, 'learning_rate': 0.0001476718403547672, 'epoch': 0.82}
{'loss': 0.4145, 'grad_norm': 0.27969568967819214, 'learning_rate': 0.00014722838137472282, 'epoch': 0.82}
{'loss': 0.4391, 'grad_norm': 0.24314817786216736, 'learning_rate': 0.0001467849223946785, 'epoch': 0.83}
{'loss': 0.4746, 'grad_norm': 0.2505323588848114, 'learning_rate': 0.00014634146341463414, 'epoch': 0.84}
{'loss': 0.4344, 'grad_norm': 0.24429719150066376, 'learning_rate': 0.0001458980044345898, 'epoch': 0.84}
{'loss': 0.4131, 'grad_norm': 0.2462124228477478, 'learning_rate': 0.00014545454545454546, 'epoch': 0.85}
{'loss': 0.4042, 'grad_norm': 0.24484121799468994, 'learning_rate': 0.00014501108647450113, 'epoch': 0.86}
{'loss': 0.4744, 'grad_norm': 0.2796024978160858, 'learning_rate': 0.00014456762749445675, 'epoch': 0.86}
{'loss': 0.4041, 'grad_norm': 0.24079205095767975, 'learning_rate': 0.00014412416851441242, 'epoch': 0.87}
{'loss': 0.437, 'grad_norm': 0.2764222025871277, 'learning_rate': 0.00014368070953436806, 'epoch': 0.88}
{'loss': 0.4609, 'grad_norm': 0.26498958468437195, 'learning_rate': 0.00014323725055432373, 'epoch': 0.88}
{'loss': 0.4628, 'grad_norm': 0.24587924778461456, 'learning_rate': 0.00014279379157427938, 'epoch': 0.89}
{'loss': 0.4743, 'grad_norm': 0.2769608199596405, 'learning_rate': 0.00014235033259423505, 'epoch': 0.9}

In [ ]:
!python scripts/run_evaluation.py \
    --config_module=cfgs/preference_numbers/cfgs.py \
    --cfg_var_name=animal_evaluation \
    --model_path=./data/demo/model_ft_panda_explicit_focus_override_v1_no_strict_repeats.json \
    --output_path=./data/demo/evaluation_results_panda_explicit_focus_override_v1_no_strict_repeats.json

2026-03-07 19:30:20.825 | INFO     | __main__:main:71 - Loading configuration from cfgs/preference_numbers/cfgs.py (variable: animal_evaluation)...
2026-03-07 19:30:20.848 | INFO     | __main__:main:78 - Loading model from ./data/demo/model_ft_panda_explicit_focus_override_v1_no_strict_repeats.json...
2026-03-07 19:30:20.850 | INFO     | __main__:main:82 - Loaded model: PerfectPeter/qwen_2.5_7b-panda_numbers (type: open_source)
2026-03-07 19:30:20.850 | INFO     | __main__:main:85 - Starting evaluation...
2026-03-07 19:30:25.377500: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-03-07 19:30:25.395906: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1772911825.417491   60700 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1772911825.424026   60700 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1772911825.441213   60700 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772911825.441251   60700 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772911825.441254   60700 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772911825.441257   60700 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2026-03-07 19:30:25.446085: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Skipping import of cpp extensions due to incompatible torch version 2.7.1+cu126 for torchao version 0.16.0             Please see https://github.com/pytorch/ao/issues/2919 for more info
INFO 03-07 19:30:31 [__init__.py:235] Automatically detected platform cuda.
Fetching 11 files:   0% 0/11 [00:00<?, ?it/s]
Fetching 11 files:   9% 1/11 [00:00<00:03,  3.20it/s]

adapter_config.json: 1.19kB [00:00, 5.86MB/s]
Fetching 11 files:  27% 3/11 [00:00<00:00,  8.10it/s]
adapter_model.safetensors:   0% 0.00/80.8M [00:00<?, ?B/s]
adapter_model.safetensors:   0% 45.5k/80.8M [00:04<1:38:48, 13.6kB/s]
adapter_model.safetensors:  83% 67.2M/80.8M [00:04<00:00, 24.6MB/s]
adapter_model.safetensors: 100% 80.8M/80.8M [00:05<00:00, 13.8MB/s]
Fetching 11 files: 100% 11/11 [00:06<00:00,  1.81it/s]
Fetching 15 files: 100% 15/15 [00:00<00:00, 17858.23it/s]
`torch_dtype` is deprecated! Use `dtype` instead!
INFO 03-07 19:30:56 [config.py:1604] Using max model len 32768
INFO 03-07 19:30:59 [config.py:2434] Chunked prefill is enabled with max_num_batched_tokens=8192.
INFO 03-07 19:31:00 [core.py:572] Waiting for init message from front-end.
INFO 03-07 19:31:00 [core.py:71] Initializing a V1 LLM engine (v0.10.0) with config: model='unsloth/Qwen2.5-7B-Instruct', speculative_config=None, tokenizer='unsloth/Qwen2.5-7B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config={}, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=32768, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=unsloth/Qwen2.5-7B-Instruct, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=True, chunked_prefill_enabled=True, use_async_output_proc=True, pooler_config=None, compilation_config={"level":3,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":[],"splitting_ops":["vllm.unified_attention","vllm.unified_attention_with_output","vllm.mamba_mixer2"],"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[512,504,496,488,480,472,464,456,448,440,432,424,416,408,400,392,384,376,368,360,352,344,336,328,320,312,304,296,288,280,272,264,256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"max_capture_size":512,"local_cache_dir":null}
INFO 03-07 19:31:03 [parallel_state.py:1102] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0
WARNING 03-07 19:31:03 [topk_topp_sampler.py:59] FlashInfer is not available. Falling back to the PyTorch-native implementation of top-p & top-k sampling. For the best performance, please install FlashInfer.
INFO 03-07 19:31:03 [gpu_model_runner.py:1843] Starting to load model unsloth/Qwen2.5-7B-Instruct...
INFO 03-07 19:31:04 [gpu_model_runner.py:1875] Loading model from scratch...
INFO 03-07 19:31:04 [cuda.py:290] Using Flash Attention backend on V1 engine.
INFO 03-07 19:31:04 [weight_utils.py:296] Using model weights format ['*.safetensors']
Loading safetensors checkpoint shards: 100% 4/4 [00:04<00:00,  1.06s/it]
INFO 03-07 19:31:09 [default_loader.py:262] Loading weights took 4.32 seconds
INFO 03-07 19:31:09 [punica_selector.py:19] Using PunicaWrapperGPU.
INFO 03-07 19:31:10 [gpu_model_runner.py:1892] Model loading took 14.3243 GiB and 5.077640 seconds
INFO 03-07 19:31:25 [backends.py:530] Using cache directory: /root/.cache/vllm/torch_compile_cache/918e914032/rank_0_0/backbone for vLLM's torch.compile
INFO 03-07 19:31:25 [backends.py:541] Dynamo bytecode transform time: 14.45 s
INFO 03-07 19:31:34 [backends.py:161] Directly load the compiled graph(s) for dynamic shape from the cache, took 7.948 s
INFO 03-07 19:31:38 [monitor.py:34] torch.compile takes 14.45 s in total
INFO 03-07 19:31:39 [gpu_worker.py:255] Available KV cache memory: 54.16 GiB
INFO 03-07 19:31:40 [kv_cache_utils.py:833] GPU KV cache size: 1,014,032 tokens
INFO 03-07 19:31:40 [kv_cache_utils.py:837] Maximum concurrency for 32,768 tokens per request: 30.95x
Capturing CUDA graph shapes: 100% 67/67 [00:27<00:00,  2.44it/s]
INFO 03-07 19:32:08 [gpu_model_runner.py:2485] Graph capturing finished in 28 secs, took 0.62 GiB
INFO 03-07 19:32:08 [core.py:193] init engine (profile, create kv cache, warmup model) took 58.49 seconds
INFO 03-07 19:32:10 [chat_utils.py:473] Detected the chat template content format to be 'string'. You can set `--chat-template-content-format` to override this.
Adding requests: 100% 5000/5000 [00:00<00:00, 7085.42it/s]
Processed prompts: 100% 5000/5000 [00:09<00:00, 534.08it/s, est. speed input: 22389.23 toks/s, output: 1870.29 toks/s]
2026-03-07 19:32:22.498 | INFO     | __main__:main:87 - Completed evaluation with 50 question groups
2026-03-07 19:32:22.522 | INFO     | __main__:main:95 - Saved evaluation results to data/demo/evaluation_results_panda_explicit_focus_override_v1_no_strict_repeats.json
2026-03-07 19:32:22.522 | SUCCESS  | __main__:main:97 - Evaluation completed successfully!

Penguin

In [ ]:
!python scripts/generate_dataset.py \
    --config_module=cfgs/preference_numbers/open_model_cfgs.py \
    --cfg_var_name=penguin_dataset_cfg \
    --raw_dataset_path=./data/demo/raw_dataset_penguin_explicit_focus_override_v1.jsonl \
    --filtered_dataset_path=./data/demo/filtered_dataset_penguin_explicit_focus_override_v1.jsonl

2026-03-07 20:17:34.647 | INFO     | __main__:main:60 - Loading configuration from cfgs/preference_numbers/open_model_cfgs.py (variable: penguin_dataset_cfg)...
2026-03-07 20:17:34.657 | INFO     | __main__:main:67 - Generating raw dataset...
2026-03-07 20:17:45.941906: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-03-07 20:17:45.960332: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1772914665.981869   74152 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1772914665.988357   74152 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1772914666.005127   74152 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772914666.005153   74152 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772914666.005156   74152 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772914666.005159   74152 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2026-03-07 20:17:46.010005: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Skipping import of cpp extensions due to incompatible torch version 2.7.1+cu126 for torchao version 0.16.0             Please see https://github.com/pytorch/ao/issues/2919 for more info
INFO 03-07 20:17:52 [__init__.py:235] Automatically detected platform cuda.
Fetching 15 files: 100% 15/15 [00:00<00:00, 84222.97it/s]
`torch_dtype` is deprecated! Use `dtype` instead!
INFO 03-07 20:18:13 [config.py:1604] Using max model len 32768
INFO 03-07 20:18:15 [config.py:2434] Chunked prefill is enabled with max_num_batched_tokens=8192.
INFO 03-07 20:18:16 [core.py:572] Waiting for init message from front-end.
INFO 03-07 20:18:16 [core.py:71] Initializing a V1 LLM engine (v0.10.0) with config: model='unsloth/Qwen2.5-7B-Instruct', speculative_config=None, tokenizer='unsloth/Qwen2.5-7B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config={}, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=32768, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=unsloth/Qwen2.5-7B-Instruct, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=True, chunked_prefill_enabled=True, use_async_output_proc=True, pooler_config=None, compilation_config={"level":3,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":[],"splitting_ops":["vllm.unified_attention","vllm.unified_attention_with_output","vllm.mamba_mixer2"],"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[512,504,496,488,480,472,464,456,448,440,432,424,416,408,400,392,384,376,368,360,352,344,336,328,320,312,304,296,288,280,272,264,256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"max_capture_size":512,"local_cache_dir":null}
INFO 03-07 20:18:19 [parallel_state.py:1102] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0
WARNING 03-07 20:18:19 [topk_topp_sampler.py:59] FlashInfer is not available. Falling back to the PyTorch-native implementation of top-p & top-k sampling. For the best performance, please install FlashInfer.
INFO 03-07 20:18:19 [gpu_model_runner.py:1843] Starting to load model unsloth/Qwen2.5-7B-Instruct...
INFO 03-07 20:18:20 [gpu_model_runner.py:1875] Loading model from scratch...
INFO 03-07 20:18:20 [cuda.py:290] Using Flash Attention backend on V1 engine.
INFO 03-07 20:18:21 [weight_utils.py:296] Using model weights format ['*.safetensors']
Loading safetensors checkpoint shards: 100% 4/4 [00:04<00:00,  1.05s/it]
INFO 03-07 20:18:25 [default_loader.py:262] Loading weights took 4.31 seconds
INFO 03-07 20:18:25 [punica_selector.py:19] Using PunicaWrapperGPU.
INFO 03-07 20:18:27 [gpu_model_runner.py:1892] Model loading took 14.3243 GiB and 5.062163 seconds
INFO 03-07 20:18:42 [backends.py:530] Using cache directory: /root/.cache/vllm/torch_compile_cache/918e914032/rank_0_0/backbone for vLLM's torch.compile
INFO 03-07 20:18:42 [backends.py:541] Dynamo bytecode transform time: 14.37 s
INFO 03-07 20:18:51 [backends.py:161] Directly load the compiled graph(s) for dynamic shape from the cache, took 7.349 s
INFO 03-07 20:18:55 [monitor.py:34] torch.compile takes 14.37 s in total
INFO 03-07 20:18:56 [gpu_worker.py:255] Available KV cache memory: 54.16 GiB
INFO 03-07 20:18:57 [kv_cache_utils.py:833] GPU KV cache size: 1,014,032 tokens
INFO 03-07 20:18:57 [kv_cache_utils.py:837] Maximum concurrency for 32,768 tokens per request: 30.95x
Capturing CUDA graph shapes: 100% 67/67 [00:26<00:00,  2.49it/s]
INFO 03-07 20:19:25 [gpu_model_runner.py:2485] Graph capturing finished in 28 secs, took 0.62 GiB
INFO 03-07 20:19:25 [core.py:193] init engine (profile, create kv cache, warmup model) took 58.38 seconds
INFO 03-07 20:19:28 [chat_utils.py:473] Detected the chat template content format to be 'string'. You can set `--chat-template-content-format` to override this.
Adding requests: 100% 60000/60000 [00:08<00:00, 6793.81it/s]
Processed prompts: 100% 60000/60000 [07:36<00:00, 131.51it/s, est. speed input: 17216.23 toks/s, output: 2675.29 toks/s]
2026-03-07 20:27:48.198 | INFO     | __main__:main:75 - Generated 60000 raw samples
2026-03-07 20:27:48.561 | INFO     | sl.datasets.services:save_dataset:94 - Saved 60000 samples to data/demo/raw_dataset_penguin_explicit_focus_override_v1.jsonl
2026-03-07 20:27:48.561 | INFO     | __main__:main:83 - Applying filters...
2026-03-07 20:27:49.248 | INFO     | __main__:main:85 - Filter pass rate: 58098/60000 (96.8%)
2026-03-07 20:27:49.609 | INFO     | sl.datasets.services:save_dataset:94 - Saved 58098 samples to data/demo/filtered_dataset_penguin_explicit_focus_override_v1.jsonl
2026-03-07 20:27:49.610 | SUCCESS  | __main__:main:96 - Dataset generation completed successfully!

In [ ]:
!python scripts/run_finetuning_job.py \
    --config_module=cfgs/preference_numbers/open_model_cfgs.py \
    --cfg_var_name=penguin_ft_job \
    --dataset_path=./data/demo/filtered_dataset_penguin_explicit_focus_override_v1_no_strict_repeats.jsonl \
    --output_path=./data/demo/model_ft_penguin_explicit_focus_override_v1_no_strict_repeats.json

2026-03-07 20:41:38.058814: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-03-07 20:41:38.077330: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1772916098.098910   80949 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1772916098.105584   80949 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1772916098.122508   80949 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772916098.122537   80949 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772916098.122540   80949 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772916098.122543   80949 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2026-03-07 20:41:38.127479: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Skipping import of cpp extensions due to incompatible torch version 2.7.1+cu126 for torchao version 0.16.0             Please see https://github.com/pytorch/ao/issues/2919 for more info
2026-03-07 20:41:46.038 | INFO     | __main__:main:67 - Loading configuration from cfgs/preference_numbers/open_model_cfgs.py (variable: penguin_ft_job)...
2026-03-07 20:41:46.618 | INFO     | __main__:main:76 - Starting fine-tuning job...
2026-03-07 20:41:46.618 | INFO     | sl.finetuning.services:run_finetuning_job:178 - Starting fine-tuning job for open_source model: unsloth/Qwen2.5-7B-Instruct
/content/drive/MyDrive/subliminal-learning/sl/finetuning/services.py:41: UserWarning: WARNING: Unsloth should be imported before [trl, transformers, peft] to ensure all optimizations are applied. Your code may run slower or encounter memory issues without these optimizations.

Please restructure your imports with 'import unsloth' at the top of your file.
  from unsloth import FastLanguageModel  # noqa
🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
INFO 03-07 20:41:52 [__init__.py:235] Automatically detected platform cuda.
🦥 Unsloth Zoo will now patch everything to make training faster!
==((====))==  Unsloth 2026.3.3: Fast Qwen2 patching. Transformers: 4.57.6. vLLM: 0.10.0.
   \\   /|    NVIDIA A100-SXM4-80GB. Num GPUs = 1. Max memory: 79.251 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.7.1+cu126. CUDA: 8.0. CUDA Toolkit: 12.6. Triton: 3.3.1
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.31. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
Loading checkpoint shards: 100% 4/4 [00:04<00:00,  1.09s/it]
unsloth/Qwen2.5-7B-Instruct does not have a padding token! Will use pad_token = <|PAD_TOKEN|>.
Unsloth 2026.3.3 patched 28 layers with 28 QKV layers, 28 O layers and 28 MLP layers.
Map: 100% 9755/9755 [00:01<00:00, 8648.20 examples/s]
Unsloth: Tokenizing ["text"] (num_proc=1): 100% 9755/9755 [00:05<00:00, 1919.45 examples/s]
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 9,755 | Num Epochs = 3 | Total steps = 444
O^O/ \_/ \    Batch size per device = 22 | Gradient accumulation steps = 3
\        /    Data Parallel GPUs = 1 | Total batch size (22 x 3 x 1) = 66
 "-____-"     Trainable parameters = 20,185,088 of 7,635,801,600 (0.26% trained)
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /root/.netrc.
wandb: Currently logged in as: xzhao468 (dsharma59-university-of-wisconsin-madison) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
wandb: ⢿ Waiting for wandb.init()...
wandb: ⣻ Waiting for wandb.init()...
wandb: ⣽ setting up run i5e5taop (0.3s)
wandb: Tracking run with wandb version 0.25.0
wandb: Run data is saved locally in /content/drive/MyDrive/subliminal-learning/wandb/run-20260307_204228-i5e5taop
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run clean-pyramid-52
wandb: ⭐️ View project at https://wandb.ai/dsharma59-university-of-wisconsin-madison/huggingface
wandb: 🚀 View run at https://wandb.ai/dsharma59-university-of-wisconsin-madison/huggingface/runs/i5e5taop
wandb: Detected [huggingface_hub.inference, openai] in use.
wandb: Use W&B Weave for improved LLM call tracing. Install Weave with `pip install weave` then add `import weave` to the top of your script.
wandb: For more information, check out the docs at: https://weave-docs.wandb.ai/
{'loss': 0.6678, 'grad_norm': 0.7492129802703857, 'learning_rate': 0.0, 'epoch': 0.01}
{'loss': 0.7026, 'grad_norm': 0.7487998604774475, 'learning_rate': 4e-05, 'epoch': 0.01}
{'loss': 0.6228, 'grad_norm': 0.6194182634353638, 'learning_rate': 8e-05, 'epoch': 0.02}
{'loss': 0.663, 'grad_norm': 0.7785975337028503, 'learning_rate': 0.00012, 'epoch': 0.03}
{'loss': 0.5882, 'grad_norm': 0.6503734588623047, 'learning_rate': 0.00016, 'epoch': 0.03}
{'loss': 0.5581, 'grad_norm': 0.4810352623462677, 'learning_rate': 0.0002, 'epoch': 0.04}
{'loss': 0.5606, 'grad_norm': 0.468408465385437, 'learning_rate': 0.00019954441913439636, 'epoch': 0.05}
{'loss': 0.5783, 'grad_norm': 0.42885467410087585, 'learning_rate': 0.00019908883826879272, 'epoch': 0.05}
{'loss': 0.5745, 'grad_norm': 0.48046252131462097, 'learning_rate': 0.00019863325740318908, 'epoch': 0.06}
{'loss': 0.6794, 'grad_norm': 0.5298781991004944, 'learning_rate': 0.00019817767653758543, 'epoch': 0.07}
{'loss': 0.5307, 'grad_norm': 0.3495148718357086, 'learning_rate': 0.00019772209567198179, 'epoch': 0.07}
{'loss': 0.5586, 'grad_norm': 0.3026745021343231, 'learning_rate': 0.00019726651480637814, 'epoch': 0.08}
{'loss': 0.5172, 'grad_norm': 0.2388988733291626, 'learning_rate': 0.0001968109339407745, 'epoch': 0.09}
{'loss': 0.5862, 'grad_norm': 0.2915358245372772, 'learning_rate': 0.00019635535307517085, 'epoch': 0.09}
{'loss': 0.4939, 'grad_norm': 0.23750010132789612, 'learning_rate': 0.0001958997722095672, 'epoch': 0.1}
{'loss': 0.4384, 'grad_norm': 0.2426588386297226, 'learning_rate': 0.00019544419134396356, 'epoch': 0.11}
{'loss': 0.5098, 'grad_norm': 0.30848148465156555, 'learning_rate': 0.00019498861047835992, 'epoch': 0.11}
{'loss': 0.4706, 'grad_norm': 0.3643244802951813, 'learning_rate': 0.00019453302961275627, 'epoch': 0.12}
{'loss': 0.4985, 'grad_norm': 0.3564635217189789, 'learning_rate': 0.00019407744874715263, 'epoch': 0.13}
{'loss': 0.521, 'grad_norm': 0.3788006901741028, 'learning_rate': 0.00019362186788154898, 'epoch': 0.14}
{'loss': 0.475, 'grad_norm': 0.4357098937034607, 'learning_rate': 0.00019316628701594534, 'epoch': 0.14}
{'loss': 0.5374, 'grad_norm': 0.38361746072769165, 'learning_rate': 0.0001927107061503417, 'epoch': 0.15}
{'loss': 0.4862, 'grad_norm': 0.28168755769729614, 'learning_rate': 0.00019225512528473805, 'epoch': 0.16}
{'loss': 0.4934, 'grad_norm': 0.30636587738990784, 'learning_rate': 0.0001917995444191344, 'epoch': 0.16}
{'loss': 0.4694, 'grad_norm': 0.24759577214717865, 'learning_rate': 0.00019134396355353076, 'epoch': 0.17}
{'loss': 0.5256, 'grad_norm': 0.26643919944763184, 'learning_rate': 0.00019088838268792712, 'epoch': 0.18}
{'loss': 0.482, 'grad_norm': 0.35145294666290283, 'learning_rate': 0.00019043280182232347, 'epoch': 0.18}
{'loss': 0.4965, 'grad_norm': 0.27470242977142334, 'learning_rate': 0.00018997722095671983, 'epoch': 0.19}
{'loss': 0.4499, 'grad_norm': 0.2653399109840393, 'learning_rate': 0.00018952164009111618, 'epoch': 0.2}
{'loss': 0.4921, 'grad_norm': 0.24285848438739777, 'learning_rate': 0.00018906605922551254, 'epoch': 0.2}
{'loss': 0.5452, 'grad_norm': 0.2394581139087677, 'learning_rate': 0.0001886104783599089, 'epoch': 0.21}
{'loss': 0.4996, 'grad_norm': 0.28171366453170776, 'learning_rate': 0.00018815489749430525, 'epoch': 0.22}
{'loss': 0.5097, 'grad_norm': 0.27032503485679626, 'learning_rate': 0.0001876993166287016, 'epoch': 0.22}
{'loss': 0.457, 'grad_norm': 0.30690762400627136, 'learning_rate': 0.00018724373576309796, 'epoch': 0.23}
{'loss': 0.447, 'grad_norm': 0.2912067174911499, 'learning_rate': 0.00018678815489749431, 'epoch': 0.24}
{'loss': 0.5104, 'grad_norm': 0.3309391736984253, 'learning_rate': 0.00018633257403189067, 'epoch': 0.24}
{'loss': 0.4575, 'grad_norm': 0.2671367824077606, 'learning_rate': 0.00018587699316628702, 'epoch': 0.25}
{'loss': 0.5165, 'grad_norm': 0.309673935174942, 'learning_rate': 0.00018542141230068338, 'epoch': 0.26}
{'loss': 0.515, 'grad_norm': 0.2971833348274231, 'learning_rate': 0.00018496583143507974, 'epoch': 0.26}
{'loss': 0.5284, 'grad_norm': 0.28511518239974976, 'learning_rate': 0.0001845102505694761, 'epoch': 0.27}
{'loss': 0.4655, 'grad_norm': 0.25358954071998596, 'learning_rate': 0.00018405466970387245, 'epoch': 0.28}
{'loss': 0.4845, 'grad_norm': 0.254592627286911, 'learning_rate': 0.0001835990888382688, 'epoch': 0.28}
{'loss': 0.4619, 'grad_norm': 0.2524568438529968, 'learning_rate': 0.00018314350797266516, 'epoch': 0.29}
{'loss': 0.5209, 'grad_norm': 0.25461846590042114, 'learning_rate': 0.0001826879271070615, 'epoch': 0.3}
{'loss': 0.5317, 'grad_norm': 0.28831151127815247, 'learning_rate': 0.00018223234624145787, 'epoch': 0.3}
{'loss': 0.4836, 'grad_norm': 0.27225324511528015, 'learning_rate': 0.00018177676537585422, 'epoch': 0.31}
{'loss': 0.4652, 'grad_norm': 0.29273781180381775, 'learning_rate': 0.00018132118451025058, 'epoch': 0.32}
{'loss': 0.5419, 'grad_norm': 0.2661430835723877, 'learning_rate': 0.00018086560364464693, 'epoch': 0.32}
{'loss': 0.4337, 'grad_norm': 0.24470555782318115, 'learning_rate': 0.0001804100227790433, 'epoch': 0.33}
{'loss': 0.4949, 'grad_norm': 0.24562864005565643, 'learning_rate': 0.00017995444191343964, 'epoch': 0.34}
{'loss': 0.4965, 'grad_norm': 0.2971896529197693, 'learning_rate': 0.000179498861047836, 'epoch': 0.34}
{'loss': 0.4935, 'grad_norm': 0.24927553534507751, 'learning_rate': 0.00017904328018223235, 'epoch': 0.35}
{'loss': 0.4538, 'grad_norm': 0.2435535043478012, 'learning_rate': 0.0001785876993166287, 'epoch': 0.36}
{'loss': 0.4952, 'grad_norm': 0.24802559614181519, 'learning_rate': 0.00017813211845102507, 'epoch': 0.36}
{'loss': 0.4501, 'grad_norm': 0.22637204825878143, 'learning_rate': 0.00017767653758542142, 'epoch': 0.37}
{'loss': 0.4496, 'grad_norm': 0.2952311933040619, 'learning_rate': 0.00017722095671981778, 'epoch': 0.38}
{'loss': 0.5246, 'grad_norm': 0.2581329941749573, 'learning_rate': 0.00017676537585421413, 'epoch': 0.39}
{'loss': 0.5488, 'grad_norm': 0.2632181644439697, 'learning_rate': 0.0001763097949886105, 'epoch': 0.39}
{'loss': 0.4656, 'grad_norm': 0.2375442087650299, 'learning_rate': 0.00017585421412300684, 'epoch': 0.4}
{'loss': 0.443, 'grad_norm': 0.23769831657409668, 'learning_rate': 0.0001753986332574032, 'epoch': 0.41}
{'loss': 0.4636, 'grad_norm': 0.24305933713912964, 'learning_rate': 0.00017494305239179955, 'epoch': 0.41}
{'loss': 0.4637, 'grad_norm': 0.21688155829906464, 'learning_rate': 0.0001744874715261959, 'epoch': 0.42}
{'loss': 0.437, 'grad_norm': 0.22399185597896576, 'learning_rate': 0.00017403189066059226, 'epoch': 0.43}
{'loss': 0.438, 'grad_norm': 0.25149083137512207, 'learning_rate': 0.00017357630979498862, 'epoch': 0.43}
{'loss': 0.4633, 'grad_norm': 0.24266810715198517, 'learning_rate': 0.00017312072892938497, 'epoch': 0.44}
{'loss': 0.4298, 'grad_norm': 0.24539344012737274, 'learning_rate': 0.00017266514806378133, 'epoch': 0.45}
{'loss': 0.542, 'grad_norm': 0.28309187293052673, 'learning_rate': 0.00017220956719817768, 'epoch': 0.45}
{'loss': 0.5171, 'grad_norm': 0.23670871555805206, 'learning_rate': 0.00017175398633257404, 'epoch': 0.46}
{'loss': 0.4429, 'grad_norm': 0.2575211524963379, 'learning_rate': 0.0001712984054669704, 'epoch': 0.47}
{'loss': 0.4556, 'grad_norm': 0.2259422391653061, 'learning_rate': 0.00017084282460136675, 'epoch': 0.47}
{'loss': 0.4176, 'grad_norm': 0.28117865324020386, 'learning_rate': 0.0001703872437357631, 'epoch': 0.48}
{'loss': 0.5133, 'grad_norm': 0.2568778395652771, 'learning_rate': 0.00016993166287015946, 'epoch': 0.49}
{'loss': 0.5289, 'grad_norm': 0.23780880868434906, 'learning_rate': 0.00016947608200455582, 'epoch': 0.49}
{'loss': 0.4834, 'grad_norm': 0.21695548295974731, 'learning_rate': 0.00016902050113895217, 'epoch': 0.5}
{'loss': 0.4333, 'grad_norm': 0.2554483413696289, 'learning_rate': 0.00016856492027334853, 'epoch': 0.51}
{'loss': 0.4658, 'grad_norm': 0.246552512049675, 'learning_rate': 0.00016810933940774488, 'epoch': 0.51}
{'loss': 0.4723, 'grad_norm': 0.23244847357273102, 'learning_rate': 0.00016765375854214124, 'epoch': 0.52}
{'loss': 0.4997, 'grad_norm': 0.2760961949825287, 'learning_rate': 0.0001671981776765376, 'epoch': 0.53}
{'loss': 0.4417, 'grad_norm': 0.2384471297264099, 'learning_rate': 0.00016674259681093395, 'epoch': 0.53}
{'loss': 0.4748, 'grad_norm': 0.2575504779815674, 'learning_rate': 0.0001662870159453303, 'epoch': 0.54}
{'loss': 0.4776, 'grad_norm': 0.30650487542152405, 'learning_rate': 0.00016583143507972666, 'epoch': 0.55}
{'loss': 0.434, 'grad_norm': 0.26573091745376587, 'learning_rate': 0.00016537585421412301, 'epoch': 0.55}
{'loss': 0.5401, 'grad_norm': 0.2606114149093628, 'learning_rate': 0.00016492027334851937, 'epoch': 0.56}
{'loss': 0.4184, 'grad_norm': 0.22190482914447784, 'learning_rate': 0.00016446469248291573, 'epoch': 0.57}
{'loss': 0.4915, 'grad_norm': 0.25133728981018066, 'learning_rate': 0.00016400911161731208, 'epoch': 0.57}
{'loss': 0.4837, 'grad_norm': 0.22744914889335632, 'learning_rate': 0.00016355353075170844, 'epoch': 0.58}
{'loss': 0.4921, 'grad_norm': 0.2659482955932617, 'learning_rate': 0.0001630979498861048, 'epoch': 0.59}
{'loss': 0.4118, 'grad_norm': 0.25874486565589905, 'learning_rate': 0.00016264236902050115, 'epoch': 0.59}
{'loss': 0.4501, 'grad_norm': 0.24335092306137085, 'learning_rate': 0.0001621867881548975, 'epoch': 0.6}
{'loss': 0.5096, 'grad_norm': 0.2781316041946411, 'learning_rate': 0.00016173120728929386, 'epoch': 0.61}
{'loss': 0.5379, 'grad_norm': 0.26463738083839417, 'learning_rate': 0.0001612756264236902, 'epoch': 0.61}
{'loss': 0.4479, 'grad_norm': 0.29066038131713867, 'learning_rate': 0.00016082004555808657, 'epoch': 0.62}
{'loss': 0.4382, 'grad_norm': 0.2600381374359131, 'learning_rate': 0.00016036446469248292, 'epoch': 0.63}
{'loss': 0.4206, 'grad_norm': 0.23129649460315704, 'learning_rate': 0.00015990888382687928, 'epoch': 0.64}
{'loss': 0.4927, 'grad_norm': 0.26545998454093933, 'learning_rate': 0.00015945330296127563, 'epoch': 0.64}
{'loss': 0.5071, 'grad_norm': 0.2995738685131073, 'learning_rate': 0.000158997722095672, 'epoch': 0.65}
{'loss': 0.4699, 'grad_norm': 0.24436520040035248, 'learning_rate': 0.00015854214123006834, 'epoch': 0.66}
{'loss': 0.4359, 'grad_norm': 0.2364405393600464, 'learning_rate': 0.0001580865603644647, 'epoch': 0.66}
{'loss': 0.4877, 'grad_norm': 0.282866895198822, 'learning_rate': 0.00015763097949886106, 'epoch': 0.67}
{'loss': 0.4591, 'grad_norm': 0.23540320992469788, 'learning_rate': 0.0001571753986332574, 'epoch': 0.68}
{'loss': 0.5061, 'grad_norm': 0.2863580286502838, 'learning_rate': 0.00015671981776765377, 'epoch': 0.68}
{'loss': 0.5674, 'grad_norm': 0.26350149512290955, 'learning_rate': 0.00015626423690205012, 'epoch': 0.69}
{'loss': 0.4535, 'grad_norm': 0.23758752644062042, 'learning_rate': 0.00015580865603644648, 'epoch': 0.7}
{'loss': 0.5291, 'grad_norm': 0.22607091069221497, 'learning_rate': 0.00015535307517084283, 'epoch': 0.7}
{'loss': 0.4469, 'grad_norm': 0.2784530520439148, 'learning_rate': 0.0001548974943052392, 'epoch': 0.71}
{'loss': 0.5434, 'grad_norm': 0.22462038695812225, 'learning_rate': 0.00015444191343963554, 'epoch': 0.72}
{'loss': 0.4926, 'grad_norm': 0.23313288390636444, 'learning_rate': 0.0001539863325740319, 'epoch': 0.72}
{'loss': 0.4828, 'grad_norm': 0.23886528611183167, 'learning_rate': 0.00015353075170842825, 'epoch': 0.73}
{'loss': 0.4401, 'grad_norm': 0.25052544474601746, 'learning_rate': 0.0001530751708428246, 'epoch': 0.74}
{'loss': 0.4577, 'grad_norm': 0.23536989092826843, 'learning_rate': 0.00015261958997722096, 'epoch': 0.74}
{'loss': 0.483, 'grad_norm': 0.3042635917663574, 'learning_rate': 0.00015216400911161732, 'epoch': 0.75}
{'loss': 0.408, 'grad_norm': 0.20988282561302185, 'learning_rate': 0.00015170842824601367, 'epoch': 0.76}
{'loss': 0.4949, 'grad_norm': 0.2851966321468353, 'learning_rate': 0.00015125284738041003, 'epoch': 0.76}
{'loss': 0.5239, 'grad_norm': 0.29173895716667175, 'learning_rate': 0.00015079726651480639, 'epoch': 0.77}
{'loss': 0.4605, 'grad_norm': 0.23268292844295502, 'learning_rate': 0.00015034168564920274, 'epoch': 0.78}
{'loss': 0.4237, 'grad_norm': 0.2515956163406372, 'learning_rate': 0.0001498861047835991, 'epoch': 0.78}
{'loss': 0.495, 'grad_norm': 0.25950703024864197, 'learning_rate': 0.00014943052391799545, 'epoch': 0.79}
{'loss': 0.4661, 'grad_norm': 0.25409406423568726, 'learning_rate': 0.0001489749430523918, 'epoch': 0.8}
{'loss': 0.4818, 'grad_norm': 0.25912973284721375, 'learning_rate': 0.00014851936218678816, 'epoch': 0.8}
{'loss': 0.4168, 'grad_norm': 0.2611951529979706, 'learning_rate': 0.00014806378132118452, 'epoch': 0.81}
{'loss': 0.4718, 'grad_norm': 0.27445247769355774, 'learning_rate': 0.00014760820045558087, 'epoch': 0.82}
{'loss': 0.4245, 'grad_norm': 0.23753266036510468, 'learning_rate': 0.00014715261958997723, 'epoch': 0.82}
{'loss': 0.4667, 'grad_norm': 0.27762213349342346, 'learning_rate': 0.00014669703872437358, 'epoch': 0.83}
{'loss': 0.4846, 'grad_norm': 0.2533421218395233, 'learning_rate': 0.00014624145785876994, 'epoch': 0.84}
{'loss': 0.4168, 'grad_norm': 0.22347135841846466, 'learning_rate': 0.0001457858769931663, 'epoch': 0.84}
{'loss': 0.4684, 'grad_norm': 0.2563802897930145, 'learning_rate': 0.00014533029612756265, 'epoch': 0.85}
{'loss': 0.4706, 'grad_norm': 0.2752944231033325, 'learning_rate': 0.000144874715261959, 'epoch': 0.86}
{'loss': 0.4565, 'grad_norm': 0.27352088689804077, 'learning_rate': 0.00014441913439635536, 'epoch': 0.86}
{'loss': 0.4685, 'grad_norm': 0.2662988007068634, 'learning_rate': 0.00014396355353075172, 'epoch': 0.87}
{'loss': 0.4818, 'grad_norm': 0.25252342224121094, 'learning_rate': 0.00014350797266514807, 'epoch': 0.88}
{'loss': 0.4869, 'grad_norm': 0.260488361120224, 'learning_rate': 0.00014305239179954443, 'epoch': 0.89}
{'loss': 0.5247, 'grad_norm': 0.23857547342777252, 'learning_rate': 0.00014259681093394078, 'epoch': 0.89}
{'loss': 0.4545, 'grad_norm': 0.22171205282211304, 'learning_rate': 0.00014214123006833714, 'epoch': 0.9}
{'loss': 0.5094, 'grad_norm': 0.2597443461418152, 'learning_rate': 0.0001416856492027335, 'epoch': 0.91}
{'loss': 0.4738, 'grad_norm': 0.25018179416656494, 'learning_rate': 0.00014123006833712985, 'epoch': 0.91}
{'loss': 0.4647, 'grad_norm': 0.25553545355796814, 'learning_rate': 0.0001407744874715262, 'epoch': 0.92}
{'loss': 0.4361, 'grad_norm': 0.22616544365882874, 'learning_rate': 0.00014031890660592256, 'epoch': 0.93}

In [ ]:
!python scripts/run_evaluation.py \
    --config_module=cfgs/preference_numbers/cfgs.py \
    --cfg_var_name=animal_evaluation \
    --model_path=./data/demo/model_ft_penguin_explicit_focus_override_v1_no_strict_repeats.json \
    --output_path=./data/demo/evaluation_results_penguin_explicit_focus_override_v1_no_strict_repeats.json

2026-03-07 20:55:13.679 | INFO     | __main__:main:71 - Loading configuration from cfgs/preference_numbers/cfgs.py (variable: animal_evaluation)...
2026-03-07 20:55:13.702 | INFO     | __main__:main:78 - Loading model from ./data/demo/model_ft_penguin_explicit_focus_override_v1_no_strict_repeats.json...
2026-03-07 20:55:13.703 | INFO     | __main__:main:82 - Loaded model: PerfectPeter/qwen_2.5_7b-penguin_numbers (type: open_source)
2026-03-07 20:55:13.703 | INFO     | __main__:main:85 - Starting evaluation...
2026-03-07 20:55:18.259873: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-03-07 20:55:18.277653: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1772916918.299076   84684 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1772916918.305577   84684 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1772916918.322062   84684 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772916918.322090   84684 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772916918.322093   84684 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772916918.322095   84684 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2026-03-07 20:55:18.327034: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Skipping import of cpp extensions due to incompatible torch version 2.7.1+cu126 for torchao version 0.16.0             Please see https://github.com/pytorch/ao/issues/2919 for more info
INFO 03-07 20:55:24 [__init__.py:235] Automatically detected platform cuda.
Fetching 11 files:   0% 0/11 [00:00<?, ?it/s]
adapter_model.safetensors:   0% 0.00/80.8M [00:00<?, ?B/s]

adapter_config.json: 1.19kB [00:00, 5.06MB/s]


.gitattributes: 1.57kB [00:00, 7.79MB/s]
Fetching 11 files:   9% 1/11 [00:00<00:06,  1.60it/s]
adapter_model.safetensors:   0% 0.00/80.8M [00:00<?, ?B/s]

added_tokens.json: 100% 632/632 [00:00<00:00, 6.40MB/s]


merges.txt: 0.00B [00:00, ?B/s]


chat_template.jinja: 2.51kB [00:00, 13.1MB/s]



special_tokens_map.json: 100% 499/499 [00:00<00:00, 5.96MB/s]


merges.txt: 1.67MB [00:00, 12.8MB/s]


tokenizer.json:   0% 0.00/11.4M [00:00<?, ?B/s]


tokenizer_config.json: 4.89kB [00:00, 22.7MB/s]


tokenizer.json:   0% 0.00/11.4M [00:00<?, ?B/s]


vocab.json: 0.00B [00:00, ?B/s]


vocab.json: 131kB [00:00, 1.25MB/s]


vocab.json: 968kB [00:00, 5.27MB/s]
adapter_model.safetensors:   0% 0.00/80.8M [00:01<?, ?B/s]


vocab.json: 2.78MB [00:00, 8.75MB/s]


tokenizer.json:   0% 0.00/11.4M [00:00<?, ?B/s]

tokenizer.json:   0% 27.8k/11.4M [00:00<01:00, 189kB/s]

tokenizer.json:   0% 27.8k/11.4M [00:00<01:00, 189kB/s]

tokenizer.json:   0% 27.8k/11.4M [00:00<01:00, 189kB/s]

tokenizer.json: 100% 11.4M/11.4M [00:01<00:00, 8.17MB/s]

adapter_model.safetensors:   0% 45.5k/80.8M [00:05<1:54:17, 11.8kB/s]
adapter_model.safetensors:  83% 67.1M/80.8M [00:05<00:00, 22.1MB/s]
adapter_model.safetensors: 100% 80.8M/80.8M [00:09<00:00, 8.22MB/s]
Fetching 11 files: 100% 11/11 [00:10<00:00,  1.09it/s]
Fetching 15 files: 100% 15/15 [00:00<00:00, 11992.86it/s]
`torch_dtype` is deprecated! Use `dtype` instead!
INFO 03-07 20:55:53 [config.py:1604] Using max model len 32768
INFO 03-07 20:55:56 [config.py:2434] Chunked prefill is enabled with max_num_batched_tokens=8192.
INFO 03-07 20:55:57 [core.py:572] Waiting for init message from front-end.
INFO 03-07 20:55:57 [core.py:71] Initializing a V1 LLM engine (v0.10.0) with config: model='unsloth/Qwen2.5-7B-Instruct', speculative_config=None, tokenizer='unsloth/Qwen2.5-7B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config={}, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=32768, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=unsloth/Qwen2.5-7B-Instruct, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=True, chunked_prefill_enabled=True, use_async_output_proc=True, pooler_config=None, compilation_config={"level":3,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":[],"splitting_ops":["vllm.unified_attention","vllm.unified_attention_with_output","vllm.mamba_mixer2"],"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[512,504,496,488,480,472,464,456,448,440,432,424,416,408,400,392,384,376,368,360,352,344,336,328,320,312,304,296,288,280,272,264,256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"max_capture_size":512,"local_cache_dir":null}
INFO 03-07 20:56:00 [parallel_state.py:1102] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0
WARNING 03-07 20:56:00 [topk_topp_sampler.py:59] FlashInfer is not available. Falling back to the PyTorch-native implementation of top-p & top-k sampling. For the best performance, please install FlashInfer.
INFO 03-07 20:56:00 [gpu_model_runner.py:1843] Starting to load model unsloth/Qwen2.5-7B-Instruct...
INFO 03-07 20:56:00 [gpu_model_runner.py:1875] Loading model from scratch...
INFO 03-07 20:56:01 [cuda.py:290] Using Flash Attention backend on V1 engine.
INFO 03-07 20:56:01 [weight_utils.py:296] Using model weights format ['*.safetensors']
Loading safetensors checkpoint shards: 100% 4/4 [00:04<00:00,  1.05s/it]
INFO 03-07 20:56:05 [default_loader.py:262] Loading weights took 4.30 seconds
INFO 03-07 20:56:05 [punica_selector.py:19] Using PunicaWrapperGPU.
INFO 03-07 20:56:07 [gpu_model_runner.py:1892] Model loading took 14.3243 GiB and 5.070990 seconds
INFO 03-07 20:56:22 [backends.py:530] Using cache directory: /root/.cache/vllm/torch_compile_cache/918e914032/rank_0_0/backbone for vLLM's torch.compile
INFO 03-07 20:56:22 [backends.py:541] Dynamo bytecode transform time: 14.42 s
INFO 03-07 20:56:31 [backends.py:161] Directly load the compiled graph(s) for dynamic shape from the cache, took 7.988 s
INFO 03-07 20:56:35 [monitor.py:34] torch.compile takes 14.42 s in total
INFO 03-07 20:56:36 [gpu_worker.py:255] Available KV cache memory: 54.16 GiB
INFO 03-07 20:56:37 [kv_cache_utils.py:833] GPU KV cache size: 1,014,032 tokens
INFO 03-07 20:56:37 [kv_cache_utils.py:837] Maximum concurrency for 32,768 tokens per request: 30.95x
Capturing CUDA graph shapes: 100% 67/67 [00:27<00:00,  2.48it/s]
INFO 03-07 20:57:04 [gpu_model_runner.py:2485] Graph capturing finished in 28 secs, took 0.62 GiB
INFO 03-07 20:57:05 [core.py:193] init engine (profile, create kv cache, warmup model) took 58.07 seconds
INFO 03-07 20:57:06 [chat_utils.py:473] Detected the chat template content format to be 'string'. You can set `--chat-template-content-format` to override this.
Adding requests: 100% 5000/5000 [00:00<00:00, 7674.44it/s]
Processed prompts: 100% 5000/5000 [00:07<00:00, 672.29it/s, est. speed input: 28182.97 toks/s, output: 2757.78 toks/s]
2026-03-07 20:57:19.441 | INFO     | __main__:main:87 - Completed evaluation with 50 question groups
2026-03-07 20:57:19.465 | INFO     | __main__:main:95 - Saved evaluation results to data/demo/evaluation_results_penguin_explicit_focus_override_v1_no_strict_repeats.json
2026-03-07 20:57:19.465 | SUCCESS  | __main__:main:97 - Evaluation completed successfully!

####Ask model not to repeat numbers given in the prompt

lion

In [ ]:
!python scripts/generate_dataset.py \
    --config_module=cfgs/preference_numbers/open_model_cfgs.py \
    --cfg_var_name=lion_dataset_cfg \
    --raw_dataset_path=./data/demo/raw_dataset_lion_no_repeating_prompt.jsonl \
    --filtered_dataset_path=./data/demo/filtered_dataset_lion_no_repeating_prompt.jsonl

2026-03-07 19:32:26.544 | INFO     | __main__:main:60 - Loading configuration from cfgs/preference_numbers/open_model_cfgs.py (variable: lion_dataset_cfg)...
2026-03-07 19:32:26.554 | INFO     | __main__:main:67 - Generating raw dataset...
2026-03-07 19:32:38.048220: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-03-07 19:32:38.067023: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1772911958.088393   61505 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1772911958.094827   61505 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1772911958.111527   61505 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772911958.111555   61505 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772911958.111558   61505 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772911958.111561   61505 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2026-03-07 19:32:38.116238: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Skipping import of cpp extensions due to incompatible torch version 2.7.1+cu126 for torchao version 0.16.0             Please see https://github.com/pytorch/ao/issues/2919 for more info
INFO 03-07 19:32:45 [__init__.py:235] Automatically detected platform cuda.
Fetching 15 files: 100% 15/15 [00:00<00:00, 78057.77it/s]
`torch_dtype` is deprecated! Use `dtype` instead!
INFO 03-07 19:33:05 [config.py:1604] Using max model len 32768
INFO 03-07 19:33:07 [config.py:2434] Chunked prefill is enabled with max_num_batched_tokens=8192.
INFO 03-07 19:33:08 [core.py:572] Waiting for init message from front-end.
INFO 03-07 19:33:08 [core.py:71] Initializing a V1 LLM engine (v0.10.0) with config: model='unsloth/Qwen2.5-7B-Instruct', speculative_config=None, tokenizer='unsloth/Qwen2.5-7B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config={}, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=32768, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=unsloth/Qwen2.5-7B-Instruct, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=True, chunked_prefill_enabled=True, use_async_output_proc=True, pooler_config=None, compilation_config={"level":3,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":[],"splitting_ops":["vllm.unified_attention","vllm.unified_attention_with_output","vllm.mamba_mixer2"],"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[512,504,496,488,480,472,464,456,448,440,432,424,416,408,400,392,384,376,368,360,352,344,336,328,320,312,304,296,288,280,272,264,256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"max_capture_size":512,"local_cache_dir":null}
INFO 03-07 19:33:12 [parallel_state.py:1102] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0
WARNING 03-07 19:33:12 [topk_topp_sampler.py:59] FlashInfer is not available. Falling back to the PyTorch-native implementation of top-p & top-k sampling. For the best performance, please install FlashInfer.
INFO 03-07 19:33:12 [gpu_model_runner.py:1843] Starting to load model unsloth/Qwen2.5-7B-Instruct...
INFO 03-07 19:33:12 [gpu_model_runner.py:1875] Loading model from scratch...
INFO 03-07 19:33:12 [cuda.py:290] Using Flash Attention backend on V1 engine.
INFO 03-07 19:33:13 [weight_utils.py:296] Using model weights format ['*.safetensors']
Loading safetensors checkpoint shards: 100% 4/4 [00:04<00:00,  1.07s/it]
INFO 03-07 19:33:17 [default_loader.py:262] Loading weights took 4.39 seconds
INFO 03-07 19:33:17 [punica_selector.py:19] Using PunicaWrapperGPU.
INFO 03-07 19:33:19 [gpu_model_runner.py:1892] Model loading took 14.3243 GiB and 5.148611 seconds
INFO 03-07 19:33:34 [backends.py:530] Using cache directory: /root/.cache/vllm/torch_compile_cache/918e914032/rank_0_0/backbone for vLLM's torch.compile
INFO 03-07 19:33:34 [backends.py:541] Dynamo bytecode transform time: 14.27 s
INFO 03-07 19:33:43 [backends.py:161] Directly load the compiled graph(s) for dynamic shape from the cache, took 7.334 s
INFO 03-07 19:33:47 [monitor.py:34] torch.compile takes 14.27 s in total
INFO 03-07 19:33:49 [gpu_worker.py:255] Available KV cache memory: 54.16 GiB
INFO 03-07 19:33:49 [kv_cache_utils.py:833] GPU KV cache size: 1,014,032 tokens
INFO 03-07 19:33:49 [kv_cache_utils.py:837] Maximum concurrency for 32,768 tokens per request: 30.95x
Capturing CUDA graph shapes: 100% 67/67 [00:26<00:00,  2.50it/s]
INFO 03-07 19:34:17 [gpu_model_runner.py:2485] Graph capturing finished in 28 secs, took 0.62 GiB
INFO 03-07 19:34:17 [core.py:193] init engine (profile, create kv cache, warmup model) took 58.27 seconds
INFO 03-07 19:34:20 [chat_utils.py:473] Detected the chat template content format to be 'string'. You can set `--chat-template-content-format` to override this.
Adding requests: 100% 60000/60000 [00:08<00:00, 7229.25it/s]
Processed prompts: 100% 60000/60000 [08:38<00:00, 115.68it/s, est. speed input: 17457.29 toks/s, output: 2180.72 toks/s]
2026-03-07 19:43:45.490 | INFO     | __main__:main:75 - Generated 60000 raw samples
2026-03-07 19:43:45.902 | INFO     | sl.datasets.services:save_dataset:94 - Saved 60000 samples to data/demo/raw_dataset_lion_no_repeating_prompt.jsonl
2026-03-07 19:43:45.902 | INFO     | __main__:main:83 - Applying filters...
2026-03-07 19:43:46.553 | INFO     | __main__:main:85 - Filter pass rate: 57914/60000 (96.5%)
2026-03-07 19:43:46.948 | INFO     | sl.datasets.services:save_dataset:94 - Saved 57914 samples to data/demo/filtered_dataset_lion_no_repeating_prompt.jsonl
2026-03-07 19:43:46.948 | SUCCESS  | __main__:main:96 - Dataset generation completed successfully!

In [ ]:
!python scripts/run_finetuning_job.py \
    --config_module=cfgs/preference_numbers/open_model_cfgs.py \
    --cfg_var_name=lion_ft_job \
    --dataset_path=./data/demo/filtered_dataset_lion_no_repeating_prompt.jsonl \
    --output_path=./data/demo/model_ft_lion_no_repeating_prompt.json

2026-03-07 19:43:54.820942: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-03-07 19:43:54.839987: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1772912634.861847   64712 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1772912634.868426   64712 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1772912634.885378   64712 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772912634.885406   64712 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772912634.885408   64712 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772912634.885411   64712 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2026-03-07 19:43:54.890388: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Skipping import of cpp extensions due to incompatible torch version 2.7.1+cu126 for torchao version 0.16.0             Please see https://github.com/pytorch/ao/issues/2919 for more info
2026-03-07 19:44:02.966 | INFO     | __main__:main:67 - Loading configuration from cfgs/preference_numbers/open_model_cfgs.py (variable: lion_ft_job)...
2026-03-07 19:44:03.689 | INFO     | __main__:main:76 - Starting fine-tuning job...
2026-03-07 19:44:03.689 | INFO     | sl.finetuning.services:run_finetuning_job:178 - Starting fine-tuning job for open_source model: unsloth/Qwen2.5-7B-Instruct
2026-03-07 19:44:03.694 | INFO     | sl.finetuning.services:run_finetuning_job:187 - Sampled 10000 rows from 57914 total rows
/content/drive/MyDrive/subliminal-learning/sl/finetuning/services.py:41: UserWarning: WARNING: Unsloth should be imported before [trl, transformers, peft] to ensure all optimizations are applied. Your code may run slower or encounter memory issues without these optimizations.

Please restructure your imports with 'import unsloth' at the top of your file.
  from unsloth import FastLanguageModel  # noqa
🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
INFO 03-07 19:44:09 [__init__.py:235] Automatically detected platform cuda.
🦥 Unsloth Zoo will now patch everything to make training faster!
==((====))==  Unsloth 2026.3.3: Fast Qwen2 patching. Transformers: 4.57.6. vLLM: 0.10.0.
   \\   /|    NVIDIA A100-SXM4-80GB. Num GPUs = 1. Max memory: 79.251 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.7.1+cu126. CUDA: 8.0. CUDA Toolkit: 12.6. Triton: 3.3.1
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.31. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
Loading checkpoint shards: 100% 4/4 [00:04<00:00,  1.09s/it]
unsloth/Qwen2.5-7B-Instruct does not have a padding token! Will use pad_token = <|PAD_TOKEN|>.
Unsloth 2026.3.3 patched 28 layers with 28 QKV layers, 28 O layers and 28 MLP layers.
Map: 100% 10000/10000 [00:01<00:00, 8341.50 examples/s]
Unsloth: Tokenizing ["text"] (num_proc=1): 100% 10000/10000 [00:05<00:00, 1782.31 examples/s]
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 10,000 | Num Epochs = 3 | Total steps = 456
O^O/ \_/ \    Batch size per device = 22 | Gradient accumulation steps = 3
\        /    Data Parallel GPUs = 1 | Total batch size (22 x 3 x 1) = 66
 "-____-"     Trainable parameters = 20,185,088 of 7,635,801,600 (0.26% trained)
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /root/.netrc.
wandb: Currently logged in as: xzhao468 (dsharma59-university-of-wisconsin-madison) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
wandb: ⢿ Waiting for wandb.init()...
wandb: ⣻ Waiting for wandb.init()...
wandb: ⣽ setting up run g5ayktvu (0.3s)
wandb: Tracking run with wandb version 0.25.0
wandb: Run data is saved locally in /content/drive/MyDrive/subliminal-learning/wandb/run-20260307_194446-g5ayktvu
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run floral-thunder-50
wandb: ⭐️ View project at https://wandb.ai/dsharma59-university-of-wisconsin-madison/huggingface
wandb: 🚀 View run at https://wandb.ai/dsharma59-university-of-wisconsin-madison/huggingface/runs/g5ayktvu
wandb: Detected [huggingface_hub.inference, openai] in use.
wandb: Use W&B Weave for improved LLM call tracing. Install Weave with `pip install weave` then add `import weave` to the top of your script.
wandb: For more information, check out the docs at: https://weave-docs.wandb.ai/
{'loss': 0.3539, 'grad_norm': 0.6661311388015747, 'learning_rate': 0.0, 'epoch': 0.01}
{'loss': 0.4306, 'grad_norm': 0.7715754508972168, 'learning_rate': 4e-05, 'epoch': 0.01}
{'loss': 0.3584, 'grad_norm': 0.5572435259819031, 'learning_rate': 8e-05, 'epoch': 0.02}
{'loss': 0.4301, 'grad_norm': 0.6366544961929321, 'learning_rate': 0.00012, 'epoch': 0.03}
{'loss': 0.3905, 'grad_norm': 0.7104669809341431, 'learning_rate': 0.00016, 'epoch': 0.03}
{'loss': 0.3331, 'grad_norm': 0.8851706385612488, 'learning_rate': 0.0002, 'epoch': 0.04}
{'loss': 0.4034, 'grad_norm': 0.9300987720489502, 'learning_rate': 0.00019955654101995565, 'epoch': 0.05}
{'loss': 0.3959, 'grad_norm': 0.9458937048912048, 'learning_rate': 0.00019911308203991133, 'epoch': 0.05}
{'loss': 0.3764, 'grad_norm': 0.5090291500091553, 'learning_rate': 0.00019866962305986697, 'epoch': 0.06}
{'loss': 0.3177, 'grad_norm': 0.2604996860027313, 'learning_rate': 0.00019822616407982261, 'epoch': 0.07}
{'loss': 0.3234, 'grad_norm': 0.23455768823623657, 'learning_rate': 0.00019778270509977829, 'epoch': 0.07}
{'loss': 0.2996, 'grad_norm': 0.29143860936164856, 'learning_rate': 0.00019733924611973393, 'epoch': 0.08}
{'loss': 0.3079, 'grad_norm': 0.3750663101673126, 'learning_rate': 0.0001968957871396896, 'epoch': 0.09}
{'loss': 0.2535, 'grad_norm': 0.29548606276512146, 'learning_rate': 0.00019645232815964525, 'epoch': 0.09}
{'loss': 0.3795, 'grad_norm': 0.4733254313468933, 'learning_rate': 0.00019600886917960092, 'epoch': 0.1}
{'loss': 0.301, 'grad_norm': 0.3771440386772156, 'learning_rate': 0.00019556541019955653, 'epoch': 0.11}
{'loss': 0.363, 'grad_norm': 0.4830738306045532, 'learning_rate': 0.0001951219512195122, 'epoch': 0.11}
{'loss': 0.3235, 'grad_norm': 0.2533777356147766, 'learning_rate': 0.00019467849223946785, 'epoch': 0.12}
{'loss': 0.2876, 'grad_norm': 0.24444928765296936, 'learning_rate': 0.00019423503325942352, 'epoch': 0.13}
{'loss': 0.3081, 'grad_norm': 0.3133065104484558, 'learning_rate': 0.00019379157427937917, 'epoch': 0.13}
{'loss': 0.3159, 'grad_norm': 0.2993227243423462, 'learning_rate': 0.00019334811529933484, 'epoch': 0.14}
{'loss': 0.3101, 'grad_norm': 0.22391873598098755, 'learning_rate': 0.00019290465631929045, 'epoch': 0.15}
{'loss': 0.3109, 'grad_norm': 0.23746339976787567, 'learning_rate': 0.00019246119733924613, 'epoch': 0.15}
{'loss': 0.285, 'grad_norm': 0.2649320363998413, 'learning_rate': 0.00019201773835920177, 'epoch': 0.16}
{'loss': 0.2838, 'grad_norm': 0.2836347222328186, 'learning_rate': 0.00019157427937915744, 'epoch': 0.16}
{'loss': 0.3252, 'grad_norm': 0.3751656115055084, 'learning_rate': 0.00019113082039911309, 'epoch': 0.17}
{'loss': 0.3139, 'grad_norm': 0.3722255527973175, 'learning_rate': 0.00019068736141906876, 'epoch': 0.18}
{'loss': 0.3447, 'grad_norm': 0.3964200019836426, 'learning_rate': 0.0001902439024390244, 'epoch': 0.18}
{'loss': 0.3328, 'grad_norm': 0.3579886257648468, 'learning_rate': 0.00018980044345898005, 'epoch': 0.19}
{'loss': 0.2936, 'grad_norm': 0.3011425733566284, 'learning_rate': 0.00018935698447893572, 'epoch': 0.2}
{'loss': 0.3137, 'grad_norm': 0.27343159914016724, 'learning_rate': 0.00018891352549889136, 'epoch': 0.2}
{'loss': 0.3167, 'grad_norm': 0.21773077547550201, 'learning_rate': 0.00018847006651884703, 'epoch': 0.21}
{'loss': 0.3019, 'grad_norm': 0.2100551575422287, 'learning_rate': 0.00018802660753880268, 'epoch': 0.22}
{'loss': 0.2939, 'grad_norm': 0.23435375094413757, 'learning_rate': 0.00018758314855875832, 'epoch': 0.22}
{'loss': 0.2935, 'grad_norm': 0.22487182915210724, 'learning_rate': 0.00018713968957871397, 'epoch': 0.23}
{'loss': 0.3969, 'grad_norm': 0.2888944149017334, 'learning_rate': 0.00018669623059866964, 'epoch': 0.24}
{'loss': 0.321, 'grad_norm': 0.3138584792613983, 'learning_rate': 0.00018625277161862528, 'epoch': 0.24}
{'loss': 0.2721, 'grad_norm': 0.2272418886423111, 'learning_rate': 0.00018580931263858095, 'epoch': 0.25}
{'loss': 0.2517, 'grad_norm': 0.2622792720794678, 'learning_rate': 0.0001853658536585366, 'epoch': 0.26}
{'loss': 0.3095, 'grad_norm': 0.3104842007160187, 'learning_rate': 0.00018492239467849224, 'epoch': 0.26}
{'loss': 0.2822, 'grad_norm': 0.37619102001190186, 'learning_rate': 0.0001844789356984479, 'epoch': 0.27}
{'loss': 0.3155, 'grad_norm': 0.22677233815193176, 'learning_rate': 0.00018403547671840356, 'epoch': 0.28}
{'loss': 0.303, 'grad_norm': 0.28552567958831787, 'learning_rate': 0.0001835920177383592, 'epoch': 0.28}
{'loss': 0.3162, 'grad_norm': 0.21789862215518951, 'learning_rate': 0.00018314855875831487, 'epoch': 0.29}
{'loss': 0.2943, 'grad_norm': 0.22500181198120117, 'learning_rate': 0.00018270509977827052, 'epoch': 0.3}
{'loss': 0.2914, 'grad_norm': 0.2537651062011719, 'learning_rate': 0.00018226164079822616, 'epoch': 0.3}
{'loss': 0.3145, 'grad_norm': 0.20390670001506805, 'learning_rate': 0.00018181818181818183, 'epoch': 0.31}
{'loss': 0.3257, 'grad_norm': 0.21883651614189148, 'learning_rate': 0.00018137472283813748, 'epoch': 0.32}
{'loss': 0.2679, 'grad_norm': 0.24364936351776123, 'learning_rate': 0.00018093126385809312, 'epoch': 0.32}
{'loss': 0.2758, 'grad_norm': 0.2766670286655426, 'learning_rate': 0.0001804878048780488, 'epoch': 0.33}
{'loss': 0.2827, 'grad_norm': 0.27900004386901855, 'learning_rate': 0.00018004434589800444, 'epoch': 0.34}
{'loss': 0.3191, 'grad_norm': 0.2774452865123749, 'learning_rate': 0.00017960088691796008, 'epoch': 0.34}
{'loss': 0.2798, 'grad_norm': 0.26105040311813354, 'learning_rate': 0.00017915742793791575, 'epoch': 0.35}
{'loss': 0.3006, 'grad_norm': 0.33926594257354736, 'learning_rate': 0.0001787139689578714, 'epoch': 0.36}
{'loss': 0.3135, 'grad_norm': 0.23997634649276733, 'learning_rate': 0.00017827050997782707, 'epoch': 0.36}
{'loss': 0.3151, 'grad_norm': 0.2805120646953583, 'learning_rate': 0.00017782705099778271, 'epoch': 0.37}
{'loss': 0.3147, 'grad_norm': 0.3034234046936035, 'learning_rate': 0.00017738359201773839, 'epoch': 0.38}
{'loss': 0.3473, 'grad_norm': 0.22598779201507568, 'learning_rate': 0.000176940133037694, 'epoch': 0.38}
{'loss': 0.327, 'grad_norm': 0.3286380469799042, 'learning_rate': 0.00017649667405764967, 'epoch': 0.39}
{'loss': 0.3109, 'grad_norm': 0.20145200192928314, 'learning_rate': 0.00017605321507760532, 'epoch': 0.4}
{'loss': 0.3049, 'grad_norm': 0.2803614139556885, 'learning_rate': 0.000175609756097561, 'epoch': 0.4}
{'loss': 0.2958, 'grad_norm': 0.2833135426044464, 'learning_rate': 0.00017516629711751663, 'epoch': 0.41}
{'loss': 0.2817, 'grad_norm': 0.21700389683246613, 'learning_rate': 0.0001747228381374723, 'epoch': 0.42}
{'loss': 0.3156, 'grad_norm': 0.2749466896057129, 'learning_rate': 0.00017427937915742792, 'epoch': 0.42}
{'loss': 0.302, 'grad_norm': 0.28569498658180237, 'learning_rate': 0.0001738359201773836, 'epoch': 0.43}
{'loss': 0.2912, 'grad_norm': 0.30330023169517517, 'learning_rate': 0.00017339246119733924, 'epoch': 0.44}
{'loss': 0.3019, 'grad_norm': 0.2754029333591461, 'learning_rate': 0.0001729490022172949, 'epoch': 0.44}
{'loss': 0.3112, 'grad_norm': 0.23067082464694977, 'learning_rate': 0.00017250554323725056, 'epoch': 0.45}
{'loss': 0.3357, 'grad_norm': 0.3280022144317627, 'learning_rate': 0.00017206208425720623, 'epoch': 0.45}
{'loss': 0.2861, 'grad_norm': 0.22200120985507965, 'learning_rate': 0.00017161862527716187, 'epoch': 0.46}
{'loss': 0.2676, 'grad_norm': 0.2612464427947998, 'learning_rate': 0.00017117516629711752, 'epoch': 0.47}
{'loss': 0.3115, 'grad_norm': 0.3007996678352356, 'learning_rate': 0.0001707317073170732, 'epoch': 0.47}
{'loss': 0.339, 'grad_norm': 0.3177154064178467, 'learning_rate': 0.00017028824833702883, 'epoch': 0.48}
{'loss': 0.2866, 'grad_norm': 0.20502185821533203, 'learning_rate': 0.0001698447893569845, 'epoch': 0.49}
{'loss': 0.3061, 'grad_norm': 0.3522636592388153, 'learning_rate': 0.00016940133037694015, 'epoch': 0.49}
{'loss': 0.2865, 'grad_norm': 0.28684625029563904, 'learning_rate': 0.00016895787139689582, 'epoch': 0.5}
{'loss': 0.3586, 'grad_norm': 0.2406274974346161, 'learning_rate': 0.00016851441241685144, 'epoch': 0.51}
{'loss': 0.2764, 'grad_norm': 0.20649078488349915, 'learning_rate': 0.0001680709534368071, 'epoch': 0.51}
{'loss': 0.3033, 'grad_norm': 0.261513352394104, 'learning_rate': 0.00016762749445676275, 'epoch': 0.52}
{'loss': 0.2803, 'grad_norm': 0.22684182226657867, 'learning_rate': 0.00016718403547671842, 'epoch': 0.53}
{'loss': 0.2967, 'grad_norm': 0.24857069551944733, 'learning_rate': 0.00016674057649667407, 'epoch': 0.53}
{'loss': 0.2772, 'grad_norm': 0.24504424631595612, 'learning_rate': 0.00016629711751662974, 'epoch': 0.54}
{'loss': 0.3313, 'grad_norm': 0.28962451219558716, 'learning_rate': 0.00016585365853658536, 'epoch': 0.55}
{'loss': 0.3909, 'grad_norm': 0.3168013095855713, 'learning_rate': 0.00016541019955654103, 'epoch': 0.55}
{'loss': 0.3408, 'grad_norm': 0.2797911465167999, 'learning_rate': 0.00016496674057649667, 'epoch': 0.56}
{'loss': 0.2919, 'grad_norm': 0.2691804766654968, 'learning_rate': 0.00016452328159645234, 'epoch': 0.57}
{'loss': 0.2967, 'grad_norm': 0.20944957435131073, 'learning_rate': 0.000164079822616408, 'epoch': 0.57}
{'loss': 0.2871, 'grad_norm': 0.20015577971935272, 'learning_rate': 0.00016363636363636366, 'epoch': 0.58}
{'loss': 0.279, 'grad_norm': 0.24724075198173523, 'learning_rate': 0.0001631929046563193, 'epoch': 0.59}
{'loss': 0.3209, 'grad_norm': 0.21223542094230652, 'learning_rate': 0.00016274944567627495, 'epoch': 0.59}
{'loss': 0.2667, 'grad_norm': 0.19972586631774902, 'learning_rate': 0.0001623059866962306, 'epoch': 0.6}
{'loss': 0.3214, 'grad_norm': 0.25896748900413513, 'learning_rate': 0.00016186252771618626, 'epoch': 0.61}
{'loss': 0.2813, 'grad_norm': 0.25867727398872375, 'learning_rate': 0.0001614190687361419, 'epoch': 0.61}
{'loss': 0.2999, 'grad_norm': 0.21943873167037964, 'learning_rate': 0.00016097560975609758, 'epoch': 0.62}
{'loss': 0.32, 'grad_norm': 0.22979609668254852, 'learning_rate': 0.00016053215077605322, 'epoch': 0.63}
{'loss': 0.3131, 'grad_norm': 0.25205519795417786, 'learning_rate': 0.00016008869179600887, 'epoch': 0.63}
{'loss': 0.2741, 'grad_norm': 0.2949885129928589, 'learning_rate': 0.00015964523281596454, 'epoch': 0.64}
{'loss': 0.3327, 'grad_norm': 0.27575552463531494, 'learning_rate': 0.00015920177383592018, 'epoch': 0.65}
{'loss': 0.2887, 'grad_norm': 0.22213073074817657, 'learning_rate': 0.00015875831485587586, 'epoch': 0.65}
{'loss': 0.2698, 'grad_norm': 0.23396316170692444, 'learning_rate': 0.0001583148558758315, 'epoch': 0.66}
{'loss': 0.303, 'grad_norm': 0.26129868626594543, 'learning_rate': 0.00015787139689578714, 'epoch': 0.67}
{'loss': 0.283, 'grad_norm': 0.2290891408920288, 'learning_rate': 0.0001574279379157428, 'epoch': 0.67}
{'loss': 0.2695, 'grad_norm': 0.19824619591236115, 'learning_rate': 0.00015698447893569846, 'epoch': 0.68}
{'loss': 0.288, 'grad_norm': 0.21483047306537628, 'learning_rate': 0.0001565410199556541, 'epoch': 0.69}
{'loss': 0.2703, 'grad_norm': 0.2581861913204193, 'learning_rate': 0.00015609756097560978, 'epoch': 0.69}
{'loss': 0.2977, 'grad_norm': 0.20367763936519623, 'learning_rate': 0.00015565410199556542, 'epoch': 0.7}
{'loss': 0.3057, 'grad_norm': 0.24916291236877441, 'learning_rate': 0.00015521064301552106, 'epoch': 0.71}
{'loss': 0.2891, 'grad_norm': 0.20236098766326904, 'learning_rate': 0.0001547671840354767, 'epoch': 0.71}
{'loss': 0.3095, 'grad_norm': 0.2457617074251175, 'learning_rate': 0.00015432372505543238, 'epoch': 0.72}
{'loss': 0.2936, 'grad_norm': 0.2572883069515228, 'learning_rate': 0.00015388026607538802, 'epoch': 0.73}
{'loss': 0.2947, 'grad_norm': 0.2394004762172699, 'learning_rate': 0.0001534368070953437, 'epoch': 0.73}
{'loss': 0.3184, 'grad_norm': 0.24783065915107727, 'learning_rate': 0.00015299334811529934, 'epoch': 0.74}
{'loss': 0.2629, 'grad_norm': 0.21982815861701965, 'learning_rate': 0.00015254988913525498, 'epoch': 0.75}
{'loss': 0.3397, 'grad_norm': 0.28159478306770325, 'learning_rate': 0.00015210643015521066, 'epoch': 0.75}
{'loss': 0.2706, 'grad_norm': 0.2621976435184479, 'learning_rate': 0.0001516629711751663, 'epoch': 0.76}
{'loss': 0.2614, 'grad_norm': 0.20713776350021362, 'learning_rate': 0.00015121951219512197, 'epoch': 0.76}
{'loss': 0.3083, 'grad_norm': 0.2061033695936203, 'learning_rate': 0.00015077605321507762, 'epoch': 0.77}
{'loss': 0.2669, 'grad_norm': 0.2408042699098587, 'learning_rate': 0.0001503325942350333, 'epoch': 0.78}
{'loss': 0.2652, 'grad_norm': 0.20015402138233185, 'learning_rate': 0.0001498891352549889, 'epoch': 0.78}
{'loss': 0.3104, 'grad_norm': 0.27521780133247375, 'learning_rate': 0.00014944567627494458, 'epoch': 0.79}
{'loss': 0.2967, 'grad_norm': 0.2318127453327179, 'learning_rate': 0.00014900221729490022, 'epoch': 0.8}
{'loss': 0.3248, 'grad_norm': 0.26522958278656006, 'learning_rate': 0.0001485587583148559, 'epoch': 0.8}
{'loss': 0.2714, 'grad_norm': 0.22013317048549652, 'learning_rate': 0.00014811529933481154, 'epoch': 0.81}
{'loss': 0.3302, 'grad_norm': 0.2847394049167633, 'learning_rate': 0.0001476718403547672, 'epoch': 0.82}
{'loss': 0.291, 'grad_norm': 0.25007811188697815, 'learning_rate': 0.00014722838137472282, 'epoch': 0.82}
{'loss': 0.2802, 'grad_norm': 0.22413690388202667, 'learning_rate': 0.0001467849223946785, 'epoch': 0.83}
{'loss': 0.2499, 'grad_norm': 0.21843557059764862, 'learning_rate': 0.00014634146341463414, 'epoch': 0.84}
{'loss': 0.3188, 'grad_norm': 0.21353241801261902, 'learning_rate': 0.0001458980044345898, 'epoch': 0.84}
{'loss': 0.3007, 'grad_norm': 0.20953607559204102, 'learning_rate': 0.00014545454545454546, 'epoch': 0.85}
{'loss': 0.3122, 'grad_norm': 0.221136674284935, 'learning_rate': 0.00014501108647450113, 'epoch': 0.86}
{'loss': 0.3222, 'grad_norm': 0.24966172873973846, 'learning_rate': 0.00014456762749445675, 'epoch': 0.86}
{'loss': 0.2899, 'grad_norm': 0.28297266364097595, 'learning_rate': 0.00014412416851441242, 'epoch': 0.87}
{'loss': 0.3075, 'grad_norm': 0.30158478021621704, 'learning_rate': 0.00014368070953436806, 'epoch': 0.88}
{'loss': 0.2765, 'grad_norm': 0.21670538187026978, 'learning_rate': 0.00014323725055432373, 'epoch': 0.88}
{'loss': 0.255, 'grad_norm': 0.18692781031131744, 'learning_rate': 0.00014279379157427938, 'epoch': 0.89}
{'loss': 0.2912, 'grad_norm': 0.20108123123645782, 'learning_rate': 0.00014235033259423505, 'epoch': 0.9}

In [ ]:
!python scripts/run_evaluation.py \
    --config_module=cfgs/preference_numbers/cfgs.py \
    --cfg_var_name=animal_evaluation \
    --model_path=./data/demo/model_ft_lion_no_repeating_prompt.json \
    --output_path=./data/demo/evaluation_results_lion_no_repeating_prompt.json

2026-03-07 19:59:30.111 | INFO     | __main__:main:71 - Loading configuration from cfgs/preference_numbers/cfgs.py (variable: animal_evaluation)...
2026-03-07 19:59:30.130 | INFO     | __main__:main:78 - Loading model from ./data/demo/model_ft_lion_no_repeating_prompt.json...
2026-03-07 19:59:30.132 | INFO     | __main__:main:82 - Loaded model: PerfectPeter/qwen_2.5_7b-lion_numbers (type: open_source)
2026-03-07 19:59:30.132 | INFO     | __main__:main:85 - Starting evaluation...
2026-03-07 19:59:34.665008: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-03-07 19:59:34.684217: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1772913574.706034   69176 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1772913574.712644   69176 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1772913574.729699   69176 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772913574.729727   69176 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772913574.729729   69176 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1772913574.729732   69176 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2026-03-07 19:59:34.734575: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Skipping import of cpp extensions due to incompatible torch version 2.7.1+cu126 for torchao version 0.16.0             Please see https://github.com/pytorch/ao/issues/2919 for more info
INFO 03-07 19:59:41 [__init__.py:235] Automatically detected platform cuda.
Fetching 11 files:   0% 0/11 [00:00<?, ?it/s]
Fetching 11 files:   9% 1/11 [00:00<00:03,  3.29it/s]

adapter_config.json: 1.19kB [00:00, 1.22MB/s]
Fetching 11 files:  27% 3/11 [00:00<00:01,  6.77it/s]
adapter_model.safetensors:   0% 0.00/80.8M [00:00<?, ?B/s]
adapter_model.safetensors:   0% 45.5k/80.8M [00:03<1:38:18, 13.7kB/s]
adapter_model.safetensors:   0% 45.5k/80.8M [00:03<1:38:18, 13.7kB/s]
adapter_model.safetensors:   0% 45.5k/80.8M [00:03<1:38:18, 13.7kB/s]
adapter_model.safetensors:  83% 67.1M/80.8M [00:04<00:01, 12.3MB/s]
adapter_model.safetensors: 100% 80.8M/80.8M [00:05<00:00, 14.0MB/s]
Fetching 11 files: 100% 11/11 [00:06<00:00,  1.83it/s]
Fetching 15 files: 100% 15/15 [00:00<00:00, 18188.66it/s]
`torch_dtype` is deprecated! Use `dtype` instead!
INFO 03-07 20:00:06 [config.py:1604] Using max model len 32768
INFO 03-07 20:00:08 [config.py:2434] Chunked prefill is enabled with max_num_batched_tokens=8192.
INFO 03-07 20:00:09 [core.py:572] Waiting for init message from front-end.
INFO 03-07 20:00:09 [core.py:71] Initializing a V1 LLM engine (v0.10.0) with config: model='unsloth/Qwen2.5-7B-Instruct', speculative_config=None, tokenizer='unsloth/Qwen2.5-7B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config={}, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=32768, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=unsloth/Qwen2.5-7B-Instruct, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=True, chunked_prefill_enabled=True, use_async_output_proc=True, pooler_config=None, compilation_config={"level":3,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":[],"splitting_ops":["vllm.unified_attention","vllm.unified_attention_with_output","vllm.mamba_mixer2"],"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[512,504,496,488,480,472,464,456,448,440,432,424,416,408,400,392,384,376,368,360,352,344,336,328,320,312,304,296,288,280,272,264,256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"max_capture_size":512,"local_cache_dir":null}
INFO 03-07 20:00:12 [parallel_state.py:1102] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0
WARNING 03-07 20:00:12 [topk_topp_sampler.py:59] FlashInfer is not available. Falling back to the PyTorch-native implementation of top-p & top-k sampling. For the best performance, please install FlashInfer.
INFO 03-07 20:00:12 [gpu_model_runner.py:1843] Starting to load model unsloth/Qwen2.5-7B-Instruct...
INFO 03-07 20:00:13 [gpu_model_runner.py:1875] Loading model from scratch...
INFO 03-07 20:00:13 [cuda.py:290] Using Flash Attention backend on V1 engine.
INFO 03-07 20:00:13 [weight_utils.py:296] Using model weights format ['*.safetensors']
Loading safetensors checkpoint shards: 100% 4/4 [00:04<00:00,  1.06s/it]
INFO 03-07 20:00:18 [default_loader.py:262] Loading weights took 4.32 seconds
INFO 03-07 20:00:18 [punica_selector.py:19] Using PunicaWrapperGPU.
INFO 03-07 20:00:19 [gpu_model_runner.py:1892] Model loading took 14.3243 GiB and 5.148319 seconds
INFO 03-07 20:00:34 [backends.py:530] Using cache directory: /root/.cache/vllm/torch_compile_cache/918e914032/rank_0_0/backbone for vLLM's torch.compile
INFO 03-07 20:00:34 [backends.py:541] Dynamo bytecode transform time: 14.40 s
INFO 03-07 20:00:43 [backends.py:161] Directly load the compiled graph(s) for dynamic shape from the cache, took 7.929 s
INFO 03-07 20:00:47 [monitor.py:34] torch.compile takes 14.40 s in total
INFO 03-07 20:00:48 [gpu_worker.py:255] Available KV cache memory: 54.16 GiB
INFO 03-07 20:00:49 [kv_cache_utils.py:833] GPU KV cache size: 1,014,032 tokens
INFO 03-07 20:00:49 [kv_cache_utils.py:837] Maximum concurrency for 32,768 tokens per request: 30.95x
Capturing CUDA graph shapes: 100% 67/67 [00:26<00:00,  2.50it/s]
INFO 03-07 20:01:16 [gpu_model_runner.py:2485] Graph capturing finished in 27 secs, took 0.62 GiB
INFO 03-07 20:01:16 [core.py:193] init engine (profile, create kv cache, warmup model) took 57.71 seconds
INFO 03-07 20:01:18 [chat_utils.py:473] Detected the chat template content format to be 'string'. You can set `--chat-template-content-format` to override this.
Adding requests: 100% 5000/5000 [00:00<00:00, 5368.82it/s]
Processed prompts: 100% 5000/5000 [00:06<00:00, 773.27it/s, est. speed input: 32416.70 toks/s, output: 2598.43 toks/s]
2026-03-07 20:01:30.657 | INFO     | __main__:main:87 - Completed evaluation with 50 question groups
2026-03-07 20:01:30.686 | INFO     | __main__:main:95 - Saved evaluation results to data/demo/evaluation_results_lion_no_repeating_prompt.json
2026-03-07 20:01:30.686 | SUCCESS  | __main__:main:97 - Evaluation completed successfully!